### ISSUE TITLE
FEAT: Use black formatting

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#1001]
Feature request for developing, not a huge deal but I find it very helpful.

I love the automatic formatting that [black](https://github.com/psf/black) does. It's becoming quite a standard for python projects. Do you want to change to that? formatting all existing code would add some noise to git blame, although [that can be mitigated](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html). Besides that all that would need to happen is add to requirements and then add a CI check alongside the other static linters.

**Comment by fgregg** [comment]
sure, let's do it. i'm actually interested in an black autoformatter instead of a linter https://github.com/psf/black/actions/runs/17913292/workflow
