### ISSUE TITLE
Use clustering metrics, not pairwise metrics

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#1004]
As I explored accuracy metrics for #1002, I came across this very nice guide to clustering metrics: https://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation

Since what we're really doing in those benchmarks is clustering, shouldn't we be using a metric that focuses on clusters, instead of using pairwise precision/recall? I would think a user is more interested in `are these clusters 'good'` more than `is a randomly sampled record A correctly grouped/not grouped with record B`. The current pairwise metrics would make sense to use if dedupe stopped its work at the pairwise scoring phase, but since the main APIs go one step further, and actually do clustering for users, I would think we should use metrics that reflect that. If not replace them, then at least add these other metrics as well.

As an extension, instead of just replacing the metrics, we could do both: Apply the pairwise metrics after the scoring phase. Then we get a sense of how good our scoring is. Then we do the clustering, and we look at the clustering metrics. By looking at both stages, we can separate our areas of concern:
- How good is scoring?
- how good is clustering?
- how good is the scoring + clustering (ie the whole process)?
This is also of course extensible, and perhaps we want to track sub-metrics for the blocking phase.

@fgregg @fjsj any thoughts?

**Comment by fgregg** [comment]
i've tried clustering metrics, particularly the rand index suggested in those docs. they are not a very good fit for record linkage.

empirically, in record linkage, the number of clusters in the data tend to grow close to linearly. this means, as the docs you link to indicate, that the unadjusted rand index tends to be very close to 1.0.

So you could adjust it, but in order to get the adjustment right you need the right random model, which isn't straightforward for record linkage, and if you don't get that just right you no longer have a metric that ranges between 0 and 1.

I would also point out that the pairwise metric is embedded in the rand index.

**Comment by fjsj** [comment]
@NickCrews AFAIK, overall the record linkage / entity resolution research benchmarks use pairwise precision/recall, even if the end result is clustered. I've seen some non-technical users of entity resolution systems care more for "good looking" clusters or clusters with an obvious "canonical record" than overall precision/recall of all pairs across all clusters, but I don't know any metrics that can capture that generally.

**Comment by NickCrews** [comment]
Thanks both of you for your explanations.

I didn't read into the details of the adjusted rand index, so I was assuming that the adjustment would just work, but I think I get the gist of the problem you mean (what exactly is a "random" assignment to use your baseline?).

OK, that puts us in good company if others are using the pair-wise scores even for clustering results. It just felt like we were missing out on tools that were designed exactly for our needs. But I guess they are more relevant for other types of clustering problems.

Sorry for the noise!

**Comment by fgregg** [comment]
not at all. it’s a good decision to have.
