### ISSUE TITLE
Benchmarking on demand

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#1009]
The benchmarking is great, but adds significant time to our CI builds.

would be great to run the in-branch benchmarking code once as a integration test, and then either request a full benchmarking run by talking to a bot or setting a label or some other similar mechanism

cc @NickCrews

**Comment by fgregg** [comment]
something like this would be very cool
https://pakstech.com/blog/gh-actions-issue-comments/

**Comment by NickCrews** [comment]
Yes, once on linux as an integration test, then on demand seems good.

How about pretty much exactly this? https://github.com/pandas-dev/pandas/blob/main/.github/workflows/asv-bot.yml

There you can comment `@github-actions benchmark canonical_gazetteer.Gazetteer.track_recall` and it will run whichever benchmarks match that regex.

Also could do something more low-level like `@benchmark args` and then it would run `asv continuous ${args}`, eg `@benchmark -b canonical_gazetteer.Gazetteer.track_recall upstream/main HEAD` results in `asv continuous -b canonical_gazetteer.Gazetteer.track_recall upstream/main HEAD`

Preference on either of those?

**Comment by fgregg** [comment]
i'd like to run each of the code examples once under all platforms as an integration test as there is some weirdnesses that has uncovered in the past.

something like

```
pip install benchmark
python -m benchmark.canonical
python -m benchmark.cononical_gazetteer
...
```

would be fine!



> Yes, once on linux as an integration test, then on demand seems good.
> 
> How about pretty much exactly this? https://github.com/pandas-dev/pandas/blob/main/.github/workflows/asv-bot.yml
> 
> There you can comment `@github-actions benchmark canonical_gazetteer.Gazetteer.track_recall` and it will run whichever benchmarks match that regex.
> 
> Also could do something more low-level like `@benchmark args` and then it would run `asv continuous ${args}`, eg `@benchmark -b canonical_gazetteer.Gazetteer.track_recall upstream/main HEAD` results in `asv continuous -b canonical_gazetteer.Gazetteer.track_recall upstream/main HEAD`
> 
> Preference on either of those?

i like `@github-actions benchmark canonical_gazetteer.Gazetteer.track_recall` 

would like to be able to do `@github-actions benchmark` without a regex and have that run all benchmarks.

It would be slick to put the benchmarks inline in the comment, but that's something we can do later!

**Comment by NickCrews** [comment]
OK I'll write a PR
