### ISSUE TITLE
reformat asv output to markdown table

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#1021]
so it looks something like https://github.com/dedupeio/dedupe/pull/992#issuecomment-1120334269, which i manually turned into a markdown table.

**Comment by NickCrews** [comment]
Perhaps this is actually something that should be upstreamed into ASV? eg a `--format=markdown` flag ?

**Comment by fgregg** [comment]
oh, that’s a good idea!

**Comment by NickCrews** [comment]
Made upstream issue at https://github.com/airspeed-velocity/asv/issues/1210

**Comment by fgregg** [comment]
since they never responded to your comment @NickCrews , i hacked something together to accomplish this. https://github.com/dedupeio/dedupe/pull/992#issuecomment-1139240914

going to go ahead and close
