### ISSUE TITLE
CanopyIndex stop word removal non-determinism

### ISSUE THREAD

**Issue by oreccb** [dedupeio/dedupe#1029]
I trained a dedupe model for address matching and ended up seeing different partition() results for the same input across different executions. I traced the non-deterministic behavior to one of my predicates (`TfidfNGramCanopyPredicate: (0.6, address1)` as seen in some log output. More specifically, I would see different sets of stop words being removed across different runs by looking at this log [line](https://github.com/dedupeio/dedupe/blob/main/dedupe/canopy_index.py#L30). 

I put in some debug logs and noticed that the tfidf counts seemed to always be the same but the stop words removed were not always the same which ended up correlating to different end results. I added a log message before this [line](https://github.com/dedupeio/dedupe/blob/main/dedupe/canopy_index.py#L28) to further check out what was happening.

```python
       for wid, docs in self.index._wordinfo.items():
            logger.info(f"  {wid} {self.lexicon._words[wid]} {len(docs)}")   # new log
            if len(docs) > threshold:
                word = self.lexicon._words[wid]
                logger.info("Removing stop word {}".format(word))
                del self.index._wordinfo[wid]
                continue
```

One example set of log output is this:

```
INFO:dedupe.canopy_index:  1  F 277
INFO:dedupe.canopy_index:  2  S 3041
INFO:dedupe.canopy_index:Removing stop word  S
INFO:dedupe.canopy_index:  4 34 252
INFO:dedupe.canopy_index:  5 4  805
```

I noticed the the wid of 3 was missing which tells me it was skipped. I then changed the code to be like this and re-ran:

```python
       for wid, docs in self.index._wordinfo.items():
            logger.info(f"  {wid} {self.lexicon._words[wid]} {len(docs)}")   # new log
            if len(docs) > threshold:
                word = self.lexicon._words[wid]
                logger.info("Removing stop word {}".format(word))
                #del self.index._wordinfo[wid]
                #continue
```

Then I would see output like this (note that it seems like the iteration order is not defined but I think that is expected):

```
INFO:dedupe.canopy_index:  1  D 1064
INFO:dedupe.canopy_index:Removing stop word  D
INFO:dedupe.canopy_index:  2  S 3041
INFO:dedupe.canopy_index:Removing stop word  S
INFO:dedupe.canopy_index:  3 12 561
INFO:dedupe.canopy_index:  4 26 266
INFO:dedupe.canopy_index:  5 6  737
```

In this case, by not calling `del` on the wordinfo entry, it did not skip the next entry after removing a stop word. So it looks like the non-determinism I was seeing in my end partition output is due to different stop words being removed due to this iteration bug across different executions. This situation of different stop words being removed will occur when they happen to be next to each other in wid order. I haven't yet been able to trace through the code to figure out what exactly is going wrong in the `del` operation. Maybe this is incorrect usage or there is some internal bug in the data structure but not sure. 

I am using python 3.8.10 on MacOS with dedupe-2.0.13

**Comment by fgregg** [comment]
fantastic bug report! thank you!

**Comment by oreccb** [comment]
no problem! thanks for the quick fix.

**Comment by oreccb** [comment]
I think there might be a small bug introduced with the fix: https://github.com/dedupeio/dedupe/commit/1d01808f574f190a22c9d524c826caf54fc29cc6#r75644084
