### ISSUE TITLE
CI fails for PRs from forks

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#1035]
#1033 fails, during checkout of the repo. Assuming it is due to changes made during https://github.com/dedupeio/dedupe/commit/7e24af24418c42af4419f6a35e358b2cca91a9f1

Per https://github.community/t/cant-push-to-forked-repository-on-the-original-repositorys-pull-request-with-github-token/16287/2, what you want this action to do is impossible for forked repos. Maybe add a conditional that skips this workflow if the PR is coming from a fork? @fgregg

**Comment by fgregg** [comment]
thanks @NickCrews , I noticed that. makes sense, but kind of a bummer!

let's just do the linting, and skip the autocommitting?

**Comment by NickCrews** [comment]
Yeah that looks good, thanks!
