### ISSUE TITLE
tests for breaking changes to settings file

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#1044]
We should try diligently to have future versions of dedupe be able to use settings file created by previous versions. 

Unfortunately, we. don't have any real test for this right now.

For PRs, it would be good to create a step in our tests that

1. checked out the main branch, created a canonical settings file
2. checkout out the head of the PR, attempt to run the canonical benchmark with the settings file

**Comment by fgregg** [comment]
Relates to #1045

**Comment by NickCrews** [comment]
More rigorous would be to test against every previous version of setting files, but just comparing against main seems way easier and I bet would catch 90% of incompatibilities
