### ISSUE TITLE
Create __setstate__to smooth over data model refactor

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#1045]
@NickCrews proposed a very nice refactor of the DataModel class, which i brought in: #1034 

unfortunately, this code can no longer read in previous setting files created by previous versions of dedupe

the python docs recommend using `__setstate__` to smooth over just such changes: https://docs.python.org/3/library/pickle.html#object.__setstate__

along with the code get previous pickled settings file to load, we should also introduce a version number to the data model class for future proofing.

**Comment by fgregg** [comment]
@NickCrews can you take a look?

**Comment by NickCrews** [comment]
Yes, something should be improved.

One potential option that I'm not sure if it works or not, is https://github.com/cloudpipe/cloudpickle.

**Comment by NickCrews** [comment]
Another thing to think about is I don't think that scikit learn supports this sort of pickling. If you want to store a trained model in scikit learn that is out of band. you just literally pickle the entire model object. So what that could look like for us is not actually storing a quote unquote settings file, but just making it so there isn't a distinction between dedupe object and a staticDedupe object and if you want to store your model you just pickle the entire object and unpickle that and use it whenever you want later.

**Comment by fgregg** [comment]
that’s basically what we are doing. we pickle the entire classifier

**Comment by fgregg** [comment]
oh, i see what you are saying. that’s an interesting idea, but a bigger change then this issue. please open an issue for this idea and we can discuss

**Comment by fgregg** [comment]
we initially started with a human readable settings file, but it got pretty limiting and complicated. i don’t think we should try that again

**Comment by NickCrews** [comment]
> we initially started with a human readable settings file, but it got pretty limiting and complicated. i don’t think we should try that again

That is some good history I didn't know. I would believe it. Other ML libraries don't do this, so seems like pickling should be adequate for us too.

Did you see my mention of `cloudpickle`?

**Comment by fgregg** [comment]
i’ve addressed this issue for now. we can address the rest of the ideas in the other pickle issue
