### ISSUE TITLE
Inconsistent alphaNumericPredicate behavior

### ISSUE THREAD

**Issue by Nephirus** [dedupeio/dedupe#1046]
Hi, I believe `alphaNumericPredicate` implementation is inconsistent.

Example:
```
In [1]: from dedupe.predicates import alpha_numeric

In [2]: alpha_numeric("a_1")
Out[2]: ['a', '1']

In [3]: alpha_numeric("a 1")
Out[3]: ['1']

In [4]: alpha_numeric("a")
Out[4]: []

In [5]: alpha_numeric("1")
Out[5]: ['1']
```

Should it really match `'a'` for `'a_1'` input, if it doesn't match it for `'a 1'` or just `'a'`?

**Comment by NickCrews** [comment]
What is desired behavior? a set of all alphanumeric tokens, with the boundary between tokens being all non-alphanumeric characters?

> Should it really match 'a' for 'a_1' input, if it doesn't match it for 'a 1' or just 'a'?

@Nephirus I don't understand what you're saying here, can you please elaborate or phrase that differently?

Is this what we're looking for:
```
"a_1" -> a, 1
"a 1" -> a, 1
"a,1" -> a, 1
"a1 b2" -> a1, b2
"a1b2" -> a1b2
"a" -> a
"1" -> 1
```
?
