### ISSUE TITLE
Enforce match when 2 fields are equal

### ISSUE THREAD

**Issue by the-whopper** [dedupeio/dedupe#1075]
Hello Dedupe Team,

Firstly, love the product!

This is less of bug and more of question/how to.

I need to enforce a hard rule. i.e when field1 == field1 then match. This is much like the custom comparator example shown in the doco except i need to ensure it adhered to consistently i.e it is definitely a match if it is true. I have tried using the below custom comparator but i am not getting the desired result. In addition when using the custom comparator and loading from a model i get the following error: `This settings file is not compatible with the current version of dedupe. This can happen if you have recently upgraded dedupe.`

Example custom comparator
`def same_or_not_comparator(field_1, field_2):
  if field_1 and field_2 :
      if field_1 == field_2 :
          return 0
      else:
          return 1`

Any help you can give would be greatly appreciated

**Comment by fgregg** [comment]
this is not a feature we are adding at this time.
