### ISSUE TITLE
Add random_state everywhere for reproducibility

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#1089]
Won't be fun to feed this through everywhere, but it would be great if things were reproducible. I think the way to accomplish this is to add a random_state arg to any function invoking randomness, like sklearn, numpy etc does

**Comment by fgregg** [comment]
is it not sufficient to set 

```
random.seed
numpy.random.seed
```
?

**Comment by NickCrews** [comment]
IDK, I assumed since those libs did it that way there was good reason. haven't found what it is though. perhaps two libraries set the random seed globally like that and then they clash??

Seems like we could let this lie, I'm not running into a particular issue

**Comment by fgregg** [comment]
theatre a number of tests that use this random seed setting and that seems to work well enough for that
