### ISSUE TITLE
Cut a release that includes #1087

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#1095]
I have monkeypatched in a custom classifier that results in 80% of the scores being 0. For one thing, this is causing the infinite loop bug, but even if I set them to .000001 to get around that bug, it still is writing way more edges to the scores memmap than is required, which is 1 running me out of disk space and 2 being way slower than needed.

It would be great to be able to use the code on main that fixes this.

https://github.com/dedupeio/dedupe/pull/1087

**Comment by fgregg** [comment]
triggered a deployment. thanks!

**Comment by fgregg** [comment]
2.0.18 is on pypi, thanks!

**Comment by NickCrews** [comment]
Thank you!
