### ISSUE TITLE
Is incremental clustering supported?

### ISSUE THREAD

**Issue by lmores** [dedupeio/dedupe#1113]
_This request would better fit the "Discussions" session of GitHub, however, as it does not seem to be used in this repository, I am posting this here (feel free to move it if you like)._

Essentially, my question is: is it possible to achieve incremental clustering starting from a base (large) data set and adding new records from time to time (without reanalysing everything from scratch)?

Let me add a few more details: so far I realized a simple demo for my use case following the [postgres example](https://github.com/dedupeio/dedupe-examples/tree/master/pgsql_big_dedupe_example).

After the initial run (done exactly in the same way as in the postgres example above), when new records become available I suspect that I should do something along these lines:

1. Update the `blocking_map` (initially built [here](https://github.com/dedupeio/dedupe-examples/blob/a767fa5a127bd56afc574c66895bb9b783152e04/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py#L241)) to take into account the new records.
If I correctly understood the purpose of the blocking map, new blocking rules should be generated if the new incoming records do not belong to existing clusters (and probably no new blocking rules should be generated if new records match an existing cluster?).

2. Update the existing clusters with the new records.
This is the incremental counterpart of what is done at [this line](https://github.com/dedupeio/dedupe-examples/blob/a767fa5a127bd56afc574c66895bb9b783152e04/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py#L292) of the one-shot use case:

    ```python
    clustered_dupes = deduper.cluster(deduper.score(record_pairs(read_cur)),threshold=0.5)
    ```

    If `A` is the set of already examined records and `N` is the set of new records (possibly just one), I expect that the incremental version of this step will try to match all records inside `N` with all the other records in `N` and all the records in `A` (but will not compare pairs of records in `A` as they have already been clustered).
    According to how clusters are generated by the dedupe library (I still do not know!) this may cause two or more existing clusters containing records in `A` to be merged into one.

Further questions:
  * The ultimate goal in my case is being able to quickly anser the question: "Given a (possibly never seen) record `r`, does it belong to an already existing cluster?".
    Of course, if I am able to incrementally add the record `r` to the data set inspected by the dedupe library I will be able to answer this question looking at which cluster `r` belongs (possibly just himself).

    However, depending on how the dedupe library works (which I do not know yet), checking if `r` matches other already seen records may be answered in another (faster) way, without simultaneously adding `r` to the inspected dataset (this operation may be delayed to a later time).
    Can you elaborate on this?

  * In my use case the initial data set will probably contain ~10M records, which will probably grow up to ~100M.
  Do you have any experience about the time and space resources needed with datasets of this size?

Thank you a lot!

**Comment by thomaswyrick** [comment]
Sorry, this isn't an answer. Possibly serendipity though. My company Semarchy has a commercial product XDM that will satisfy your use case. Besides bulk fuzzy matching, it exposes a "look up before create" API call. In terms of volume, we have customers with 600M+ source records. If you want to learn more or setup a trial in your infrastructure, message me at: thomas.wyrick@semarchy.com. Cheers!

**Comment by fgregg** [comment]
Hi @lmores,

that's the use case that the [gazetteer class](https://docs.dedupe.io/en/latest/API-documentation.html#gazetteer-objects) is for. 

Once you have cleaned up data, you can turn that into you canonical list, and then match against it.

**Comment by lmores** [comment]
Hi, unfortunately my cleaned up data is still far from being a canonical list with unique addresses.
How can I face my use case if I do not have a canonical list at hand?
Does dedupe cover this use case?
Can I do it incrementally (in the sense explained in the original post)?

**Comment by fgregg** [comment]
the dedupe lib doesn’t currently provide any facilities, but the way to do this is to set up a gazetteer class with your data and to **also** keep track of each records cluster assignment in an auxiliary table (starting with the results of your imperfect clustering). 

then when a new record comes in, and it matches only one of your existing records, you apply the cluster assignment of that target record.

if the new record matches records from two clusters that’s an opportunity to merge clusters.

currently you have to do that bookkeeping yourself
