### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by paulmakeraiimi** [dedupeio/dedupe#1118]
Running through the csv example and I am getting the following exception. If I comment out 'dedupe\api.py' line 1483/4 it works fine. looks like the fille is not being closed somewhere. Thanks. 

importing data ...
reading from csv_example_learned_settings
clustering...
Traceback (most recent call last):
  File "C:\work\MyProjects\PythonPlayGround\dedupe\csv_example.py", line 149, in <module>
    clustered_dupes = deduper.partition(data_d, 0.5)
  File "C:\work\MyProjects\PythonPlayGround\dedupe\venv\lib\site-packages\dedupe\api.py", line 178, in partition
    _cleanup_scores(pair_scores)
  File "C:\work\MyProjects\PythonPlayGround\dedupe\venv\lib\site-packages\dedupe\api.py", line 1484, in _cleanup_scores
    os.remove(mmap_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\pmaker\\AppData\\Local\\Temp\\tmpx43a12wb'

**Comment by oliverzeman9** [comment]
Hey @paulmakeraiimi , I'm having the same issue!

How should I solve the issue as a regular user that wants to use the dedupe package in Jupyter Notebook?

**Comment by paulmakeraiimi** [comment]
the easiest temporary way (until its fixed properly) is to edit the file above in \Lib\site-packages\dedupe ... This will be in your main Python install or your venv (if you are using a virtual environment)
