### ISSUE TITLE
About Inverse Document Frequency implementation

### ISSUE THREAD

**Issue by lmores** [dedupeio/dedupe#1126]
Currently [this line](https://github.com/dedupeio/dedupe/blob/0b0b324f56a0b4eaf41d20eb53f5e5dc802f9d4f/dedupe/canopy_index.py#L40) computes the inverse document frequency of a document (a string) inside a corpus.

That line reads `idf = numpy.log1p(N / len(docs))` which computes the value `log(1 + x)` with `x =  N / len(docs)`. However this formula does not appear in any of the variants [listed on wikipedia](https://en.wikipedia.org/wiki/Tf%E2%80%93idf#Inverse_document_frequency_2) that compute the idf. Why this choice?

In case we want to use the smooth idf, the formula should be `idf = 1 + numpy.log(N / (1 + len(docs)))`.

**Comment by fgregg** [comment]
it's a form of smoothing, of which there are many strategies. if you'd like to show your proposed smoothing strategy will make a difference in dedupe performance, i'd be happy to look at the PR.
