### ISSUE TITLE
Levenshtein_search GPL 3-licensed Revisited

### ISSUE THREAD

**Issue by sarmohamed** [dedupeio/dedupe#1128]
I am running into an issue where I cannot find a way to prove that Levenshtein_search version 1.4.5 is indeed MIT licensed. When investigated, dedupe is showing us as GPL 3 licensed due to the fact that levenshtein_search is GPL 3 licensed.  I came across the below comment from a closed issue dating back to March 2022.  Is there a way to prove that levenshtein_search 1.4.5 is indeed MIT as the comment claims? Looking on pypi, I cannot find this information and the levenshtein_search github page shows the library as GPL 3.

Comment from closed issue:

The last version on pypi 1.4.5 is licensed as MIT. So, I can pin to that version

I've very much appreciated @mattandahalfew's library, and I'm sure he has his reasons for making this change.

_Originally posted by @fgregg in https://github.com/dedupeio/dedupe/issues/885#issuecomment-802983906_

**Comment by fgregg** [comment]
you can look at the git commit history of https://github.com/mattandahalfew/Levenshtein_search

**Comment by fgregg** [comment]
good sleuthing. it wasn't. dedupe now depends on https://github.com/dedupeio/Levenshtein_search, which forks at https://github.com/dedupeio/Levenshtein_search/tree/dc50b04d0b41a8bf190ade70e8d3292dbb673ec8

when it was MIT licensed!

**Comment by sarmohamed** [comment]
Thank you @fgregg, your response is very helpful!
