### ISSUE TITLE
Installation breaks because Levenshtein_search version 1.4.5 is no more listed on PyPi

### ISSUE THREAD

**Issue by fsal** [dedupeio/dedupe#1129]
Installing dedupe now breaks because Levenshtein_search version 1.4.5 is not listed anymore on PyPi. 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/9203508/212566995-55d1dbd8-e626-4336-9031-01d616770840.png">

There is version 1.4.6 though, released yesterday. 
I guess the dependency should be updated in the [pyproject.toml](https://github.com/dedupeio/dedupe/blob/main/pyproject.toml#L39) and a new dedupe version released and uploaded to PyPi, because right now it is impossible to install.

**Comment by fsal** [comment]
as the maintainer of the package says [here](https://github.com/mattandahalfew/Levenshtein_search/issues/29#issuecomment-1383253785), the only solution is updating the version number in the dependencies in the [pyproject.toml](https://github.com/dedupeio/dedupe/blob/main/pyproject.toml#L39)

**Comment by mattandahalfew** [comment]
Agree - would recommend changing the requirement to >=1.4.5

**Comment by fgregg** [comment]
Levenshtein-search changed its license from MIT in 1.4.5 to GPL in 1.4.6. 

as we want dedupe to remain MIT, we cannot depend on GPL versions, so i cannot simply bump the version number.

i have a fork of the library up to the GPL license change, and i can release a version of that to pypi tonight, along with a new version of dedupe that points to the forked library.

**Comment by mattandahalfew** [comment]
1.4.4 is MITOn Jan 16, 2023, at 6:17 PM, Forest Gregg ***@***.***> wrote:﻿
Levenshtein-search changed its license from MIT in 1.4.5 to GPL in 1.4.6.
as we want dedupe to remain MIT, we cannot depend on GPL versions, so i cannot simply bump the version number.
i have a fork of the library up to the GPL license change, and i can release a version of that to pypi tonight, along with a new version of dedupe that points to the forked library.

**Comment by fgregg** [comment]
thanks, @mattandahalfew !
