### ISSUE TITLE
dedupe Is Not Opening Question window To Provide Label

### ISSUE THREAD

**Issue by ragvendra3898** [dedupeio/dedupe#1137]
Hi Guys,
I have a python script which I converted to GUI using python gooey and in this I am using python_dedupe.dedupe_dataframe() to perform deduplication but while I am running the script from command without gooey mode then it ask for labelling data which I can provide from command line like y for yes, n for no but while I am running the script in GUI mode it is not providing questions window to provide answer, I am facing this issue when I updated my dedupe from 2.0.11 to 2.0.17 version.
for reference I am attaching screenshot, please help me, I will be thankful to you.
Thank You
![dedupe_not_opening_question_window](https://user-images.githubusercontent.com/62380006/212815810-914e7793-3c3a-4abc-aa4d-fb22f58142d9.png)

**Comment by ragvendra3898** [comment]
Also I gone through changelog.md to see what changes are made in new version but I did not find version after 2.0.6 while I am using 2.0.17

**Comment by fgregg** [comment]
looks like you are using https://github.com/Lyonk71/pandas-dedupe

please direct questions to that repo.

**Comment by ragvendra3898** [comment]
Also I forget to mention that while I am trying to run the same script from jupyter notebook, I am getting the question window but not getting while running the script in GUI mode
![question_window is_coming _in_jupyter](https://user-images.githubusercontent.com/62380006/212819096-90fac78f-016f-4e9e-9189-8eb0003e5964.png)

**Comment by ragvendra3898** [comment]
> looks like you are using https://github.com/Lyonk71/pandas-dedupe
> 
> please direct questions to that repo.

thanks fgregg but I gone through the pandas-dedupe but they are using dedupe library and also this happening with me after updation of dedupe package
