### ISSUE TITLE
Can't import 'dedupe_dataframe' because of numpy

### ISSUE THREAD

**Issue by jordy-moddit** [dedupeio/dedupe#1150]
Hi,

I'm trying to import import pandas_dedupe but with the recent update of numpy I get error messages. Installing pandas_dedupe is no issue (version 1.5.0). I've installed dedupe (version 2.0.23) aswell but from both libraries I can't import 'dedupe_dataframe' because of the following error message.

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I've tried to upgrade Numpy, which is 1.24.2 at this moment.

It looks like my pandas_dedupe version and numpy version aren't compatible.

Thanks in advance.

**Comment by fgregg** [comment]
hi jordy, this is not a problem with dedupe, which has been using numpy 1.20 and higher for quite some time. please report this on https://github.com/Lyonk71/pandas-dedupe/blob/master/pandas_dedupe/dedupe_dataframe.py
