### ISSUE TITLE
Use of predict_proba

### ISSUE THREAD

**Issue by pecade** [dedupeio/dedupe#1162]
Just in case you use predict_proba from sklearn: The predict_proba method on sklearn classifiers does not actually predict probabilities, it predicts confidence scores. Specifically:

https://towardsdatascience.com/pythons-predict-proba-doesn-t-actually-predict-probabilities-and-how-to-fix-it-f582c21d63fc

**Comment by fgregg** [comment]
that's not what the article says. it says it produces predicited probablilites that may be miscalibrated.
