### ISSUE TITLE
BlockingError: No records have been blocked together.

### ISSUE THREAD

**Issue by bwenyenye** [dedupeio/dedupe#1179]
I am getting the following Blocking Error:BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on? If so, try adding more training data.

I figured the issue is from this line of code: clustered_dupes = deduper.cluster(deduper.score(record_pairs(read_cur)),
                                          threshold=0.5)
                                          
 I am using the PostgreSQL example. 

BlockingError                             Traceback (most recent call last)
Cell In[3], line 398
    396     print('clustering...')
    397     record_pairs_data = record_pairs(read_cur)
--> 398     clustered_dupes = deduper.cluster(deduper.score(record_pairs_data), threshold=0.5)
    421 print('writing results...')
    422 with write_con:

File ~/dss_home/code-envs/python/pyconda_38/lib/python3.8/site-packages/dedupe/api.py:125, in IntegralMatching.score(self, pairs)
    116 """
    117 Scores pairs of records. Returns pairs of tuples of records id and
    118 associated probabilities that the pair of records are match
   (...)
    122 
    123 """
    124 try:
--> 125     matches = core.scoreDuplicates(
    126         pairs, self.data_model.distances, self.classifier, self.num_cores
    127     )
    128 except RuntimeError:
    129     raise RuntimeError(
    130         """
    131         You need to either turn off multiprocessing or protect
   (...)
    134         [https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods"""](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods%22%22%22)
    135     )

File ~/dss_home/code-envs/python/pyconda_38/lib/python3.8/site-packages/dedupe/core.py:126, in scoreDuplicates(record_pairs, featurizer, classifier, num_cores)
    124 first, record_pairs = peek(record_pairs)
    125 if first is None:
--> 126     raise BlockingError(
    127         "No records have been blocked together. "
    128         "Is the data you are trying to match like "
    129         "the data you trained on? If so, try adding "
    130         "more training data."
    131     )
    133 record_pairs_queue: _Queue = Queue(2)
    134 exception_queue: _Queue = Queue()

BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on? If so, try adding more training data.

**Comment by rderidder-lda** [comment]
what if you try lowering your threshold?

**Comment by rderidder-lda** [comment]
also, i have found that 'dirty' data in the training data can cause the process to halt with that error.. 
could be records with special characters, nulls when you havent specified 'has missing'...

**Comment by bwenyenye** [comment]
> what if you try lowering your threshold? (Assuming you do have a bunch of training data being used)

I have tried everything including lowering the threshold and using clean data, nothing so far. However, i may have traced the error to this line of code: b_data = deduper.fingerprinter(full_data)

The other lines prior to that including full_data = ((row['donor_id'], row) for row in read_cur) are working as expected and i am able to print out and inspect them.
However b_data  is a generator object and i am unable to find code that can print it out so i can inspect its content. I have tried converting it to a list and even using the Next function, any tips on how i can print it out to inspect its contents? Thank you

**Comment by fgregg** [comment]
please provide a reproducible example

**Comment by bwenyenye** [comment]
> please provide a reproducible example
I am trying to deduplicate music records
Here is my code:
import psycopg2
import psycopg2.extras
import dedupe
import dedupe.backport
import time
import logging
import optparse
import locale
import itertools
import io
import os
import time
import pickle
import csv

class Readable(object):

    def __init__(self, iterator):

        self.output = io.StringIO()
        self.writer = csv.writer(self.output)
        self.iterator = iterator

    def read(self, size):

        self.writer.writerows(itertools.islice(self.iterator, size))

        chunk = self.output.getvalue()
        self.output.seek(0)
        self.output.truncate(0)

        return chunk
    
def record_pairs(result_set):

    for i, row in enumerate(result_set):
        a_record_id, a_record, b_record_id, b_record = row
        record_a = (a_record_id, a_record)
        record_b = (b_record_id, b_record)

        yield record_a, record_b

        if i % 10000 == 0:
            print(i)    
    
    



# potential issue here - zip
def cluster_ids(clustered_dupes):
    for cluster, scores in clustered_dupes:
        cluster_id = cluster[0]
        for track_id, score in zip(cluster, scores):
            yield track_id, cluster_id, score
            

if __name__ == '__main__':
    log_level = logging.WARNING
    logging.getLogger().setLevel(log_level)
    
    settings_file = '/home/dataiku/dss_home/managed_folders/MISSING_CONTENT_V2/6pRp11b4/yt_charts_history_settings'
    training_file = '/home/dataiku/dss_home/managed_folders/MISSING_CONTENT_V2/6pRp11b4/yt_charts_history_training.json'

    start_time = time.time()

    try:
        read_con = conn = psycopg2.connect(
            database='*****',
            user='*******',
            host='127.0.0.1',
            password='********',
            port='5030'
        )
        

        write_con = conn = psycopg2.connect(
            database='*****',
            user='*',
            host='127.0.0.1',
            password='*******',
            port='5030'
        )
       

        # Successful connection
        print("Successfully connected to the database")

    except Exception as e:
        # Print the error message if connection fails
        print(f"Error connecting to the database: {e}")

    # Pulling in data and creating a table with target fields
    
    print("Before adding data to target fields...")
    # potential issues - column names between the read and write table
    with read_con.cursor() as cur:
        cur.execute("SELECT track_title, track_artist, song_id FROM md_yt_charts_history_1")
        rows = cur.fetchall()
        
    print("After fetching all rows...")

    # Create the cleaned table using a separate connection for writing
    
    print("Creating a cleaned dataset table...")
    
    with write_con:
        with write_con.cursor() as cur:
            try:
                cur.execute("DROP TABLE IF EXISTS cleaned_yt_charts")
                cur.execute("""
                    CREATE TABLE cleaned_yt_charts AS
                    SELECT TRIM(LOWER(song_name)) AS track_title,
                           TRIM(LOWER(artist)) AS track_artist,
                           song_id AS track_id, 
                           country
                    FROM md_yt_charts_history_1
                    WHERE song_name IS NOT NULL 
                        AND artist IS NOT NULL
                        AND song_name != 'undefined'
                        AND country = 'GH'
                        LIMIT 200; 
                    """)
                write_con.commit()
                print("Table 'cleaned_yt_charts' created successfully.")
            except Exception as e:
                write_con.rollback()
                print(f"Error creating table: {e}")
                
     
    # Training
    print('Starting Training...')
    
    if os.path.exists(settings_file):
        print('reading from', settings_file)
        with open(settings_file, 'rb') as sf:
            deduper = dedupe.StaticDedupe(sf, num_cores=4)
    else:
        fields = [
            {'field': 'track_title', 'type': 'String', 'has missing': True},
            {'field': 'track_artist', 'type': 'String', 'has missing': True},
        ]
        
        deduper = dedupe.Dedupe(fields, num_cores=4)
    
    # Fetch data for training
    with read_con.cursor('yt_charts_data') as cur:
        cur.execute('SELECT track_title, track_artist FROM cleaned_yt_charts')
        temp_d = {i: {'track_title': row[0], 'track_artist': row[1]} for i, row in enumerate(cur)}
    
    
    if os.path.exists(training_file):
        print('reading labeled examples from', training_file)
        with open(training_file) as tf:
            deduper.prepare_training(temp_d, tf)
    else:
        deduper.prepare_training(temp_d)
        
    del temp_d
    
    
    
    # Active learning
    print('Starting active labeling...')
    
    
    dedupe.console_label(deduper)
    with open(training_file, 'w') as tf:
        deduper.write_training(tf)
        deduper.train(recall=0.90)
    
    with open(settings_file, 'wb') as sf:
        deduper.write_settings(sf)
        
    deduper.cleanup_training()
    
    
    
    
    # Blocking
    print('Blocking...')
    # Blocking
    
    print('Blocking...')
    print('Creating a blocking_map database')
    with write_con:
        with write_con.cursor() as cur:
            cur.execute("DROP TABLE IF EXISTS blocking_map")
            cur.execute("CREATE TABLE blocking_map"
                       "(block_key TEXT, track_id TEXT)")
            
            
    print('blocking_map created successfully')
            
       print('Creating Inverted index')

    for field in deduper.fingerprinter.index_fields:
        with read_con.cursor('field_values') as cur:
            cur.execute("SELECT DISTINCT %s FROM cleaned_yt_charts" % field)
            # add WHERE {field} IS NOT NULL
            field_data = (row[0] for row in cur)
            deduper.fingerprinter.index(field_data, field)         
  
    
    read_cur = read_con.cursor('track_select')

    read_cur.execute("SELECT track_id, track_title, track_artist FROM cleaned_yt_charts")

    full_data = ((row[0], row) for row in read_cur)
    
    counter = 0
    
    # Print each tuple in full_data
    for data_tuple in full_data:
        print(data_tuple)
        counter += 1
    print(f"Number of instances of data_tuple: {counter}")    
    print("track_id, row tuple printed successfully")
   
   
   
    print("track_id, row tuple printed successfully")
    
    b_data = deduper.fingerprinter(full_data)
    
   
        
    print("b_data created successfully")

    with write_con:
        with write_con.cursor() as write_cur:
            write_cur.copy_expert('COPY blocking_map FROM STDIN WITH CSV',
                                 Readable(b_data),
                                 size=10000)

deduper.fingerprinter.reset_indices()
    
# Create index on block key
print("Creating index on block key")

with write_con:
    with write_con.cursor() as cur:
        cur.execute("CREATE UNIQUE INDEX ON blocking_map"
                    "(block_key text_pattern_ops, track_id)")
                       
# Clustering
print("Creating the entity_map table")

with write_con:
    with write_con.cursor() as cur:
        print("Creating entity_map database...")
        cur.execute("DROP TABLE IF EXISTS entity_map")
        cur.execute("CREATE TABLE entity_map"
                   "(track_id TEXT, canon_id INTEGER, "
                   " cluster_score FLOAT, PRIMARY KEY(track_id))")
        
        
print("entity_map database created successfully...") 


print("Deduplication query...")

# Create a cursor without using a context manager
read_cur = read_con.cursor('pairs', cursor_factory=psycopg2.extensions.cursor)

# Execute the SQL query
read_cur.execute("""
    SELECT a.track_id,
            row_to_json((SELECT d from (SELECT a.track_title,
                                            a.track_artist
                                    ) d)),
            b.track_id,
            row_to_json((SELECT d from (SELECT b.track_title,
                                            b.track_artist
                                    ) d))
    from (SELECT DISTINCT l.track_id as east, r.track_id as west
            from blocking_map as l
            INNER JOIN blocking_map as r
            USING (block_key)
            WHERE l.track_id < r.track_id) ids
        INNER JOIN cleaned_yt_charts a on ids.east=a.track_id
        INNER JOIN cleaned_yt_charts b on ids.west=a.track_id
""")

print("After Deduplication query...")
print("Clustering...")

# Fetch data before exiting the with block
result_set = read_cur.fetchall()

# Use the fetched data to perform deduplication

clustered_dupes = deduper.cluster(deduper.score(record_pairs(result_set)),
                                 threshold=0.5)

# Close the cursor manually since we didn't use a context manager
#read_cur.close()

**Comment by fgregg** [comment]
that is not reproducible. i need data and training data and setting file.

**Comment by fgregg** [comment]
if you cannot share that because of privacy issues, we offer consulting services.

**Comment by bwenyenye** [comment]
> if you cannot share that because of privacy issues, we offer consulting services.

Okay, Thank you. One more question, when i print out full_data this is the output I get:
('r2FEdTZzbOM', ('r2FEdTZzbOM', 'country side', 'sarkodie feat. black sherif'))
('GgeTnpTkzI0', ('GgeTnpTkzI0', 'loaded', 'tiwa savage, asake'))
('aP-MBSrzFNo', ('aP-MBSrzFNo', "'letter from overseas'", 'larry gaaga & black sherif'))
('we5gSjpX03U', ('we5gSjpX03U', 'single', 'kuami eugene'))
('E1YDr0PYg34', ('E1YDr0PYg34', 'nirvana', 'kwesi arthur x kofi mole'))
('o_oenl2Be-w', ('o_oenl2Be-w', '2 sugar', 'wizkid'))
('DPBRGWUgQsA', ('DPBRGWUgQsA', 'soweto', 'victony & tempoe'))
('5BfoawaaARc', ('5BfoawaaARc', 'shatta montez', 'shatta wale'))
('9zEPGHPZCF8', ('9zEPGHPZCF8', 'red flags', 'ruger'))
('1FbzbsWSN88', ('1FbzbsWSN88', 'midnight', 'larruso'))

This is the expected format right?

**Comment by fgregg** [comment]
yes.
