### ISSUE TITLE
Strange import behaviour with Python 3.12.3 during debugging

### ISSUE THREAD

**Issue by ArVar** [dedupeio/dedupe#1192]
Apperently something has changen with how imports are processed in python when debugging.
In datamodel.py the __import__ function iterates throgh all key-value-pairs of the variables in frequency.py on import (!).
This leads to an incredible long import time when running in debugger. (VSCode Python Debugger)

I've checked the changelog for python 3.12.x and a lot of other ressources and did not find any hint. Maybe replacing __import__ with importlib.import_module can help.

Has anyone else a similar issue?

**Comment by ArVar** [comment]
I think, this is adressed here as well: https://github.com/microsoft/debugpy/issues/1496

**Comment by fgregg** [comment]
looks like it was fixed upstream https://github.com/python/cpython/issues/119118
