### ISSUE TITLE
ExistsType subclasses CategoricalType which requires categories

### ISSUE THREAD

**Issue by ArVar** [dedupeio/dedupe#1196]
I've tried to use the new syntax for field definitions and encountered a potential bug:

`dedupe.variables.Exists("first_name")`
doesn't work as stated in the Variable-definition.rst

The following error occurs:
> TypeError: CategoricalType.__init__() missing 1 required positional argument: 'categories'

due to `super().__init__(field, **kwargs)` referencing `CategoricalType`.

There might be different options to tackle this. As far as I've understood, it should be sufficient to hardcode 
`categories=[0, 1]` as kwarg.

**Comment by ArVar** [comment]
Just got a second view. Other Options might be: 
* remove `super().__init__(field, **kwargs)`
* inherit directly from FieldType

**Comment by fgregg** [comment]
thanks! I'll fix that up!
