### ISSUE TITLE
investigate asynchronous tools for more extensible active learning loop

### ISSUE THREAD

**Issue by derekeder** [dedupeio/dedupe#153]
[Asynchronous Programming in Python](http://xph.us/2009/12/10/asynchronous-programming-in-python.html)

[An Introduction to Asynchronous Programming and Twisted](http://krondo.com/blog/?p=1247)

**Comment by rahulkathet** [comment]
@declan - this link is not working https://github.com/purplebinder/dedupe-http-server. Is there any other path where we can review what is the output of the conversation.

**Comment by fgregg** [comment]
https://dedupe.io/

**Comment by declan** [comment]
@rahulkathet - yes, @fgregg now offers dedupe as a service. It's very good and I'd highly recommend it.
