### ISSUE TITLE
consolodate readme into read the docs?

### ISSUE THREAD

**Issue by derekeder** [dedupeio/dedupe#504]
Having both a Readme.md and Read the docs, both with slight variations on the same info seems a bit confusing.

I think we should remove most of the content from the Readme and point users over to Read the docs. Thoughts?

**Comment by fgregg** [comment]
hmmm... doesn't look like that to me. what sections seem duplicative?

**Comment by fgregg** [comment]
Maybe a more helpful comment would be that this repo README should primarily aimed at developers who want to hack on dedupe. Other users are probably better served by going to the documentation

BUT! this repo has *much* more google juice the dedupe.readthedocs. So, we may want to place a keep a few things here even if it is redundant.

**Comment by fgregg** [comment]
@derekeder are you still interested in doing this?
