### ISSUE TITLE
Sets of Addresses

### ISSUE THREAD

**Issue by robertf224** [dedupeio/dedupe#526]
Is there a recommended way to represent a set of addresses as a field with Dedupe?  I'm trying to link records that have sets of addresses that might not exactly match, but fuzzy overlap is meaningful.

**Comment by fgregg** [comment]
It sounds like you are looking for something like [Soft Tf-IDF](http://secondstring.sourceforge.net/javadoc/com/wcohen/ss/SoftTFIDF.html). We do not have an implementation for this type of comparator. 

@mattandahalfew, are you still interested in this https://github.com/datamade/dedupe/issues/436#issuecomment-255755272

**Comment by mattandahalfew** [comment]
I am still interested but realistically the timeline to complete it would be at least a couple of months.
