### ISSUE TITLE
Revisiting the save index methods

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#546]
Now, the indices that are used in blocking can be saved and restored. This only really seems useful for gazetteer classes. 

With the file-backed blocking introduced in 1.6.8, this becomes a lot more interesting. I think I might reduce the api for the saving and restoring of blocked records and indices for the gazetteer class and remove it from the other classes.

**Comment by mehrrsaa** [comment]
Hi @fgregg,

Using the most recent version of Dedupe, I am still unable to save result of indexAll using writeSettings when working with gazetteer on large data sets and getting the maximum recursion error. Am I missing something here or is this still the case?

Thank you

**Comment by matthewdchambers** [comment]
Hey @fgregg - experiencing the same here. Any guidance would be sincerely appreciated :)

**Comment by fgregg** [comment]
closed by https://github.com/dedupeio/dedupe/pull/788
