### ISSUE TITLE
Error Pickling Deduper

### ISSUE THREAD

**Issue by rlvoyer** [dedupeio/dedupe#550]
I get the following error when attempting to serialize a Dedupe object. I am using Python 3 (Python 3.6.1 :: Continuum Analytics, Inc.) with the following dedupe dependencies:

dedupe==1.6.9
dedupe-hcluster==0.3.2

```python
In [271]: with open("deduper.pickle", "wb") as outfile:
     ...:     pickle.dump(deduper, outfile)
     ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-271-19193cb30018> in <module>()
      1 with open("deduper.pickle", "wb") as outfile:
----> 2     pickle.dump(deduper, outfile)

AttributeError: Can't pickle local object 'Blocker.__init__.<locals>.<lambda>'
```

**Comment by fgregg** [comment]
sorry, dedupe can't be pickled. Is there a reason why https://dedupe.readthedocs.io/en/latest/API-documentation.html#Dedupe.writeSettings and https://dedupe.readthedocs.io/en/latest/API-documentation.html#StaticDedupe won't work for you?

**Comment by rlvoyer** [comment]
Thanks for the speedy response and this handy library. I am new to the API and just missed that method, but I suspect it will work for my use case. Sorry!
