### ISSUE TITLE
OverflowError when running pgsql_big_dedupe_example on a Windows 64-bit machine

### ISSUE THREAD

**Issue by ofershar** [dedupeio/dedupe#551]
When running the Dedupe example pgsql_big_dedupe_example on a Windows 2008 64-bit machine, an OverflowError is thrown ("Python int too large to convert to C long") when calling deduper.sample .
Python version is 3.4.3 and Dedupe version is 1.6.7 .

Inside the Dedupe code, the exception is thrown from core.py lines 39-40:

    random_pairs = numpy.array(random.sample(range(n), sample_size),
                                   dtype='uint')

It seems the default for 'uint' on the Windows 64-bit machine is 'uint32' , which isn't enough for the random numbers in range(n). There are about 766K rows in the processed_donors table, so 'n' is a 12-digits number:

    n = int(n_records * (n_records - 1) / 2)

Is this a kind of bug in Dedupe, and it should have been written "uint64' rather then just 'uint'?

**Comment by fgregg** [comment]
Thanks for the bug report. Should be fixed by https://github.com/dedupeio/dedupe/commit/493300e0a786fb7226a3ce947d1a52dc348835c6
