### ISSUE TITLE
Dedupe, multiple cores on Ubuntu

### ISSUE THREAD

**Issue by scuerda** [dedupeio/dedupe#574]
I opened an issue under csvdedupe https://github.com/dedupeio/csvdedupe/issues/68 but I think that it might be more fundamental to the installation of dedupe.

I'm not seeing multicore processing when running on an EC2 Ubuntu 16.04 instance. Is there any way that this could be related to the Numpy / Blas issues outlined in https://github.com/dedupeio/dedupe/issues/206 for OSX?

**Comment by fgregg** [comment]
These are the tests that turn off multiprocessing: https://github.com/dedupeio/dedupe/blob/master/dedupe/backport.py#L12-L27

Do any of these pertain to your instance?

**Comment by scuerda** [comment]
Doesn't look like it. Running those leaves MULTIPROCESSING as True

**Comment by fgregg** [comment]
Are you sure that you never use more than one core. Some parts of dedupe are still not parallelized but can take a significant amount of time (particularly blocking and clustering).

btw. both could be parallelized if someone wanted to work on that (hint, hint)

**Comment by scuerda** [comment]
Fair point, I am not sure! My point of reference was running a version of the postgres-backed deduping as part of an earlier step where I saw multiple Python processes being spun up. But I may be conflating different steps!

I spun up a local version of the linking and the process profile looks almost the same. So I think that this is working as expected.

This does raise a related question about performance and what sort of server configurations are ideal for larger jobs (memory, fast disk write, cpu?). But that's a conversation for another day.

Thanks for steering me to the tests.

**Comment by BobFonix** [comment]
Hi @fgregg , I have a related question on multicore processing. This is the best related post I could find as I am not sure if its a bug yet. Is it common for dedupe to drop core utilization mid-way through clustering? 

i am running dedupe v1.9.1 through WSL on py2.7. the dataset is about 2.3mil records.

I recently switched over to the pgsql backend. Python would utilize all cores available, at full capacity, at the start of the clustering step, but mid-way through it would drop 3 cores with the last core reduced to 30% usage. typically at this point mysql would time out and cause the script to fail. i am currently running on pgsql and will monitor the outputs.

Thanks so much!
