### ISSUE TITLE
Using distinct pairs in BlockLearner.learn ?

### ISSUE THREAD

**Issue by Leobouloc** [dedupeio/dedupe#582]
As far as I could tell, `BlockLearner.learn` doesn't take into account the distinct labels provided by the user.   Intuitively, I would assume using predicates that cover less of the non-matches should perform better (for the same number of matches covered).

I counted the number of hits for the final predicates in the distinct labels on multiple runs with the same data. I experienced very variable results (as mentionned [here](https://github.com/dedupeio/dedupe/issues/557)); some of the blocking rules learned had no matches in distinct labels whereas others had hits for up to two thirds of distinct labels. The number of varying parameters makes it hard to make any significant correlation between the number of hits in distinct and performance (recall, precision)...

**Are distincts somehow already included in the choice of predicates, and -if not- is there a reason not to?** 

(also, my understanding is that the final predicates are used as a "union" rather than "intersection"; is that correct?)

```
# Run 1
Predicate (SimplePredicate: (sortedAcronym, localite_acheminement_uai), SimplePredicate: (suffixArray, full_name)) has 0/30 hits in distinct pairs
Predicate (TfidfNGramSearchPredicate: (0.6, full_name), TfidfTextSearchPredicate: (0.6, localite_acheminement_uai)) has 0/30 hits in distinct pairs
Predicate (SimplePredicate: (sameThreeCharStartPredicate, departement), TfidfTextSearchPredicate: (0.4, full_name)) has 5/30 hits in distinct pairs
Predicate (SimplePredicate: (commonTwoTokens, localite_acheminement_uai), TfidfTextSearchPredicate: (0.4, localite_acheminement_uai)) has 9/30 hits in distinct pairs

# Run 2
Predicate (LevenshteinSearchPredicate: (1, departement), SimplePredicate: (suffixArray, full_name)) has 0/30 hits in distinct pairs
indexing

# Run 3
Predicate (SimplePredicate: (tokenFieldPredicate, localite_acheminement_uai), TfidfTextSearchPredicate: (0.6, full_name)) has 0/30 hits in distinct pairs
Predicate (SimplePredicate: (suffixArray, localite_acheminement_uai), TfidfTextSearchPredicate: (0.4, full_name)) has 11/30 hits in distinct pairs
Predicate (SimplePredicate: (commonSixGram, localite_acheminement_uai), TfidfNGramSearchPredicate: (0.6, full_name)) has 0/30 hits in distinct pairs
Predicate (SimplePredicate: (commonTwoTokens, localite_acheminement_uai), TfidfNGramSearchPredicate: (0.4, full_name)) has 1/30 hits in distinct pairs

# Run 4
Predicate (TfidfNGramSearchPredicate: (0.6, departement), TfidfTextSearchPredicate: (0.4, full_name)) has 12/30 hits in distinct pairs
indexing
```

**Comment by fgregg** [comment]
For learning blocking, our objective is have blocks that lead to comparisons of "all true duplicates while minimizing **total** comparisons". This is a slightly different objective than "all true duplicates while minimizing comparisons of **distinct** records. In practice, they will be very similar because the vast bulk of possible comparisons will be of distinct records.

Because we are trying to minimize total comparisons, we can get an pretty accurate estimate of how many comparisons a block predicate will use by taking a random sample of all records and then blocking those. So, that's why we don't use distinct pairs.

I surprised that we are getting this much variability, but we should continue that conversation in #557.

**Comment by deepesch** [comment]
@fgregg _For learning blocking, our objective has blocks that lead to comparisons of "all true duplicates while minimizing total comparisons"_. Based on this, How important is it to have distinct values during active learning? Would using have a large sample of matching pairs would be enough or would it lead to heavier weight to most common features leading to lack of recall? Is it important to have max two pairs of unique_id or it's okay to have multiple records with same unique_id? Thank you :)

**Comment by fgregg** [comment]
having distinct pairs is not at all important for block learning, but it is very important for learning the pair classifier.

**Comment by deepesch** [comment]
when training a supervised classifier, Is it okay to train it on 'randomly selected data points'(distinct) compared to 'data points near decision boundary' like active learning?
