### ISSUE TITLE
match() code missing argument

### ISSUE THREAD

**Issue by calz1** [dedupeio/dedupe#584]
I have a very sparse dataset where only about 5% of the records have true matches. dedupe's precision is great but my recall is suffering because (I think) the average pair are not ending up in the same block. I want to try making the blocks as large as possible, understanding this will slow down the comparisons. 

The docs say you can set the max_components here:

https://dedupe.io/developers/library/en/latest/API-documentation.html#StaticDedupe.match

But line 188 here doesn't have that last argument and when trying to modify the simple CSV example's call to match, I get an error to that effect.

https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py

**Comment by fgregg** [comment]
Yes. we need to fix this in documentation. I'd be really suprised if this is your problem in any case.

**Comment by calz1** [comment]
@fgregg Why do you say that is unlikely to be the problem? I am also trying out searches of the whole corpus with [FuzzyWuzzy](https://github.com/seatgeek/fuzzywuzzy). It is an order of magnitude slower with no blocking, but it is scraping up some matches that dedupe didn't.
