### ISSUE TITLE
OverflowError with numpy.memmap in core.py

### ISSUE THREAD

**Issue by rayrrr** [dedupeio/dedupe#586]
I'm trying to use dedupe core to handle a large dataset (~500k rows). 

I'm seeing a frequent `OverflowError` at this point in the code:

https://github.com/dedupeio/dedupe/blob/v1.6.17/dedupe/core.py#L171

If I wrap that line in a try/except block and pass on the exceptions, it seems to work okay. What exactly is this doing and what could be the source of this bug? 

Seems similar to https://github.com/dedupeio/dedupe/issues/551 but again, not exactly sure what's going on here with this `numpy.memmap` object and why it would be throwing `OverflowError`s in my use case. The `start` and `end` values I am feeding it are all under ten million.

The specific error:
`OverflowError: Python int too large to convert to C long`

**Comment by fgregg** [comment]
Are you on a 32 bit or 64 bit operating system?

**Comment by rayrrr** [comment]
@fgregg I'm on a 64bit Mac OS system, but I'm also using Docker, using a container based on this [Python 3.5/Debian Jessie](https://github.com/docker-library/python/blob/88ba87d31a3033d4dbefecf44ce25aa1b69ab3e5/3.5/Dockerfile) image. Any help from you would be greatly appreciated! I updated the description with the specific error message too.

**Comment by fgregg** [comment]
How large is a C long within that container?

**Comment by rayrrr** [comment]
Here's the info about C longs within the container...it looks as though they are 64 bit, same as llongs, as expected.

```
LONG_MIN   = -9223372036854775808
LONG_MAX   = +9223372036854775807
ULONG_MAX  = 18446744073709551615
```

Furthermore I can tell you that this is happening at the end of the blocking process. Check out the relevant logging and error info (on a test batch with 100k rows):

logging:
```
INFO:dedupe.blocking:10000, 6.9581962 seconds
INFO:dedupe.blocking:20000, 13.5522822 seconds
INFO:dedupe.blocking:30000, 18.3748372 seconds
INFO:dedupe.blocking:40000, 22.6627752 seconds
INFO:dedupe.blocking:50000, 26.7890912 seconds
INFO:dedupe.blocking:60000, 30.5479332 seconds
INFO:dedupe.blocking:70000, 34.0439852 seconds
INFO:dedupe.blocking:80000, 37.4283712 seconds
INFO:dedupe.blocking:90000, 40.7444752 seconds
```

error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/dedupe/core.py", line 171, in mergeScores
  fp[start:end] = score_chunk
OverflowError: Python int too large to convert to C long
```

**Comment by fgregg** [comment]
Hmm... I don't know. I've seen that file regularly get into the hundreds of millions of rows long. Please provide a minimal reproducible example.

**Comment by rayrrr** [comment]
@fgregg not sure I can provide that quickly. I dug in a bit more and it looks like `start` and `end` are actually getting larger than a 64bit can hold. I'd like to figure out why and potentially post a PR myself. Can you provide a little insight into what's happening at that point in the dedupe core code?

**Comment by rayrrr** [comment]
@fgregg the issue here wasn't the number of rows, it was that I was using primary IDs that were larger than the C long limit. I can constrain those primary IDs to that limit, so closing this out. Thanks for your help.
