### ISSUE TITLE
Issue #578 (RecordLink.blocker and Gazetteer.blocker create a huge number of blocks) is not fixed in version 1.7.0

### ISSUE THREAD

**Issue by ofershar** [dedupeio/dedupe#587]
I've installed version 1.7.0 of Dedupe and re-ran the test code for issue #578 (see link in that issue's description).
The number of blocks created by RecordLink.blocker is still huge. In fact, it seems to be even larger than before. I stopped the run when the CSV  file containing the blocks reached a size of 10G.

I use Python 3.5.3 and RHEL 6.5 (but that's probably irrelevant to the problem).

**Comment by fgregg** [comment]
You need to to use the `target=True` argument for blocking your target dataset. Then you'll need to reproduce the logic of `_blockGenerator` with your db https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L398-L420

**Comment by fgregg** [comment]
This will be resolved when we have a big record link example https://github.com/dedupeio/dedupe-examples/issues/23

**Comment by ofershar** [comment]
Hi Forest,

Thanks for your reply (and for sending it so quickly).

I just wanted to make sure I understand correctly what you meant. So here is how I figured it out:

Using the Gazetteer class, I first need to block my target dataset with target=True argument. (I already tested it, and it seems to be working fine).

Then, I need to block my "messy" dataset with target=False. But calling it "as is" would still produce a huge number of blocks (as reported in issue #578).
For preventing this from happening, I need to create a derived class of Gazetteer, similar to DatabaseGazetteer in https://github.com/dedupeio/address-matching/blob/sqlclass/address_matching.py  ,
 with my own implementation of _blockRecords that would access my DB (similar to the code of _blockData in the above link). This should make the blocking work properly even with target=False.

Is that right?
Or maybe I should be using the same instance of Gazetteer / DatabaseGazetteer for blocking both the target and the messy data? If that is the case, wouldn’t the overridden implementation
 of _blockRecords tamper with the proper blocking of the target dataset?

Thanks,
Ofer

**Comment by fgregg** [comment]
> Then, I need to block my "messy" dataset with target=False. But calling it "as is" would still produce a huge number of blocks (as reported in issue #578).

This is right, but you don't need to store the blocks in your database or anywhere else. As soon as you generate a block key for a messy record you can see if it matches any, stored block key of your target record. That's what's going on in that method I linked to. You don't have to subclass the dedupe class (though you can), but you do need that type of logic.
