### ISSUE TITLE
Gazetteer example has a poor recall rate (under 28%)

### ISSUE THREAD

**Issue by ofershar** [dedupeio/dedupe#588]
I get a poor recall rate when running a Gazetteer example which I've created based on pgsql_big_dedupe_example.
The code for reproducing the problem is attached. Please see the "instructions.txt" file for instructions.

     https://github.com/dedupeio/dedupe/files/1134932/Gazetteer.Problem.zip 

The code actually uses the results of pgsql_big_dedupe_example. For every cluster returned by Dedupe.MatchBlocks (having more than one record), one donor is selected for the "gazetteer" while the other donors are used as "messy data". It means that for each "messy" donor, there should be a match in the gazetteer which was already  identified by Dedupe as the same donor (when pgsql_big_dedupe_example was run).
Under these circumstances, I would expect this Gazetteer example to have a very high recall (and also precision). But while the precision is indeed high, the recall is very poor.

The "instructions.txt" file also contains instructions for checking the results to calculate the recall ratio, 
 which is under 28%.

I use Dedupe version 1.7.0, with Python 3.5.3.

The recall argument for Gazetteer.train is 0.9 .
The threshold for Gazetteer.matchBlocks is 0.5 .

Notes:

	1. Because of issue #578 (which wasn't fixed yet in 1.7.0 - see issue #587), the blocks are created 
              using StaticDedupe.blocker rather than Gazetteer.blocker. 

	2. The file gazetteer_problem_settings is included in the set of files. But if deleted, the example code
	    would re-create it.

	3. The file dedupe_example_settings is also included, for creating the StaticDedupe instace.
	   If deleted, the example code would NOT run. However, it may be re-created by running 
             pgsql_big_dedupe_example using the same training JSON file: gazeteer_problem_training.json .

**Comment by fgregg** [comment]
You are using a blocking logic meant for duplicates for gazetteer class. I expect that will lead to poor results. I gave you some direction towards what you need to do in #587. Sorry, I don't have time to write out a full example.
