### ISSUE TITLE
ValueError: No predicate found!  Maybe give Dedupe more training data or increasing the `max_comparisons` argument to the train method

### ISSUE THREAD

**Issue by prakhar21** [dedupeio/dedupe#598]
Please, tell where to specify `max_comparisons`. I am trying dedupe on 1 million records.

i am getting ValueError: No predicate found! We could not learn a single good predicate. Maybe give Dedupe more training data or increasing the `max_comparisons` argument to the train method

**Comment by fgregg** [comment]
Looks like you have an out-of-date version of dedupe. `max_comparisons` is deprecated. Please upgrade.
