### ISSUE TITLE
Which dataset to treat as target in RecordLink?

### ISSUE THREAD

**Issue by potash** [dedupeio/dedupe#602]
The documentation for RecordLink.blocker() states:

> When doing linking you’ll want to treat one of your two data source as a “target”

How do I decide which of the two datasets to treat as the target and are there consequences? Does it affect speed? Matches?

**Comment by fgregg** [comment]
https://dedupe.io/developers/library/en/latest/API-documentation.html#Dedupe.blocker

Please let me know if this explains the issue.

**Comment by potash** [comment]
Thanks, this answers my question.
