### ISSUE TITLE
Locked file when trying to remove temp memmap file on Windows

### ISSUE THREAD

**Issue by chancyk** [dedupeio/dedupe#604]
The `os.remove` following the `del matches` in [matchBlocks](https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L125) fails with a PermissionError, I presume due to the file still being locked by `numpy.memmap`.

I tried forcing a `gc.collect()`, forcing a `time.sleep(0.5)`, and also `del fp` on the memmap reference in  [mergeScores](https://github.com/dedupeio/dedupe/blob/master/dedupe/core.py#L190) to no avail. I'm not sure what the solution is.

I ended up just wrapping the `os.remove()` in a try block, which works for now.

Windows 10 64-bit
Python 3.6 64-bit

**Comment by fgregg** [comment]
Can you paste the whole traceback?

**Comment by chancyk** [comment]
Here's the traceback:
```
  File "C:\Users\chancy\sync\rc_projects\rc_code\cdb\dedupe_owners\dedupe_api.py", line 862, in run_ongoing_dedupe
    matched_dupes = linker.match(new_owners)
  File "C:\venv\rc_code_py36\lib\site-packages\dedupe\api.py", line 952, in match
    return self.matchBlocks(blocked_pairs, threshold, n_matches)
  File "C:\venv\rc_code_py36\lib\site-packages\dedupe\api.py", line 126, in matchBlocks
    os.remove(match_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\User
s\\chancy\\AppData\\Local\\Temp\\tmpq8xfiq8z'
```

**Comment by fgregg** [comment]
Hmm........ super weird. Can you try to see if there are any referers to the match object https://docs.python.org/3/library/gc.html#gc.get_referrers

**Comment by fgregg** [comment]
no more response on this, so closing for now.
