### ISSUE TITLE
Validity of the sampling method on files with large numbers of entities ?

### ISSUE THREAD

**Issue by Leobouloc** [dedupeio/dedupe#605]
From my understanding, to provide pairs to label, dedupe choses among a subset of 5000 pairs which were generated so as to uniformly cover all simple (one field) predicates. If working on a large file with a large number of distinct entities, I would suspect that choosing these pairs simply by randomly picking records with a simple predicate in common might yield a very small number of actual matches (if any) in the sample to label, since the probability of having two distinct entities with a predicate in common becomes larger...

I am missing something? I this issue already dealt with somehow in the code? If not, do you have an intuition on how to fix this (I would suspect increasing sample size or blocking on multiple fields could become necessary as the number of distinct entities grows...) ?

**Comment by fgregg** [comment]
What you are describing is absolutely possible. We haven't seen this in practice yet, though. How big are the datasets you are talking about?

**Comment by Leobouloc** [comment]
This is a theoretical question as I haven't it tried out yet, but I would for example want to match companies with a reference database of 10M companies.

**Comment by fgregg** [comment]
I don't think you will have problems at that scale.

**Comment by fgregg** [comment]
I'm going to close this since it hasn't come up in a real case. Feel free to reopen if you see this behaviour.
