### ISSUE TITLE
Any way to calculate or estimate number of blocks before/while writing them?

### ISSUE THREAD

**Issue by ropeladder** [dedupeio/dedupe#615]
Thanks very much for all your work on the library!

I'm running dedupe on a large (2.6M) set of records and it's taking a while. Is there any way to see in advance how many blocks will be generated in the block writing step? (or get an estimate?) In some of my initial runs it was going up to 350k, the last one it got up to 1.5M.

Also do you have any suggestions for speeding it up? I'm basically following the MySQL example (but using Postgres) and my fields look like the following:

    {'field' : 'fullname', 'type': 'Name'},
    {'field' : 'initials', 'type': 'Custom', 'comparator': mutual_subsumes},
    # initials is a field extracted from the 'fullname' field, mutual_subsumes is a custom function to
    # check whether both sets of initials contain initials that are not in the other set (e.g. 'a,b,c' and 
    # 'a,b,d' fails but 'a,b,c' and 'a,b' passes)
    {'field' : 'givenname', 'type': 'String', 'has missing' : True}, # the rest of the fields are frequently null
    {'field' : 'familyname', 'type': 'String', 'has missing' : True},
    {'field' : 'ispartof', 'type': 'String', 'has missing' : True},
    {'field' : 'handle', 'type': 'String', 'has missing' : True},
    {'field' : 'phone', 'type': 'Exact', 'has missing' : True},
    {'field' : 'email', 'variable name': 'email', 'type': 'Exact', 'has missing' : True}

**Comment by fgregg** [comment]
You could randomize the order that you block the data, block 100 records, count how blocks you created and generalize to the rest of the data.

I'd consider following the posgres reciped for speed.
