### ISSUE TITLE
Unclickable links in rtd theme

### ISSUE THREAD

**Issue by whalebot-helmsman** [dedupeio/dedupe#616]
Links in documentation from last line before header are unclickable. E.g. https://dedupe.io/developers/library/en/latest/Variable-definition.html - affine gap distance link is unclickable, cosine similarity metric is ok,  Haversine Formula is ok, but dedupe-variable-fuzzycategory is unclickable again.

**Comment by fgregg** [comment]
@jeancochrane can you take a look at this.
