### ISSUE TITLE
Dudupe on Large Dataset

### ISSUE THREAD

**Issue by prakhar21** [dedupeio/dedupe#618]
I am trying to run deduplication on a csv file having 6 million records with 4 columns (considering for deduplication) and 1 (uuid). I am using **csv_example.py** as the main code.

Machine configuration is as follows:
1. RAM: 121GB
2. Cores: 16
3. Processor: i7

After the job runs for 5 hours the code starts to behave weirdly and shows 
![error](https://user-images.githubusercontent.com/6958949/31875834-6a8a11c6-b7bf-11e7-9ead-353cd6f376ce.png)

**Comment by fgregg** [comment]
For big datasets, we recommend using a database: https://github.com/dedupeio/dedupe-examples#postgresql-big-dedupe-example---postgresql-example-on-large-dataset
