### ISSUE TITLE
mysql_example error UnicodeEncodeError

### ISSUE THREAD

**Issue by sarthakchakravarty** [dedupeio/dedupe#619]
I am facing an issue while running mysql_example.py on campaign dataset.
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)
Python version: 2.7.12
![screenshot-2017-10-24 screenshot from 2017-10-24 13-48-59 png png image 1366 x 768 pixels - scaled 87](https://user-images.githubusercontent.com/31059970/31980544-d842614e-b96a-11e7-801d-d8c718bd35de.png)

**Comment by fgregg** [comment]
I saw the issue you opened on dedupe-examples, thank you.
