### ISSUE TITLE
n_matches not defined when using linker.match()

### ISSUE THREAD

**Issue by jimmysteinmetz** [dedupeio/dedupe#621]
Modified example [here](https://dedupeio.github.io/dedupe-examples/docs/record_linkage_example.html), got the following error back

    Traceback (most recent call last):
    File "test.py", line 221, in <module>
    linked_records = linker.match(pm_valid, temp_d, 0)
    File "/Applications/anaconda2/lib/python2.7/site-packages/dedupe/api.py", line 361, in match
    clusters = self.matchBlocks(blocked_pairs, threshold, n_matches)
    NameError: global name 'n_matches' is not defined`

**Comment by fgregg** [comment]
Thanks for the report! I should have this sorted within a few days.
