### ISSUE TITLE
dedupe

### ISSUE THREAD

**Issue by hskal** [dedupeio/dedupe#624]
I installed dedupe on windows platform using the command "pip install dedupe". The installation finishes and it shows the message "Successfully installed dedupe-1.8.1". But when I try importing dedupe it displays an error  "No module named 'zope.index' " . Can anyone tell me what it means and how to circumvent it ? 

I am using python 3.6.

**Comment by talikarng** [comment]
That error message means that you haven't got 'zope.index' installed. Whenever it happens to me, I usually find that I forgot to install something that another module or library requires.

You can install it the same way you installed dedupe:
"pip install zope.index"

**Comment by talikarng** [comment]
Just as a 'heads up': It it easier for people to get a sense of what is being asked (and they are more likely to read the thread) if the title is more descriptive. E.g. "No module named 'zope.index' "

**Comment by fgregg** [comment]
what version of pip did you have?
