### ISSUE TITLE
** Question ** Adding new data

### ISSUE THREAD

**Issue by espray** [dedupeio/dedupe#625]
I ran dedup over my data. No problems.

Now I want to add more data to the set, naturally I want to avoid adding a duplicate. :) What are my options?
*Do I need to re dedup the entire set again?
*Can the FScore be calculated on the new data to find a possible categories, if none found create a new one?

**Comment by espray** [comment]
I was reading more on dedupe.io
I can figure out what batch the new entity would be in and run dedupe on just that batch.
Is that correct?

**Comment by akkaneko** [comment]
I'm also curious about this. For record linking, could I just leave the target file blocked and add it in somehow?

**Comment by fgregg** [comment]
you can use the gazette class
