### ISSUE TITLE
Alternate api for console label function

### ISSUE THREAD

**Issue by ashokpv** [dedupeio/dedupe#626]
Is there any other method rather than  consolelabel() for labelling yes,  no ,  finished.  Because I have to show the questions in the UI ,  so would like to know another way for displaying them in the UI

**Comment by fgregg** [comment]
We do not provide any other method, but we wrote [`uncertainPairs`](https://dedupe.io/developers/library/en/latest/API-documentation.html#Dedupe.uncertainPairs) and [`markPairs`](https://dedupe.io/developers/library/en/latest/API-documentation.html#Dedupe.markPairs) to make it easier to write your own interface.
