### ISSUE TITLE
Dedupe training on Spyder

### ISSUE THREAD

**Issue by JoanaSalvado** [dedupeio/dedupe#627]
Dedupe slams with Spyder when asking for user input (the active labeling phase).
I understand the issue is about the input - raw_input changes from Python 2.7 to Python 3, but I haven't managed to solve the issue (I'm using Idle to train and Spyder to do the rest).

Do you have some suggestions?

**Comment by fgregg** [comment]
I have no idea what spyder is, so sorry.
