### ISSUE TITLE
Setting a maximum number of items per cluster

### ISSUE THREAD

**Issue by mikhuang** [dedupeio/dedupe#636]
Hi! I've been having a great time with Dedupe, it's been very valuable. I've found that sometimes certain entries will be clumped into sets with a dozen items. However, I know that in my dataset, the max number of collisions is less than half that. Is there any way to change dedupe behavior to take that into account?

**Comment by fgregg** [comment]
This is not something that we would include in the core library, but you could process the results of `core.ScoreDuplicates` yourself to get something like this.
