### ISSUE TITLE
local variable 'dtype' referenced before assignment

### ISSUE THREAD

**Issue by nsckir** [dedupeio/dedupe#641]
Else clause always crashed because `dtype` is not defined
```
    if result :
        scored_pairs_file, dtype, size = result
        scored_pairs = numpy.memmap(scored_pairs_file,
                                    dtype=dtype,
                                    shape=(size,))
    else:

        scored_pairs = numpy.array([], dtype=dtype)
```

https://github.com/dedupeio/dedupe/blob/46572ed1677254811f5c71c7eecd352cf3d7510b/dedupe/core.py#L241

**Comment by fgregg** [comment]
closed by https://github.com/dedupeio/dedupe/commit/422f8655bc8b03828931ee8f40def023efac3578
