### ISSUE TITLE
Docs website wonky again

### ISSUE THREAD

**Issue by janstice** [dedupeio/dedupe#644]
Hi - the docs website is wonky again - was working last week but not this week, I'm seeing a 404 on 
https://dedupe.io/developers/library/en/latest/

cheers

**Comment by jeancochrane** [comment]
Hey @janstice! We're still working on this in #637, no changes have been made since then. While we're debugging, you can view the docs on the readthedocs domain at https://dedupe.readthedocs.io/en/latest/.
