### ISSUE TITLE
Hard-coded numbers in labeler.py

### ISSUE THREAD

**Issue by daoli** [dedupeio/dedupe#649]
Hello,

When reading the source code, I encountered some hard-coded numbers when calling `Sample` in `labeler.py`. What are the purposes for the numbers 2000 and 600?

https://github.com/dedupeio/dedupe/blob/52e5d568a3472670c987fed3043806ba8ce18972/dedupe/labeler.py#L309

https://github.com/dedupeio/dedupe/blob/52e5d568a3472670c987fed3043806ba8ce18972/dedupe/labeler.py#L331

https://github.com/dedupeio/dedupe/blob/52e5d568a3472670c987fed3043806ba8ce18972/dedupe/labeler.py#L332

**Comment by fgregg** [comment]
Those numbers work pretty well, practically.

**Comment by daoli** [comment]
Seems _magical_... Pointers available? Thanks.
