### ISSUE TITLE
Dedupe does not currently support multiprocessing on Windows

### ISSUE THREAD

**Issue by Genussradler** [dedupeio/dedupe#653]
Hi,

more a question than an issue:
I try to use dedupe within Sql Server 2017 via sp_execute_external_script, which supports Python scripts.
Up to now I have successfully ininitalizes a dedupe object, made a sample and fetched some uncertainPairs, but the performance is not that good as it could be.
Is there a chance that dedupe will support multiprocessing on Windows someday?
Or could you explain me why it is not supported?

Greetings
  Marco

**Comment by fgregg** [comment]
We would welcome a PR that added multiprocessing to windows. It would be a big change because the model of multiprocessing is very different for linux and windows.
