### ISSUE TITLE
AttributeError: Attempting to block with an index predicate without indexing records

### ISSUE THREAD

**Issue by cypherxtreme** [dedupeio/dedupe#655]
Throws this error while calling deduper.markPairs. Not sure what this means and how to fix it.

**Comment by krish240574** [comment]
I have the same problem when running address_matching.py - using python 3.6 Anaconda. Not sure what it means either.

**Comment by fgregg** [comment]
You have to index the records before using an index predicate. https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.blocker.index

**Comment by ThomasProctor** [comment]
Just fyi for those who have encountered this error, it seems to me that this error is thrown if you pass data to a linker or gazetteer where there are overlapping indices in the two data sets.

There should probably be a more understandable error if you do this.

**Comment by NataliaNovosad** [comment]
@vshlpunjabi Did you managed to solve the problem? 
https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.blocker.index - this does not actually help me, because deduper.blocker object is NoneType and I can not get to deduper.blocker.index_fields. Did it help you?

**Comment by EfremBraun** [comment]
I encountered this problem as well, and I figured it out, so here's my use-case in the hopes that it helps someone else:

See csv_example.py file to follow-along with variable names:

I trained a Dedupe object on a small subset of my total data, found that it worked, and then wanted to re-train a new Dedupe object on my full data set. I didn't want to have to go through the active learning process again to re-generate a new training file, so I removed the settings file from my directory but I kept the training file. While within deduper.readTraining(f), I got thrown the same error as @vshlpunjabi. After some debugging, I found that the problem had to do with the line "deduper.sample(data_d, 15000)". Apparently, when I went to the larger dataset, the 15000 sample didn't include all of the rows that were in the training file that had been generated with the smaller dataset. This means that those rows weren't indexed, which throws the error. The issue can be solved by either increasing the sample number to the size of the full dataset to ensure that all original rows are included in the sample (which makes the program runtime slower) or by generating a new training file (which takes user time).

@fgregg: A feature request would be to allow the deduper.sample() method to ensure that rows included in previous training runs are included in the sample it returns. I think it's quite common for users to tinker with a smaller data set before going up to a larger one.

**Comment by Fliktrax** [comment]
"/.local/lib/python2.7/site-packages/dedupe/predicates.py", line 149, in __call__
    raise AttributeError("Attempting to block with an index "
AttributeError: Attempting to block with an index predicate without indexing records
"

It really makes no sense to me to have to retrain before every dedupe run. I was pretty excited about this project but it seems the ball was dropped at the goal line here.
