### ISSUE TITLE
Recursive Training

### ISSUE THREAD

**Issue by harshalraj08** [dedupeio/dedupe#657]
We are trying to use active labeling recursively. Reading from existing training file and after active labeling-rewriting  training which will now have old + new training set. Overwriting settings file each time for whole set of training again.

Program is getting into hang at threshold function after 2-3 training. Please help if this approach is suitable and any help on why its getting hang?

**Comment by fgregg** [comment]
If you are truly rewriting the training data and rewrite the settings file, you should have no issues. 

Please provide a short code example that reproduces this problem, and re-open,
