### ISSUE TITLE
Issue while clustering datasets

### ISSUE THREAD

**Issue by vinodtycoon123** [dedupeio/dedupe#659]
While clustering the datasets. I'm facing the issue:
'Error in catch ', "invalid literal for int() with base 10: ''"

Can someone help me?

**Comment by fgregg** [comment]
This is not enough information to resolve your issue. Please follow this [guidance for reporting issues]( https://github.com/dedupeio/dedupe/blob/master/CONTRIBUTING.md), and re-open with adequate information.
