### ISSUE TITLE
calling match on anything not equal to original training data doesnt work?

### ISSUE THREAD

**Issue by kevinfaust0308** [dedupeio/dedupe#664]
seems that i can only call match on the exact same data that was passed for training. i took the training data and created a dictionary of 2 keys and even that doesnt work (simulating trying to compare similarity of two rows). i thought that due to machine learning it should be able to generalize to other data with the same attributes

**Comment by fgregg** [comment]
What do you mean by "dictionary of 2 keys"?

The hard problem in record linkage is not comparing two records, but avoiding comparing every possible pair of two records. dedupe tries to learn how to avoid comparing records that will not be co-referent, and this means that it will learn settings that will not generalize well to data that's not like the data it was trained on. 

You can always add more training data so dedupe will learn blocking rules that work with newer, different data.

**Comment by kevinfaust0308** [comment]
sorry i shouldve been more clear. 

lets say data_d is the data dictionary we train our deduper on. i create this smaller dictionary: small_d ={ 0 : data_d[0], 1 : data_d[1] } and attempt to call deduper.match(small_d, threshold) but this doesn't work. my debugger hangs for a while and then the debugger pretty much becomes non-functional and have to restart the program. Thats the main problem im facing. It looks like the matcher wont work on any data other than what it was trained on.

For "continuing" training, I am slightly confused by whats in csv_example.py. So in effect, we are training using our old labeled + new labeled (since we load the training file which contains all labeled data thus far).

**Comment by fgregg** [comment]
What happens when you call "deduper.match"?

**Comment by kevinfaust0308** [comment]
strange. returned back to my computer and the above problem i had works now. just is unable to work on new data which i understand is expected
