### ISSUE TITLE
Save/restore training data

### ISSUE THREAD

**Issue by sarink** [dedupeio/dedupe#679]
Hey guys, first off, thanks for this awesome library!

Question: Is there a way to save training data and come back to it to train more later on? Assuming the data remains unchanged.

Thanks!

**Comment by fgregg** [comment]
Yup! Use the readTraining method. https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.readTraining

**Comment by sarink** [comment]
@fgregg how does `readTraining` allow you to append more training data?

**Comment by fgregg** [comment]
read the training in,

add more training using the normal methods

write training out and it will have the training you read plus the training
you added.
