### ISSUE TITLE
Why is the threshold parameter set to 0 when method scoreDuplicates is called from matchBlocks method in class Matching?

### ISSUE THREAD

**Issue by emrsn-danbozdog** [dedupeio/dedupe#693]
In method matchBlocks from class Matching in file api.py why is the threshold set to 0 when scoreDuplicates method is called?

https://github.com/dedupeio/dedupe/blob/e2a8ec851e177fbbaeb1c5c8837d095d28d8060a/dedupe/api.py#L118

**Comment by fgregg** [comment]
after we compare pairs, we use hierarchical agglomerative clustering to turn find clusters of records that are all co-referent. The clustering algorithm uses the pairwise scores to calculate "cluster scores" If we didn't pass these through, the clustering algorithm would have worse performance (lower recall, in particular).
