### ISSUE TITLE
Unable to match multiple records in messy data using gazetteer

### ISSUE THREAD

**Issue by Nitin-Asthana** [dedupeio/dedupe#696]
We have multiple records in messy data(multiple sets of duplicate records) and a corresponding canonical set. When we execute gazetteer process, output file has only 1 record mapping to canonical record. Rest of duplicates from set are not mapped to canonical and marked/clustered as separate.

Kindly help if this is as expected in gazetteer or if I am missing something?

**Comment by fgregg** [comment]
It's certainly possible.
