### ISSUE TITLE
Gazetteer Object totally ignores smaller_ids information, doing more comparisons than needed

### ISSUE THREAD

**Issue by pedrolauro** [dedupeio/dedupe#700]
https://github.com/dedupeio/dedupe/blob/65252112844f9951c33a67bcc10a20a6617b160e/dedupe/core.py#L316

Why are the smaller_ids information (on this line, the third parameter of the tuples) simply ignored for the gazetteer comparator? This is forcing a lot more comparisons than necessary, making this a very slow option when using this framework.

https://github.com/dedupeio/dedupe/blob/65252112844f9951c33a67bcc10a20a6617b160e/dedupe/core.py#L133

Take the dedupe algorithm, for example. Here it uses the smaller_ids var to garantee that this pair haven't been compared in a previous block. 

Why not do the same for GazetteScore?

**Comment by fgregg** [comment]
Because we already take a step to make sure that there are not redundant pairs https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L418-L439

**Comment by fgregg** [comment]
Woops here's the linkg https://github.com/dedupeio/dedupe-geocoder/blob/085f06995010f0635f8bf4515565bc0841b18913/geocoder/deduper.py#L137-L193

**Comment by pedrolauro** [comment]
I see you closed the issue, @fgregg, and you won't even discuss my argument. 

You should at least update your documentation, then. 
There's **2 definitions** for matchBlocks function on StaticGazetteer section. Both determine that you have to send information about blocks that cover that comparison. **Why then**, if I have to do it manually before calling that function?

**Comment by fgregg** [comment]
I'm sorry, I didn't know that you were making an argument, I thought you were asking a question about the code. 

The reasons the code is like this if you are doing gazeteer or record linkage there are much more efficient ways of removing redundant comparisons than the `smaller_ids` scheme. I provided a link for one such way.

Definitely would be good to update the documentation, and I'd welcome a PR.
