### ISSUE TITLE
'NoneType' object has no attribute 'indexAll'

### ISSUE THREAD

**Issue by sahilocean** [dedupeio/dedupe#702]

**Comment by fgregg** [comment]
Thanks for the report, but this does not provide enough information for me understand what went wrong. Could you please past a traceback. Thanks!

**Comment by adriennefranke** [comment]
I just got this error and thought it might be helpful to post the traceback:

AttributeError                            Traceback (most recent call last)
<ipython-input-96-fc032796c0a2> in <module>
     52         gazetteer.writeTraining(tf)
     53 
---> 54     gazetteer.index(temp_canonical_d)
     55 
     56     with open(settings_file, 'wb') as sf:

~/.conda/envs/dev2/lib/python3.7/site-packages/dedupe/api.py in index(self, data)
    873     def index(self, data):  # pragma: no cover
    874 
--> 875         self.blocker.indexAll(data)
    876 
    877         for block_key, record_id in self.blocker(data.items(), target=True):

AttributeError: 'NoneType' object has no attribute 'indexAll'

**Comment by adriennefranke** [comment]
I forgot to include gazetteer.train() before writing the training file and indexing it. Including this resolved this issue.
