### ISSUE TITLE
Dedupe crashes while running on large data sets

### ISSUE THREAD

**Issue by abhaynaik77** [dedupeio/dedupe#704]
Hello,

We are using dedupe for checking duplicate data in our customer base. The duplicate check works fine upto 0.2 million records. But dedupe crashes when the dataset is larger than 0.2 million records. 

An urgent help in solving this issue will be greatly appreciated!

Thanks in anticipation!
Regards,

**Comment by fgregg** [comment]
Please past the traceback. Thank you.

**Comment by abhaynaik77** [comment]
We are extremely sorry for replying so late! 

We have attached the TraceBack for your reference. Can you please help us here as the issue still persists?

Thanks a lot.
[DedupeTraceback.txt](https://github.com/dedupeio/dedupe/files/2537400/DedupeTraceback.txt)

**Comment by fgregg** [comment]
the traceback doesn't give enough information to know for sure, but it looks like you are doing everythign in memory. use  database like https://dedupeio.github.io/dedupe-examples/docs/pgsql_big_dedupe_example.html
