### ISSUE TITLE
gazetteer.match not returning matches for all inputs when threshold=0 (or really small number)

### ISSUE THREAD

**Issue by ChaseWeber** [dedupeio/dedupe#706]
I know for certain that an input should match an item in the canonical set; however after I trained my data, the gazetteer.match is not returning every unique_id from the input set with a match. For example in the below case, csv5 (unique id = 6), is missing.

>  'input_messy.csv5': {
    'unique_id': '6',

`**results = gazetteer.match(messy, threshold=0, n_matches=1, generator=False)**`

`dtype=[('pairs', '<U256', (2,)), ('score', '<f4')]), array([(['input_messy.csv4', 'input_cononical.csv59'], 0.65260684)],
      dtype=[('pairs', '<U256', (2,)), ('score', '<f4')]), array([(['input_messy.csv6', 'input_cononical.csv137'], 0.66865766)],
      dtype=[('pairs', '<U256', (2,)), ('score', '<f4')]), array([(['input_messy.csv7', 'input_cononical.csv140'], 0.64622027)],
      dtype=[('pairs', '<U256', (2,)), ('score', '<f4')]), array([(['input_messy.csv8', 'input_cononical.csv53'], 0.4620853)],
      dtype=[('pairs', '<U256', (2,)), ('score', '<f4')]), array([(['input_messy.csv9', 'input_cononical.csv50'], 0.5379542)],
      dtype=[('pairs', '<U256', (2,)), ('score', '<f4')]), array([(['input_messy.csv10', 'input_cononical.csv50'], 0.537954`

My issue is that I always want to return a match (hopefully the best). Am I missing something?

**Comment by ChaseWeber** [comment]
No luck in filtering through the Python. Does anyone have an idea why some of my inputs result in the No records to match? I tried searching for character differences between the matches without luck.

**Comment by ChaseWeber** [comment]
I may be running into the same issue with the gazetteer example. When setting the threshold to 0, some messy inputs do not result in a match.

**Comment by fgregg** [comment]
This is almost certainly due to having learned blocking rules that are too restrictive. Add some training data for the examples that you know should match and retrain.

**Comment by ChaseWeber** [comment]
Is there any way to remove or ignore if exception is thrown for the restrictive blocking rules? I need to make sure that there is always at least 1 match returned even if the confidence score is extremely low.

**Comment by fgregg** [comment]
your two options are to either learn blocking rules that work for your data or to not do blocking. the latter would require you to do some surgery on https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L441-L453

Basically, returning the cartesian product of the two recordsets.

**Comment by sluijs** [comment]
I have the same problem, but with the `linker.match` function. 

`linker.match(data_1, data_2, threshold = 0.0)` returns 730 rows instead of the 746 in both `data_1` and `data_2`. I have no blocking rules and I trained using same datasets (just for testing purposes). Any advice @fgregg ?
