### ISSUE TITLE
dedupe error module 'dedupe' has no attribute 'Dedupe'

### ISSUE THREAD

**Issue by paresh982** [dedupeio/dedupe#707]
dedupe error module 'dedupe' has no attribute 'Dedupe'

**Comment by abizerjafferjee** [comment]
I'm getting the same error.

**Comment by hancush** [comment]
fwiw, i encountered this error when the script i was running was called `dedupe.py`. renaming the script fixed the problem.

**Comment by sohagiya** [comment]
I am getting same error. I am using python 3.7 IDLE in windows 7 machine

**Comment by fgregg** [comment]
can't reproduce.
