### ISSUE TITLE
tricky on future package issue

### ISSUE THREAD

**Issue by loveJasmine** [dedupeio/dedupe#709]
(.venv) ub16hp@UB16HP:~/ub16_prj/dedupe$ sudo pip3 install future
The directory '/home/ub16hp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ub16hp/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting future
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 478kB/s 
Installing collected packages: future
  Running setup.py install for future ... done
Successfully installed future-0.16.0
(.venv) ub16hp@UB16HP:~/ub16_prj/dedupe$ python3 tests/canonical_matching.py
Traceback (most recent call last):
  File "tests/canonical_matching.py", line 4, in <module>
    from future.utils import viewitems
ImportError: No module named 'future'
(.venv) ub16hp@UB16HP:~/ub16_prj/dedupe$

**Comment by fgregg** [comment]
i'm not sure what this is. please open a new issue with a question.
