### ISSUE TITLE
AttributeError: module 'dedupe' has no attribute 'trainingDataLink'. 

### ISSUE THREAD

**Issue by JordanMicahBennett** [dedupeio/dedupe#713]
After [successfully installing dedupe](https://github.com/dedupeio/dedupe/issues/712), when trying to run [tests/canonical_matching.py](https://github.com/dedupeio/dedupe/blob/master/tests/canonical_matching.py), I get the following error:

AttributeError: module 'dedupe' has no attribute 'trainingDataLink'. 

Any thoughts?

**Comment by fgregg** [comment]
No, sorry. Can't reproduce.

**Comment by suparnotito** [comment]
Same issue for me
