### ISSUE TITLE
reduce execution time for writing blocking map for sqlite_example

### ISSUE THREAD

**Issue by derekeder** [dedupeio/dedupe#72]
Current implementation of writing our blocking map to a sqlite3 table uses the executemany method. This is great for speed, but means that a single object in memory blows up in size as we read in more data. 

<pre>
print 'writing blocking map'
def block_data() :
    full_data = ((row['donor_id'], row) for row in con.execute(donor_select))
    for donor_id, record in full_data :
        if donor_id % 10000 == 0 :
            print donor_id
        for key in blocker((donor_id, record)):
            yield (str(key), donor_id)

con.executemany("INSERT OR IGNORE INTO bm.blocking_map VALUES (?, ?)",
                block_data())

con.commit()
</pre>

This could be fixed by chunking the executemany using itertools.islice, similar to how we do it for scoreDuplicates in core.py:

<pre>
# identify all pairs above a set threshold as duplicates
def scoreDuplicates(candidates,
                    data_model,
                    threshold=None,
                    ):

    score_dtype = [('pairs', 'i4', 2), ('score', 'f4', 1)]
    scored_pairs = numpy.zeros(0, dtype=score_dtype)

    complete = False
    chunk_size = 5000
    i = 1
    while not complete:
      #pdb.set_trace()
      can_slice = list(itertools.islice(candidates, 0, chunk_size))

      
      record_distances = recordDistances(can_slice, data_model)
      duplicate_scores = scorePairs(record_distances, data_model)

      scored_pairs = numpy.append(scored_pairs,
                                  numpy.array(zip(record_distances['pairs'],
                                                  duplicate_scores),
                                              dtype=score_dtype)[duplicate_scores > threshold], 
                                  axis=0)
      i += 1
      if len(record_distances) < chunk_size :
        complete = True
        print "num chunks", i
</pre>

**Comment by fgregg** [comment]
7 years later, sqlite3 is good.
