### ISSUE TITLE
Large labeled pairs, deduper.train problem

### ISSUE THREAD

**Issue by LordAndraXXXus** [dedupeio/dedupe#724]
I have a large file containing "good" and "bad" pairs.
i dumped them in a training file and made dedupe read it with: (it is in a good format)

with codecs.open('large_training.txt', 'rb') as sf:
    deduper.readTraining(sf)

then i wanted to make dedupe to make use of the large confimed pairs and non-pairs woth this:

deduper.train()

but i get a following error massege:

INFO:rlr.crossvalidation:using cross validation to find optimum alpha...
d:\Users\******\Anaconda3\lib\site-packages\rlr\lr.py:39: UserWarning: The line-search routine reaches the maximum number of evaluations.
  case_weights, self.alpha))
INFO:rlr.crossvalidation:optimum alpha: 0.000010, score 0.430615513989
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-ec8232eba94d> in <module>()
----> 1 deduper.train(index_predicates=False)

d:\Users\*****\Anaconda3\lib\site-packages\dedupe\api.py in train(self, recall, index_predicates)
    673         self.classifier.fit(self.data_model.distances(examples), y)
    674 
--> 675         self.predicates = self.active_learner.learn_predicates(
    676             recall, index_predicates)
    677         self.blocker = blocking.Blocker(self.predicates)

AttributeError: 'NoneType' object has no attribute 'learn_predicates'

can this be fixed somehow?

**Comment by fgregg** [comment]
you need to sample the data (https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.sample) before call the train method.
