### ISSUE TITLE
Comparator for set JSON

### ISSUE THREAD

**Issue by jyjyj** [dedupeio/dedupe#725]
Hi, I'm currently going through a dataset that has fields which are JSON with their own fields. What is the best way to compare these, and is it possible to write custom comparators or use the inbuilt comparators for each field in the JSON?

Currently I'm using Set to pick one just one field in the JSON, but am lookingo incorporate all of the available data.

A separate but related question since I'm thinking the answer to the above question will relate to Set - does the Set comparator compare like Text as it says in the docs, meaning it picks out the number of words it has in common? If for example I want to check if 2 companies are the same by comparing their list of clients, and company A has clients X Y Z E F but company B has client X Y, will these be less likely to match together as company B does not have Z E F? If this example is not clear, I'm wondering if this pair is less likely to match vs. a company C with X Y Z and company D with X Y.

Thanks!

**Comment by fgregg** [comment]
Thanks for your interest, @jyjyj. These are questions that would best be asked on stackoverflow.
