### ISSUE TITLE
Error on comparison of empty records

### ISSUE THREAD

**Issue by eadka** [dedupeio/dedupe#729]
Hi, An error of **ZeroDivisionError: float division** occurs when records being compared are empty(''). The error occurs in **datamodel**, within the **distances** function, inside the condition: 

>   if record_1[field] is not None and record_2[field] is not None

`def distances(self, record_pairs):
        `

        num_records = len(record_pairs
        distances = numpy.empty((num_records, len(self)), 'f4')
        field_comparators = self._field_comparators

        for i, (record_1, record_2) in enumerate(record_pairs):

            for field, compare, start, stop in field_comparators:
                if record_1[field] is not None and record_2[field] is not None:
                    distances[i, start:stop] = compare(record_1[field],
                                                       record_2[field])
                elif hasattr(compare, 'missing'):
                    distances[i, start:stop] = compare(record_1[field],
                                                       record_2[field])
                else:
                    distances[i, start:stop] = numpy.nan

        distances = self._derivedDistances(distances)

        return distances`

The following change overcame it: 

> if record_1[field] not in (None, '') and record_2[field] not in (None, ''):

`def distances(self, record_pairs):
        `

        num_records = len(record_pairs
        distances = numpy.empty((num_records, len(self)), 'f4')
        field_comparators = self._field_comparators

        for i, (record_1, record_2) in enumerate(record_pairs):

            for field, compare, start, stop in field_comparators:
                if record_1[field] not in (None, '') and record_2[field] not in (None, '')::
                    distances[i, start:stop] = compare(record_1[field],
                                                       record_2[field])
                elif hasattr(compare, 'missing'):
                    distances[i, start:stop] = compare(record_1[field],
                                                       record_2[field])
                else:
                    distances[i, start:stop] = numpy.nan

        distances = self._derivedDistances(distances)

        return distances`

**Comment by fgregg** [comment]
This behavior is documented. https://docs.dedupe.io/en/latest/Variable-definition.html#missing-data
