### ISSUE TITLE
Cannot Install Dedupe on Mojave with XCode 10

### ISSUE THREAD

**Issue by michael-clarkson** [dedupeio/dedupe#730]
Hi guys, 

When trying to install on MacOS Mojave using pip there is an error when building the wheel for fastcluster:

```
src/fastcluster_python.cpp:55:10: fatal error: 'cmath' file not found
    #include <cmath> // for std::abs, std::pow, std::sqrt
             ^~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
```

It seems fastcluster 1.1.25 installs just fine but dedupe requires <1.1.25.

**Comment by fgregg** [comment]
This should be reported on https://github.com/cran/fastcluster

**Comment by ultrons** [comment]
export CFLAGS='-stdlib=libc++'

**Comment by michael-clarkson** [comment]
Thanks @ultrons. I did a little more looking and I likewise found that apple deprecated the use of libstdc++ a few years ago and finally removed it altogether. So as you say we now need to use libc++.

@fgregg I realise it is a fastcluster issue I just thought you’d like to be aware.

**Comment by GodefroyClair** [comment]
if it doesn't work for you, you can also install the right version of fastcluster (1.1.24) from conda-forge.

**Comment by GuoQuanhao** [comment]
> export CFLAGS='-stdlib=libc++'

nice, it solved all my problems, god bless you
