### ISSUE TITLE
Could deduper.match return cluster records with confidence that is less than the given threshold?

### ISSUE THREAD

**Issue by sokirko74** [dedupeio/dedupe#736]
I take your example dedupe-examples-master/csv_example and create some training examples (10 positive and more than 10 negative). After deduper.match I add a new condition:

for record_id, score in zip(id_set, scores):
  if score < threshold:
      print ("bad score found")

This line is hit if one just start python csv_example.py

**Comment by sokirko74** [comment]
Yes, I checked  https://github.com/dedupeio/dedupe/blob/master/dedupe/clustering.py , There is not checking of  threshold if a component contains only one edge. Please, explain it.

**Comment by fgregg** [comment]
it is a bug that there was not checking of threshold if the component contains only one edge. Just fixed that in 193b5d9d4034bdb6307d9bfc071c7d077dd7f4f0

**Comment by sokirko74** [comment]
I think, you fix  is not correct, because  on line 145 threshold is set to 1 - threshold
