### ISSUE TITLE
Use dedupe in Java

### ISSUE THREAD

**Issue by akhilgupta0221** [dedupeio/dedupe#740]
Hi 

Is it possible to use dedupe in Java project.

Regards
Akhil

**Comment by fgregg** [comment]
there are numerous python - java bridges that might work. For example: https://jpy.readthedocs.io/en/latest/intro.html

Never used one myself.

**Comment by akhilgupta0221** [comment]
Hi 

I have called the script form the Java code.
Is there any way to deal with the training part form Java Based UI application.
Here I want to do Yes or No from the UI instead of command prompt then How can Python script wait for the response from the JAVA based application.

Regards
Akhil
