### ISSUE TITLE
Dedupe returns `# duplicate sets 29` but all clusters contain just one element.

### ISSUE THREAD

**Issue by AlxndrMlk** [dedupeio/dedupe#743]
Hi!

Fisrt of all thanks for a great work with dedupe! :)

Lately I encountered an issue. 

I am deduplicating a csv file using active learning paradigm.

I went thru some trials:

`12/10 positive, 53/10 negative`

Output looks like this:

```
importing data ...                                                               
reading from ./dedupe_params/__il_learned_settings                               
clustering...                                                                    
# duplicate sets 29
```

Then I examine my deduplicated file and it occurs that each cluster contains only one element:
```
>> data['Cluster ID'].value_counts().max()
1
```

This behavior appeared for only one dataset so far.

Any ideas on how to solve it?

Thanks,
Aleksander 

Environment: Win 10, Python 3.6.5

**Comment by fgregg** [comment]
the writing of the data into an object that has a 'Cluster ID' key is not part of the dedupe library. Doesn't seem clear that this is an issue with dedupe.
