### ISSUE TITLE
Dedupe library performance for large dataset(more than 200 million records)

### ISSUE THREAD

**Issue by Sushant20** [dedupeio/dedupe#749]
Team,
Will dedupe library work with more than 200 million records ? Any performance optimization tips?

**Comment by tendres** [comment]
I have been successful with about 60million records using Postgres.
Have not attempted anything larger but in monitoring memory I wouldn’t anticipate it being a problem.
HTH

**Comment by Sushant20** [comment]
Thanks a lot for the reply. How much time did it take for you to process 60 million records?

**Comment by Neelotpaul** [comment]
> I have been successful with about 60million records using Postgres. Have not attempted anything larger but in monitoring memory I wouldn’t anticipate it being a problem. HTH

@tendres I just wanted a few details, i understand you have used postgres as your data source, but what was the configuration of your machine? Were you using a single node to do the processing for such huge dataset? How much total time did it take for you to complete the whole exercise?

**Comment by fgregg** [comment]
Not a bug report or feature request.

**Comment by LogeswaranAudhikesavan** [comment]
Sushant20, have you got any luck in processing 200 Million records?, how did you handle it. Would be great, if you could shed some lights on this issue.
