### ISSUE TITLE
How well does affine distance deals with missing?

### ISSUE THREAD

**Issue by arthur-rocha** [dedupeio/dedupe#755]
So, I was searching in the documentation to understand how dedupe deals with missing data and I found that it can be incorporated in the model using some parameters, however there is no information about how the missing data affects the choose of centroid in a cluster, which is based in the normalized affine gap distance.

**Comment by fgregg** [comment]
`getCentroid` is a pretty simplistic method at this point, it could be improved in a number of ways and better handling of missing data is certainly one of them.
