### ISSUE TITLE
Large dataset 2 Million records - Clustering

### ISSUE THREAD

**Issue by Neelotpaul** [dedupeio/dedupe#756]
Dear Dedupe Team,

I have used this brilliant library and using to de-duplicate for huge data in CDH cluster. I am fetching the data from Hive database and then using my code piece to create sample, train the data and then getting output as per my requirement. i do have clusters with few worker nodes, so i have used pyspark to do some processing. But the clustering and creating cluster dupes dictionary, is something which comes from dedupe library. Though this is done in pythonic way and uses single node to do all the processing, it takes huge amount of time and breaks our patience. 

I wanted to know if anyone has created something like this, or using dedupe for Huge dataset. What is the configuration you are using and how are you tackling creating dictionaries for cluster dupes and other things.

It would be very beneficial if i get some pointers.

Warm regards,
Neelotpaul

**Comment by fgregg** [comment]
the main impediment to doing distributed clustering is the step where we find the the connected components prior to the hierarchical agglomerative clusterings.

There are parralel algorithms for this, and if you'd like to implement one I'd be happy to review the PR.
