### ISSUE TITLE
Feature request: allow the deduper.sample() method to ensure that rows included in previous training runs are included in the sample it returns

### ISSUE THREAD

**Issue by EfremBraun** [dedupeio/dedupe#757]
@fgregg: A feature request would be to allow the deduper.sample() method to ensure that rows included in previous training runs are included in the sample it returns. I think it's quite common for users to tinker with a smaller data set before going up to a larger one.

_Originally posted by @EfremBraun in https://github.com/dedupeio/dedupe/issues/655#issuecomment-511933184_

EDIT
Applies even when staying on a single data set. See https://github.com/dedupeio/dedupe/issues/655#issuecomment-511933184

**Comment by fgregg** [comment]
duplicate of #753
