### ISSUE TITLE
Date ranges?

### ISSUE THREAD

**Issue by gap777** [dedupeio/dedupe#764]
Would it be possible to make a data type for a date range? "Match" is 1.0 for exact endpoint match, 0.5 for overlapping ranges, and 0 for non-overlapping ranges.

**Comment by adriennefranke** [comment]
You could potentially make your own using the [custom type](https://docs.dedupe.io/en/latest/Variable-definition.html#custom-types).

**Comment by gap777** [comment]
Is there a way for a custom type to access more than one property of each object?

**Comment by adriennefranke** [comment]
Right now, the custom comparator can only take in one field from each object. Alternatively, you could format your data to have the start date and end date within one field and then parse those dates out in your custom comparator's function logic. That probably wouldn't be very efficient in the long term though.

So maybe this would be a good idea for a feature request - expanding the custom type to access more than just one field in each object.

**Comment by gap777** [comment]
Sounds good! Let me know how I can help to move this idea forward.

**Comment by fgregg** [comment]
you could also make two custom comparators one that evaluate and use an interaction comparison to get what you want.

**Comment by gap777** [comment]
@fgregg Can you provide more details on your suggestion? I'd like to try it out.

**Comment by adriennefranke** [comment]
@gap777 I just found this that might be helpful for you: https://github.com/dedupeio/datetime-distance
