### ISSUE TITLE
Python 3.7.4 install error with fastcluster

### ISSUE THREAD

**Issue by davidxhuang** [dedupeio/dedupe#765]
I am trying to install dedupe for Python 3.7.4, but get an error while trying to install fastcluster. I get the same error using the windows wheel or the method in the wiki (https://github.com/dedupeio/dedupe/wiki/How-to-install-dedupe,-%5BTUTORIAL%5D-on-Windows-7). I can install the latest version of fastcluster, but when I try to install dedupe it uninstalls it and tries to install another version and gives an error message. Any ideas?

![image](https://user-images.githubusercontent.com/33134541/61916884-43dd9780-aeff-11e9-918e-1185b11b9b9e.png)

I've also seen an error that says "gcc: error: src/cpredicates.c: No such file or directory." In some of the other threads, it's suggested to build cpredicates.c from source from the cython files: https://github.com/datamade/dedupe#developers. I see the cpredicates.pyx file, but am not sure what I should do with it. Can someone please explain what this means?

_Originally posted by @davidxhuang in https://github.com/dedupeio/dedupe/issues/726#issuecomment-515260388_

**Comment by seacen** [comment]
same issue here

**Comment by seacen** [comment]
different error msg though:
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\zhao.x.12\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ZHAOX~1.12\\AppData\\Local\\Temp\\1\\pip-install-d48qhfnf\\fastcluster\\setup.py'"'"'; __file__='"'"'C:\\Users\\ZHAOX~1.12\\AppData\\Local\\Temp\\1\\pip-install-d48qhfnf\\fastcluster\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ZHAOX~1.12\AppData\Local\Temp\1\pip-record-5fwe6n9e\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\ZHAOX~1.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\
    Complete output (23 lines):
    Version: 1.1.24
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying fastcluster.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_fastcluster' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\users\zhao.x.12\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Ic:\users\zhao.x.12\appdata\local\programs\python\python37\include -Ic:\users\zhao.x.12\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/fastcluster_python.cpp /Fobuild\temp.win-amd64-3.7\Release\src/fastcluster_python.obj /EHsc
    fastcluster_python.cpp
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
    Use fenv header. If there is a warning about unknown #pragma STDC FENV_ACCESS, this can be ignored.
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(54): warning C4068: unknown pragma
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(831): error C2065: 'idx': undeclared identifier
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(831): error C2065: 'idx': undeclared identifier
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(832): error C2065: 'idx': undeclared identifier
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(833): error C2065: 'idx': undeclared identifier
    C:\Users\zhao.x.12\AppData\Local\Temp\1\pip-install-d48qhfnf\fastcluster\src\fastcluster.cpp(1038): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by fgregg** [comment]
how are you installing?

**Comment by davidxhuang** [comment]
I tried "pip install dedupe" and ran into the error in the screenshot. I also tried downloading dedupe and using "python setup.py install" but I get: "gcc: error: src/cpredicates.c: No such file or directory."

**Comment by fgregg** [comment]
please try to install from pypi again. just released a new version that should work.

**Comment by davidxhuang** [comment]
Amazing job. Thank you so much, Forest! I just installed it.
