### ISSUE TITLE
Comparing lists of addresses?

### ISSUE THREAD

**Issue by jasondoc3** [dedupeio/dedupe#768]
Is there are recommended way to compare a list of addresses? I have records that have more than one address associated with them. The field should be considered a match if both records have at least one common address.

I've been using the `Set` type for this, but is there a better way?

**Comment by fgregg** [comment]
you could use set, or you could use multiple addrss comparisons (i.e. define a comparison for every pair of possible addresses. I would also probably add an interaction variable for all those comparisons)
