### ISSUE TITLE
Nicknames?

### ISSUE THREAD

**Issue by gap777** [dedupeio/dedupe#769]
Do you believe it to be possible to use dedupe for matching entities when nicknames are involved? I'm thinking of common english nicknames, like Bill/William, John/Jack, John/Jonathan, Amanda/Mandy, as well as shortened names like Josh/Joshua, Bill/Billy, Jon/Jonathan.

**Comment by fgregg** [comment]
yes.

**Comment by gap777** [comment]
Can you provide any direction on how to do that? Do I train it once that Bill Johnson matches William Johnson, and expect it to thereafter recognize Bill Jones matches William Jones?

**Comment by gap777** [comment]
@fgregg ?
