### ISSUE TITLE
Blocker leaves out records

### ISSUE THREAD

**Issue by MrNerdy42** [dedupeio/dedupe#770]
I have noticed that Dedupe.blocker randomly ignores some of the records it is passed. I would think that given lets say 500,000 records it should generate at least 500,000 block key record ID pairs if each record is in only one block, or more if there are records which belong to multiple. I however am encountering records that are in the original dataset, but completely missing from the data that that blocker generates.

**Comment by fgregg** [comment]
if you learn a blocking rule that does match a given record, the blocking rule will not generate a block key for that record.

for example, you might have a blocking rule that extracts integers from a field. on a record where that field has no integer, it won't have blocking rule.

Given that, it is not clear that there is a bug here. If you find an example of a place where the blocking rules you learned **should** have make a key, but didn't please reopen.

**Comment by MrNerdy42** [comment]
Okay, that actually makes perfect sense, thank you for the quick response. I guess that a possible "solution" to this issue would be to retrain the model with a larger sample size and more manually marked files in hopes of unlearning, if that's possible, predicates that leave out too much data.
