### ISSUE TITLE
BlockingError

### ISSUE THREAD

**Issue by SeregaKR** [dedupeio/dedupe#771]
Hello. I'm trying to use mysql example with my data.
I have a db with fields fam,nam,snam,sex,dt_beth with full name, sex and date of birth. My task is to find doubles. 
To train the model I select 30 records from db and create manually 10 doubles (9 doubles and one marked as unsure). After training is complete, I try to use it on the whole database. I get the error below. I found closed issues with this problem, but I could not find a solution.

```
Traceback (most recent call last):
  File "D:\Distr\WPy64-3740\mysql_example.py", line 385, in <module>
    for cluster, scores in clustered_dupes :
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\dedupe\api.py", line 121, in matchBlocks
    threshold=0)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\dedupe\core.py", line 214, in scoreDuplicates
    raise BlockingError("No records have been blocked together. "
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?
```

**Comment by reloaded001** [comment]
I am having the exact same issue. Has there been a fix for this? BTW I am using the mysql example.

Here is the log:

WARNING:dedupe.backport:Dedupe does not currently support multiprocessing on Windows
reading from  mysql_example_settings
blocking...
creating blocking_map database
creating inverted index
writing blocking map
prepare blocking table. this will probably take a while ...
clustering...
creating entity_map database
Traceback (most recent call last):
  File "mysql_example_mod2.py", line 270, in <module>
    for cluster, scores in clustered_dupes :
  File "C:\ProgramData\Anaconda3\lib\site-packages\dedupe\api.py", line 121, in matchBlocks
    threshold=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dedupe\core.py", line 214, in scoreDuplicates
    raise BlockingError("No records have been blocked together. "
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?

**Comment by SeregaKR** [comment]
The same error . I have not found the solution unfortunately.

Here is the log:
reading from  mysql_example_settings
blocking...
creating blocking_map database
creating inverted index
writing blocking map
prepare blocking table. this will probably take a while ...
clustering...
creating entity_map database
Traceback (most recent call last):
  File "D:\Distr\WPy64-3740\mysql_example.py", line 385, in <module>
    for cluster, score in clustered_dupes :
  File "D:\Distr\WPy64-3740\python-3.7.4.amd64\lib\site-packages\dedupe\api.py", line 121, in matchBlocks
    threshold=0)
  File "D:\Distr\WPy64-3740\python-3.7.4.amd64\lib\site-packages\dedupe\core.py", line 214, in scoreDuplicates
    raise BlockingError("No records have been blocked together. "
dedupe.core.BlockingError: No records have been blocked together. Is the data you are trying to match like the data you trained on?
>>>

**Comment by reloaded001** [comment]
I read somewhere that it would work with MariaDB 10.2+ with Python 3.5. Haven't been able to test it on my end, however, if someone can test and update here.

Many thanks.

**Comment by reloaded001** [comment]
ok I have had some success, not entirely sure if this is supposed to be done this way. I found the issue to be in this piece of code:

```
clustered_dupes = deduper.matchBlocks(candidates_gen(c),
                                      threshold=0.5)
```
This is passing the results of the query to the candidates_gen(result_set). I tried to see what the datatype was in the C and it was set to <MySQLdb.cursors.SSDictCursor object at 0x000001D0DC988688>.

I then did a fetchall on c and assigned it to a variable like this:

`resultq = c.fetchall()
`
Then I changed the original from this:

clustered_dupes = deduper.matchBlocks(candidates_gen(**c**),
                                      threshold=0.5)

to this:

```
clustered_dupes = deduper.matchBlocks(candidates_gen(**resultq**),
                                      threshold=0.5)

```
and it worked. or at least it seems that it did.

So in summary, instead of passing candidates_gen() a cursor object, I passed it a set of dictionaries and i think it worked.

Please let me know if you are able to test this.

Many thanks.

**Comment by SeregaKR** [comment]
I tried adding the line and changing the original one to :
resultq = c.fetchall()
clustered_dupes = deduper.matchBlocks(candidates_gen(resultq), threshold=0.5)

But I get the same error in the for cycle here:

```
for cluster, score in clustered_dupes :
    cluster_id = cluster[0]
    for donor_id, score in zip(cluster, scores) :
        c.execute('INSERT INTO entity_map VALUES (%s, %s, %s)',(donor_id, cluster_id, score))
```

**Comment by reloaded001** [comment]
Hi Sergey,

Here is my version of the working code. It works with the same database as
the sample. I am using python 3.7.4 and MariaDB/MySQL 10.4.6:

https://pastebin.com/De8TnK0e

Hope this helps.

Best.

**Comment by SeregaKR** [comment]
I'll try to run this code tomorrow
