### ISSUE TITLE
Multiprocessing in later version not working properly

### ISSUE THREAD

**Issue by monicatao** [dedupeio/dedupe#772]
Hi, I upgraded the library and ran gazette but it's getting much slower than the previous versions.  I found it started to get slower since from version 1.9.7. And the function it's slower is dedupe.core.scoreGazette.

I compared the GitHub from 1.9.6 and 1.9.7 and cannot tell the reason why it's happening. 

After some investigation, I think it might be the multiprocessing in the later version is not working properly. I tried it with both multiprocessing and no multiprocessing and running no multiprocessing is even faster than the current one with multiprocessing.

Could you help investigate this? Thank you!!

**Comment by fgregg** [comment]
can you use profiling (https://docs.python.org/3/library/profile.html) to
provide data on the speed difference and where the difference is

**Comment by fgregg** [comment]
this should be fixed in an upcoming release.

**Comment by michael-clarkson** [comment]
Hi @fgregg is this fixed in the 1.10 release?

Thanks!

**Comment by fgregg** [comment]
no, it's fixed on the https://github.com/dedupeio/dedupe/tree/dedupe_2 branch

**Comment by michael-clarkson** [comment]
Ok thanks, do you have a plan about when you would like to release it?

**Comment by fgregg** [comment]
no

**Comment by monicatao** [comment]
Hi @fgregg is there a reason why it's not fixed in the new release but in a different branch?

**Comment by fgregg** [comment]
please feel free to port the fix.

**Comment by fgregg** [comment]
closed by https://github.com/dedupeio/dedupe/pull/788
