### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by ferraijv** [dedupeio/dedupe#775]
I am training a rather large gazetteer model. Whenever I run writesettings(), I get the above error. Is there another way of saving the model, or do I need to rewrite writesettings()?

**Comment by cyranix** [comment]
I'm getting started with Dedupe, specifically Gazetteer, and I'm encountering this as well.

A portion of my code, which is based heavily on your CSV example:
```
dedupe.consoleLabel(gazetteer)

gazetteer.train()

with open(training_file, 'w') as file:
    gazetteer.writeTraining(file)

gazetteer.index(canonical)

with open(settings_file, 'wb') as file:
    gazetteer.writeSettings(file, index=True)
```

Result, after reaching the `writeSettings` call:
```
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    main()
  File "train.py", line 27, in main
    train_gazetteer(gazetteer, messy_recordset, canonical_recordset)
  File "train.py", line 107, in train_gazetteer
    gazetteer.writeSettings(file, index=True)
  File "/home/andrew/dedupe-test/env/lib/python3.6/site-packages/dedupe/api.py", line 1079, in writeSettings
    super().writeSettings(file_obj, index)
  File "/home/andrew/dedupe-test/env/lib/python3.6/site-packages/dedupe/api.py", line 149, in writeSettings
    self._writeIndices(file_obj)
  File "/home/andrew/dedupe-test/env/lib/python3.6/site-packages/dedupe/api.py", line 168, in _writeIndices
    pickle.dump(indices, file_obj)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ferraijv** [comment]
I never found a solution for this. I ended up setting the `index` parameter to False, and it writes, but I'm assuming with a hit to performance

**Comment by fgregg** [comment]
gazetteer.writeSettings(file, index=True)

can let you avoid having to reindex the data, but has this issue that sometimes you run into recursion. 


gazetteer.writeSettings(file, index=False) and things will work, but you will have an indexing step
