### ISSUE TITLE
clustered_dupes is empty when I send the data with smaller_ids

### ISSUE THREAD

**Issue by pmalipeddi** [dedupeio/dedupe#776]
I am using MongoDB to get clusterids and passing the data "records" in the code to deduper.matchBlocks as below but I am not getting any cluster_ids back as  "clustered_dupes" is always empty, am I passing the data to match blocks in a wrong format? if this is  wrong format for match blocks please let me know the correct format
**Records with smaller_ids**:  
[('ETY1211', {'EtyNbr': 'ETY1211', 'block_id': 2, 'smaller_ids': [2], 'Alpha': 'A', 'City': 'EAST HARTFORD', 'ClusterInd': 'N', 'Cntry': 'US', 'Fname': 'A DALE & JUDY', 'FullAddr': '92 LANGFORD LN ', 'Lname': 'HUSTON', 'State': 'CT', 'Zip': '06118', 'cluster_conf': '-1', 'cluster_id': '-1'}, {2}), 
('ETY1213', {'EtyNbr': 'ETY1213', 'block_id': 2, 'smaller_ids': [2], 'Alpha': 'A', 'City': 'EAST HARTFORD', 'ClusterInd': 'N', 'Cntry': 'US', 'Fname': 'A DALE & JUDY', 'FullAddr': '92 LANGFORD LN ', 'Lname': 'HUSTON', 'State': 'CT', 'Zip': '06118', 'cluster_conf': '-1', 'cluster_id': '-1'}, {2})] 

When I pass the data to match blocks as below where with " set()" is empty then I am getting cluster_ids from clustered_dupes
**Records without smaller_ids**:
[('ETY1217', {'EtyNbr': 'ETY1217', 'block_id': 2, 'smaller_ids': [2], 'Alpha': 'A', 'City': 'EAST HARTFORD', 'ClusterInd': 'N', 'Cntry': 'US', 'Fname': 'A DALE & JUDY', 'FullAddr': '92 LANGFORD LN ', 'Lname': 'HUSTON', 'State': 'CT', 'Zip': '06118', 'cluster_conf': '-1', 'cluster_id': '-1'}, set()), 
('ETY1219', {'EtyNbr': 'ETY1219', 'block_id': 2, 'smaller_ids': [2], 'Alpha': 'A', 'City': 'EAST HARTFORD', 'ClusterInd': 'N', 'Cntry': 'US', 'Fname': 'A DALE & JUDY', 'FullAddr': '92 LANGFORD LN ', 'Lname': 'HUSTON', 'State': 'CT', 'Zip': '06118', 'cluster_conf': '-1', 'cluster_id': '-1'}, set())]

**Comment by fgregg** [comment]
closed by https://github.com/dedupeio/dedupe/pull/788
