### ISSUE TITLE
predicates using ngramsTokens returning empty set

### ISSUE THREAD

**Issue by joshuacortez** [dedupeio/dedupe#777]
Hi, 

I noticed that predicates that use the ngramsTokens function, such as commonTwoTokens and commonThreeTokens, simply return the empty set when the input string has 1 token (for commonTwoTokens) and 1 or 2 tokens (for commonThreeTokens)

Example:
`dedupe.predicates.commonTwoTokens("john")`
returns 
`set()`

while
`dedupe.predicates.commonTwoTokens("john doe")`
returns
`{'john doe'}`

Wouldn't it be better if the first example returned the entire string instead of returning the empty set? Record pairs that should have been in the same block are filtered out with this current setup. The effect is decreased recall.

Proposed outcome:
`dedupe.predicates.commonTwoTokens("john")`
returns 
`{'john'}`

My suggestion is to modify the ngramsTokens functions slightly so that n is capped at the number of tokens.

```
def ngramsTokens(field, n):
    grams = set()
    n_tokens = len(field)
# proposed change
    if n > n_tokens:
        n = n_tokens
    for i in range(n_tokens):
        for j in range(i + n, min(n_tokens, i + n) + 1):
            grams.add(' '.join(str(tok) for tok in field[i:j]))
    return grams
```

What do you guys think? :)

Here's what I'm using:
Python Version 3.7.3
Dedupe Version 1.9.9

**Comment by fgregg** [comment]
the promise of the commonTwoTokens is that two tokens are common, your proposal would be something very different.
