### ISSUE TITLE
How to make sure same Samples are chosen by `prepare_training` and `trainingDataDedupe`?

### ISSUE THREAD

**Issue by tshrjn** [dedupeio/dedupe#778]
Hi 

I'm getting the following error when running `deduper.markPairs(training_pairs)`:
```
AttributeError: Attempting to block with an index predicate without indexing records
```

As [pointed](https://github.com/dedupeio/dedupe/issues/655#issuecomment-511933184) out by @EfremBraun in [issue 665](https://github.com/dedupeio/dedupe/issues/655), this is due to a few `training_pairs` samples not being indexed by `prepare_training`.

One solution is to upper bound the sampling and indexing process in `prepare_training` by providing `n**2` as the `sample_size`. However, doing this increases computation time (In my case also somehow the process gets killed).

So, is there a way to make sure the same Samples are chosen by `prepare_training` and `trainingDataDedupe`?

PS: I'm following the [tests/canonical](https://github.com/dedupeio/dedupe/blob/ce567c8046c9520fc7f8e98bbb70448b87be563e/tests/canonical.py) to train from a file with ground truth answers.

**Comment by dfiorino** [comment]
You might want to see: https://github.com/dedupeio/dedupe/issues/753

Which led to: https://github.com/dedupeio/dedupe/pull/761

I'm about to see if this works out for me!

**Comment by fgregg** [comment]
as @dfiorino points out, this has already been addressed
