### ISSUE TITLE
Dedupe asking for re-training from already trained pairs

### ISSUE THREAD

**Issue by suyashdb** [dedupeio/dedupe#779]
I already have huge training data which is tagged correct or incorrect. Its store under training.json. 

The issue is, when i use this training data along with two new csv to link between, Dedupe picks up pairs from the training.json for re-training it instead of asking new pairs from the csv i supplied..

Any pointers why this might be happening and how it can be avoided...?

**Comment by sskadamb** [comment]
I have the exact same issue, and pairs that I have already answered as "y/n" come up multiple times afterword. How to avoid this?

**Comment by fgregg** [comment]
if you have not removed exact deduplicates from your data, this can happen.
