### ISSUE TITLE
AttributeError: Attempting to block with an index predicate without indexing records

### ISSUE THREAD

**Issue by MatthewPavia** [dedupeio/dedupe#786]
I have a number of large datasets (e.g., datasets A, B and C), all in CSV format. For training purposes, to avoid creating a model for each dataset separately, I created a new dataset containing records from all the said datasets (datasets A, B and C), where the exception "AttributeError: Attempting to block with an index predicate without indexing records" is being thrown.

Note that this new dataset was created with sample data from each dataset, since they all contain the same type of data (i.e., same schema). Moreover, the aim behind this deduplication process is to have a common trained model which can be applied to different datasets having the same data model.

Please guide me, if I am missing anything within the dataset used for training and/or config file.

**Comment by fgregg** [comment]
https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.blocker.index

**Comment by rahullak** [comment]
Hi @fgregg 
The docs link provided above does not work ie. it leads to the documentation site but there is no #Dedupe.blocker.index in the documentation.

Could you please let me know where I can find information on this error as I am facing the same error when I try to mark pairs using a dictionary.

**Comment by fgregg** [comment]
https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.blocking.Fingerprinter.index

but you probably want to use the prepare_training method
