### ISSUE TITLE
Documentation on blocks is confusing / inaccurate

### ISSUE THREAD

**Issue by jdotjdot** [dedupeio/dedupe#789]
_(Whoops&mdash;originally posted this as dedupeio/dedupe-examples#101, whereas it is probably better for this repo. Moving it over here instead.)_

Thanks for this awesome project! We're really excited to start using it.

That said, we've had a lot of trouble understanding the documentation.  In particular for blocks, it appears to be a combination of missing information, out of date, and internally inconsistent.  The clearest example of this is in the documentation for `Gazetteer` ([link](https://docs.dedupe.io/en/latest/API-documentation.html#Gazetteer)).  We're using Gazetteer on a large quantity of data, so we're trying to use `matchBlocks()` instead of `match()`, but even with reading the source code, we haven't been able to figure out how to properly set up the blocks. As an initial example, the `Gazetteer` object in the docs actually defines `matchBlocks()` twice, with _different_ documentation that includes different examples.  

[First definition][1], with the final example block structure as follows (the example itself is also syntactically invalid, the parens don't match up):
![image](https://user-images.githubusercontent.com/1328961/71748322-2282bf00-2e40-11ea-9841-662cbae7d942.png)

The second redefinition doesn't have a direct page link, so go [here][2] and then scroll up slightly to see it.  Final example block structure it gives:
![image](https://user-images.githubusercontent.com/1328961/71748370-53fb8a80-2e40-11ea-99c2-90613ba5bf3b.png)

`StaticGazetteer` has the same issue, presumably due to inheritance.

Can you clarify what the right way to do blocking is? Thanks so much!

[1]: https://docs.dedupe.io/en/latest/API-documentation.html#Gazetteer.matchBlocks
[2]: https://docs.dedupe.io/en/latest/API-documentation.html#Gazetteer.writeSettings

**Comment by fgregg** [comment]
closed by https://github.com/dedupeio/dedupe/pull/788
