### ISSUE TITLE
crashes during run

### ISSUE THREAD

**Issue by sanjevanb** [dedupeio/dedupe#791]
Hi, 
im trying the dedupe python code.
is there a way to split the steps
like when you run the file, first process it
than get all the required verification question asked after?
than processes the file output

also does anyone who ...what the min server requirement is to run a large file with let say 1M entry?

**Comment by fgregg** [comment]
take a look at https://github.com/dedupeio/dedupe-examples/tree/master/pgsql_big_dedupe_example
