### ISSUE TITLE
canonicalize only working with strings

### ISSUE THREAD

**Issue by guyts** [dedupeio/dedupe#792]
After running deduping (on some fields that are non-strings, like `LatLong` and `Price` for example, meaning these two are by definition not strings in the data model), I tried using the [csv example](https://dedupeio.github.io/dedupe-examples/docs/csv_example.html) to build a file with all dupes, but `canonicalize` throws a type error.

How does one handle non-strings? Skip canonicalization altogether?

**Comment by fgregg** [comment]
related to #274, #274 

right now cast to string.
