### ISSUE TITLE
conceptual question

### ISSUE THREAD

**Issue by obibring** [dedupeio/dedupe#796]
Hey there, many thanks for your great work on this library! I'm struggling to understand the idiomatic way to do the following:

I have a collection of stores and for store I have 4 different versions of the products they sell. While I have millions of total records, I only need to deduplicate on the individual store level, meaning I don't need compare products from store X to products from store Y.

Is there a way to tell Dedupe to only compare items to a small portion of the total dataset?

**Comment by fgregg** [comment]
only use the relevant columns in your data model
