### ISSUE TITLE
LevenshteinIndex not reloading correctly from settings 

### ISSUE THREAD

**Issue by BernardDuyckaerts** [dedupeio/dedupe#798]
Dear all, 

Not sure what I see is true, or if it is me not using the library in the proper way, if the latter, appologies in advance.
 
When reloading the index from a setting file, the self._doc_to_id dictionary is reloaded correctly but yet the data that should be stored in the Levenshtein_search object is not.

Indeed the call to index can find the doc in the dictionary (it has been deserialized) and therefore do not call the add_string that would populate the C tree object.

if doc not in self._doc_to_id:
    self._doc_to_id[doc]        
     Levenshtein_search.add_string(self.index_key, doc)

Then all subsequent searches fail retrieving similar words, since the Levenshtein_search is empty.

**Comment by fgregg** [comment]
closed by https://github.com/dedupeio/dedupe/pull/788
