### ISSUE TITLE
use dedupe on ongoingly growing database

### ISSUE THREAD

**Issue by guyts** [dedupeio/dedupe#799]
A nice feature to have is enable dedupe to work with a database where records are regularly added, and need to be grouped to already-clustered records. 

At the moment, to use dedupe, I approach the problem by:
1. Running an initial deduping process (keeping all records, but assigning them a new `cluster_id`
2. Every x days re-running dedupe on past data + new
3. After deduping complete (and clusters were determined), grab previous `cluster id`s  and reassign those ids to new records that matched the original sets, while records that grouped but didn't exist before, simply get a new cluster id.

Is there a smarter way to do it using dedupe? Pluggning in a new row, and checking whether it fits into any existing cluster, or give it a new independent number? 

I looked at Gazetteer but part of the issue is that I need to actually keep all dupes, just mark their cluster. (https://github.com/dedupeio/dedupe/issues/421)

**Comment by deepesch** [comment]
can you elaborate step 3? Would it be easier to use record linkage on the new data?

**Comment by mmcgarry92** [comment]
Hi @guyts did you have any luck implementing this? I'm facing a similar task whereby I will have a stream of similarly structured data coming in and will need to match records across datasets. A Gazetteer object seems to be the best way to do this for a single instance of two datasets, but I'm struggling to understand how dedupe can manage with constantly adding new data to a model to re-train it.
