### ISSUE TITLE
does the order of records influence the outcome?

### ISSUE THREAD

**Issue by Polhovsky** [dedupeio/dedupe#800]
Hi there,

Once the connected components are formed, clustering takes place. The resulting graph (at least with the code I have implemented) seems to be directed since the condensed distances contain 1 minus the value of the corresponding elements of the upper triangular adjacency matrix only. As a result the order in which the records are in the database influence the outcome.

In reality I don't think the edges should be directional. After all, address A relates to address B in the same way as address B does to address A. So, if I dedupe 10K records I expect the same outcome as when I dedupe the same 10K records in a shuffled way (randomly shuffle the rows). Perhaps my analysis is incorrect in which case I hope someone can point me in the right direction.

An example:

[array([([324314, 324264], 0.8 ),
            ([324314, 324204], 0.92),
            ([324264, 324204], 0.9 )], dtype=[('pairs', '<i4', (2,)), ('score', '<f4')])]

results in the following cluster:

[((324204, 324264), array([0.89999998, 0.89999998]))]

but if I reverse the order of the edges:

[array([([324264, 324314], 0.8 ),
           ([324204, 324314], 0.92),
           ([324204, 324264], 0.9 )], dtype=[('pairs', '<i4', (2,)), ('score', '<f4')])]

I get this cluster:

[((324204, 324264, 324314), array([0.91      , 0.84999999, 0.86000001]))]

Is it correct that the order of the records matters or should the outcome be the same regardless of the order?

**Comment by fgregg** [comment]
in creating the condensed matrix, we assume that the record pairs are such that the smaller record id is first. if this is not true, then the correct condensed matrix will not be created.

I'll add a note to the documenation and perhaps an assert to raise a useful error if this assumption is violated.

this is all quite independent on the row order of the original data.

**Comment by Polhovsky** [comment]
thanks for your quick response

I have used a record-id as index which is originally monotonically increasing but not anymore after shuffling. Then the smaller id is not necessarily first, so that explains the difference in outcome.

**Comment by fgregg** [comment]
the row order of the records should have no effect on which record id appears first in a pair.

**Comment by Polhovsky** [comment]
also when for example in the postgresql big dedupe example the donor-id is not monotonically increasing in the processed_donors table?

**Comment by fgregg** [comment]
shuffle the order of donor id if you'd like. or make it strictly descending. this line makes it so that the row order does not matter. https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L258

> the row order of the records should have no effect on which record id appears first in a pair.
