### ISSUE TITLE
Clustering multiprocessing/reduction.py MemoryError

### ISSUE THREAD

**Issue by deepesch** [dedupeio/dedupe#807]
1350000
1360000
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
1370000

Program is stuck here for long time. Has anyone figured out how to avoid memory errors?

Memory Usage below:
svmem(total=33561993216, available=31999352832, percent=4.7, used=1140838400, free=27479076864, active=4481572864, inactive=1024360448, buffers=139243520, cached=4802834432, shared=13053952, slab=292618240)

**Comment by fgregg** [comment]
hmm... if you happen to have more of a trackeback i'd like to see that.
