### ISSUE TITLE
ValueError "could not broadcast input array" during scoring, new code has wrong behavior

### ISSUE THREAD

**Issue by fjsj** [dedupeio/dedupe#808]
Hi, I'm getting the following exception on Dedupe 2.0.0:

```
.../venv/lib/python3.7/site-packages/dedupe/core.py in fieldDistance(self, record_pairs)
    158 
--> 159                 scored_pairs['pairs'] = ids
    160                 scored_pairs['score'] = scores

ValueError: could not broadcast input array from shape (249,2) into shape (228,2)
```

Looks like the new code is wrong, the old code used a mask:
https://github.com/dedupeio/dedupe/blob/96f9b895948f856637591c4b3dc9807eadf0d626/dedupe/core.py#L143-L148

The new code doesn't:
https://github.com/dedupeio/dedupe/blob/7df2ab5ef268080a60e1f3f31248de985d93c598/dedupe/core.py#L155-L157

That's problematic because the new code is still using `numpy.count_nonzero`. So the `scored_pairs` array may get a smaller shape than `ids`, causing the broadcast error. That happen when `scores` contain zeros.

Please let me know if a full reproduction is useful or if this is already clear enough.

**Comment by fgregg** [comment]
thanks for the report! cutting new release now.
