### ISSUE TITLE
Normalized Affine Gap Distance:  Zero Division Error

### ISSUE THREAD

**Issue by data-group-aus** [dedupeio/dedupe#810]
Hi There

We are using Dedupe to links records between two data sets of products.  Our code is primarily based on your "record linkage" example.  The system errors when we prepare the data for training on a sparsely populated field, which contains the colour of the item.

To replicate this, please open your record linkage example.  Generate a new column called "prod_colour" when importing your data set.  This can be achieved by:

import random

#IMPORT DATA SECTION:  Generate a new field called "prod_colour"
clean_row['prod_colour'] =  random.choice(['black', 'white', 'red', '', '', '', '', '', '', '', '', '', '', '', ''])

#FIELD DEFINITION SECTION:  Please include a new field:
{'field': 'prod_colour', 'type': 'String'},

#RUN TRAINING:
linker.prepare_training ......

#SYSTEM WILL ERROR:  
linker.prepare_training(data_oc, data_wnc, sample_size=15000)
  File "/usr/local/lib/python3.7/site-packages/dedupe/api.py", line 1336, in prepare_training
    original_length_2)
  File "/usr/local/lib/python3.7/site-packages/dedupe/api.py", line 1370, in _sample
    index_include=examples)
  File "/usr/local/lib/python3.7/site-packages/dedupe/labeler.py", line 464, in __init__
    self._common_init()
  File "/usr/local/lib/python3.7/site-packages/dedupe/labeler.py", line 319, in _common_init
    candidates=self.candidates)
  File "/usr/local/lib/python3.7/site-packages/dedupe/labeler.py", line 98, in __init__
    self.distances = self.transform(self.candidates)
  File "/usr/local/lib/python3.7/site-packages/dedupe/labeler.py", line 106, in transform
    return self.data_model.distances(pairs)
  File "/usr/local/lib/python3.7/site-packages/dedupe/datamodel.py", line 83, in distances
    record_2[field])
  File "affinegap/affinegap.pyx", line 111, in affinegap.affinegap.normalizedAffineGapDistance
  File "affinegap/affinegap.pyx", line 130, in affinegap.affinegap.normalizedAffineGapDistance
ZeroDivisionError: float division

#HAVE ALSO TRIED:
1) Setting blank colours to None.  Same error
e.g. clean_row['prod_colour'] =  random.choice(['black', 'white', 'red', None, None, None, None, None, None, None, None, None, None, None, None])

2) Changing the prod_colour field to "ShortString". Same error 

3) Including "has missing: True" in the field, still errors
e.g. {'field': 'prod_colour', 'type': 'ShortString', 'has missing': True},
 
4) The system will run and work as expected if we leave this field out, however, some of the proposed matches are incorrect as the colours of the matched products are different.

5) Changing the prod_colour field to "Text".  Program will run as expected.
e.g. {'field': 'prod_colour', 'type': 'Text', 'has missing': True}

Your documentation mentions that "Text" fields are for use when "you want to compare fields containing long blocks of text", so is this the appropriate choice, when comparing one-word colours?

Thank you for making Dedupe available as open source.  Its a great package.

**Comment by cilopez** [comment]
I fixed this error, i used to have the same mistake when i was filling like this:
`df['text'] = df['text'].fillna('')`

Then i fixed it with
`df['text'] = df['text'].fillna('nan')`
I know is not the same but it kind of works

**Comment by fjsj** [comment]
If I recall correctly, there should be no empty strings in your data. Change the empty strings to `None` to prevent this issue.
