### ISSUE TITLE
Any reason for supporting generator param only at GazetteerMatching?

### ISSUE THREAD

**Issue by fjsj** [dedupeio/dedupe#813]
Hi folks, at Dedupe 1.10.0, `DedupeMatching`, `RecordLinkMatching` and `GazetteerMatching` supported the `generator` param in matching methods. See: 

https://github.com/dedupeio/dedupe/blob/96f9b895948f856637591c4b3dc9807eadf0d626/dedupe/api.py#L189-L222

Now only `GazetteerMatching` supports `generator`.
Any reason for that? I'm not sure if generator gives a lot of memory saving, but I think it's worth investigating.

**Comment by fgregg** [comment]
1. only the `search` method actually allows streaming behavior, i.e. if you can get matches one at a time from the `search` method. for the other classes, we have to make *all* comparisons before we can start to give you any comparisons back. having the generator will not provide any real memory savings.

2. the dedupe 2.0 api is much cleaner, imo, and you can restore the generator behavior by doing either `cluster(score(pairs(data)))` or `one_to_one(sore(pairs(data_1, data_2)))`

**Comment by fjsj** [comment]
Sounds good, thanks. Please feel free to close this issue.
