### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by tharma3** [dedupeio/dedupe#814]
Hi team!  Thank you so much for this awesome API.  I wonder if you might be able to fix the [API documentation](https://docs.dedupe.io/en/latest/API-documentation.html) linked to from the repository, which currently is a 403 error?

**Comment by derekeder** [comment]
Thanks for letting us know! We're looking into it

**Comment by tharma3** [comment]
Thank you!!!

**Comment by fgregg** [comment]
Should be sorted now (if it's not fixed yet, try again in an hour as DNS is propagating)
