### ISSUE TITLE
identical records marked as different cluster

### ISSUE THREAD

**Issue by davelowndes** [dedupeio/dedupe#817]
I am deduping point of interest information with name, content, etc. based on the Patent example code with modifications. The initial clustering works fine. I parse the results but then mix it back in with minor updates to the original data.

I'd expect exact duplicates (of which there are many) to return the same cluster id. However I'm finding exact duplicates are coming back under different cluster ids, e.g. these two identical records return with different cluster ids (1st column from csv):

```
143109,1.0,a4f07ffc-8ce2-4def-9488-bf6490b2f518,true,poi,Aachen,Aachen**Eifel (North Rhine-Westphalia)**North Rhine-Westphalia**Germany**Central Europe**Europe,Haus Löwenstein,14th-century building.,see,see,,50.776549**6.083601,
143110,1.0,a4f07ffc-8ce2-4def-9488-bf6490b2f518,true,poi,Aachen,Aachen**Eifel (North Rhine-Westphalia)**North Rhine-Westphalia**Germany**Central Europe**Europe,Haus Löwenstein,14th-century building.,see,see,,50.776549**6.083601,
```

The csv has columns:

`"uuid","trusted","class","parenttitle","ancestors","name","content","template","tag","url","latlong","address"
`

These are my field definitions:
```
    fields = [
        {'field': 'name',
            'variable name': 'name',
            'type': 'String'},
        {'field': 'ancestors',
            'variable name': 'ancestors',
            'type': 'Set',
            'corpus': ancestors(data_d)},
        {'field': 'content',
            'variable name': 'content',
            'type': 'Text',
            'has missing': True},
        {'field': 'url',
            'variable name': 'url',
            'type': 'String',
            'has missing': True},
        {'field': 'latlong',
            'variable name': 'latlong',
            'type': 'LatLong',
            'has missing': True},
        {'field': 'address',
            'variable name': 'address',
            'type': 'String',
            'has missing': True}
    ]
```
What would cause this behaviour?

**Comment by fgregg** [comment]
I don't know without seeing more, but here's something. we don't treat identical records differently, so they are not guaranteed to be matched together.

I recommend that if you always want identical records to be together you preprocess your records before hand.
