### ISSUE TITLE
dedupe.consoleLabel(linker) -- Attribute Error: model 'dedupe' has no attribute 'consoleLabel'

### ISSUE THREAD

**Issue by nbreg** [dedupeio/dedupe#820]
Hello,

I've heard excellent things from multiple researchers who have had great results from dedupe in projects matching large datasets with tricking spelling problems, so I'm looking forward to getting dedupe to work for me.

I am following the instructions on dedupe's GitHub page for running dedupe in a virtual environment on Windows 10 with Python 3.7.6. I install everything successfully and pass the test.

However, when I try to run my script, which is the same as the script made available but with different files and variable names, I get this error:

![error_whole](https://user-images.githubusercontent.com/5891765/82738870-f7bed780-9d08-11ea-838e-1c95345e58c3.PNG)

If I run the blocks of code separately, everything runs without error until I run the Training block of the dedupe script, after which I get this error:
![error_training](https://user-images.githubusercontent.com/5891765/82738902-2ccb2a00-9d09-11ea-92f0-ffe5304ebac3.PNG)

A friend has run my script with my data on his own Windows machine and ran it successfully without error.

Do you know what might be going wrong here?

Thank you in advance!

Nate

**Comment by fgregg** [comment]
where are the instructions you are working off of? these look out of date.

**Comment by nbreg** [comment]
Hello,
I am following the directions on the readme under Installation and Test, as well as the directions it links to in setting up virtualenv:
https://github.com/dedupeio/dedupe/blob/master/README.md

The script I took and modified is here:
https://dedupeio.github.io/dedupe-examples/docs/record_linkage_example.html

I only changed the input/output file names and the field names:
![image](https://user-images.githubusercontent.com/5891765/82755114-9564e600-9d9f-11ea-95bd-e73fbbe94281.png)


Please let me know if there’s more information I can provide.

**Comment by fgregg** [comment]
the code in your original excerpt does not match the code in https://dedupeio.github.io/dedupe-examples/docs/record_linkage_example.html

(consoleLabel vs console_label, for example)

**Comment by nbreg** [comment]
That fixed it -- thanks very much for your time and your help!
