### ISSUE TITLE
How I can print the equation regression?

### ISSUE THREAD

**Issue by sontata** [dedupeio/dedupe#823]
I have structure of data:

```
       fields = [
              {'field': 'address_addressview', 'type': 'String',
             'variable name': 'address_addressview'},

            {'field': 'address_region', 'type': 'Exact',
             'variable name': 'address_region', 'has missing': True},

            {'field': 'address_district', 'type': 'Exact',
             'variable name': 'address_district', 'has missing': True},

            {'field': 'address_locality', 'type': 'Exact',
             'variable name': 'address_locality', 'has missing': True},

            {'field': 'address_street', 'type': 'Exact',
             'variable name': 'address_street', 'has missing': True},

            {'field': 'address_house', 'type': 'String',
             'variable name': 'address_house', 'has missing': True},

            {'field': 'address_building', 'type': 'String',
             'variable name': 'address_building', 'has missing': True},

            {'type': 'Interaction', 'interaction variables': ['address_locality', 'address_street', 'address_house']}
        ]
```

 weights:

`[-5.39908160e+00 -3.12469359e-05  6.47108373e-01  1.46348184e+00
 -1.97021202e+00 -1.22286638e+00  3.93247856e-01  3.79818941e-01
 -3.12469359e-05  6.47108373e-01 -2.80387326e+00  1.08682339e+00
  1.12860238e+00  7.86422633e-01  1.70102405e-01]`

and predicates:

`((SimplePredicate: (hundredIntegerPredicate, address_addressview), SimplePredicate: (oneGramFingerprint, address_addressview)), (SimplePredicate: (twoGramFingerprint, address_addressview), SimplePredicate: (wholeFieldPredicate, address_district)), (SimplePredicate: (twoGramFingerprint, address_house), SimplePredicate: (wholeFieldPredicate, address_district)))
`

I don't understand, what is final regression equation? Predicates are used just for blocking? I want to print equation after loading file of settings as Y = b0 + b1*f1(X1)+....+bn*fn(Xn). Sorry, if question is stupid, but I really don't understand.

**Comment by fgregg** [comment]
it's a normalized logistic regression so `logit(y) = b0 + b1 x_1 ...` wher x_1 is the pairwise distance measure of the first field x_2 is the distance measure of the second field.

**Comment by sontata** [comment]
> it's a normalized logistic regression so `logit(y) = b0 + b1 x_1 ...` wher x_1 is the pairwise distance measure of the first field x_2 is the distance measure of the second field.

Thank you very much for you answer! I didn't understand before why length of weight array and field array is different . Now I found attribute data_model.variables and it's clear.
