### ISSUE TITLE
Large dataset issue

### ISSUE THREAD

**Issue by starun1611** [dedupeio/dedupe#832]
Hi,

We are facing "connection lost" issue while running mysql code on a large dataset. We were able to run the code without any errors and with accurate results when we ran it on 250K-350k datasets. However, it failed on a 1mn records dataset. We trained some 600 odd records during labeling exercise.

We have special characters in some name values and we noticed that they never appeared during labeling when we had smaller dataset but started appearing in case of large dataset.

Below is what happens after writing blocking map
"writing blocking map
INFO:dedupe.blocking:10000, 0.4869392 seconds
INFO:dedupe.blocking:20000, 0.8858992 seconds
INFO:dedupe.blocking:30000, 1.3390832 seconds
INFO:dedupe.blocking:40000, 1.8181592 seconds
.............
INFO:dedupe.blocking:980000, 69.9014982 seconds
INFO:dedupe.blocking:990000, 70.6587972 seconds
INFO:dedupe.blocking:1000000, 71.2766332 seconds"

However when we run indexing on this, we get integrity error so we took unique pairs and then indexed it. When the code calls record_pairs function, it keeps running for a long time and then throws the below errors:

"ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host During handling of the above exception, another exception occurred:"

"OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10054] An existing connection was forcibly closed by the remote host)') During handling of the above exception, another exception occurred:"

"AttributeError: 'NoneType' object has no attribute 'settimeout'"

Can someone please help us out here?

Thanks

**Comment by fgregg** [comment]
this is not really a dedupe issue, but yo probably need to increase your the mysql connection timeout https://stackoverflow.com/questions/14726789/how-can-i-change-the-default-mysql-connection-timeout-when-connecting-through-py
