### ISSUE TITLE
infinite loop in clustering.py _connected_components due to zero pair scores

### ISSUE THREAD

**Issue by joshuacortez** [dedupeio/dedupe#833]
Hi, 

Encountered an issue where the _conencted_components goes into an infinite loop (see screenshot below). I think this occurs when there are pairs that have zero scores. Since numpy treats log of 0 as -Inf, the calculated threshold becomes 0 and the cycle repeats forever. We can remedy this by filtering pair_scores to have scores only above 0. What do you think?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/7113605/85729269-3e01bf00-b72b-11ea-8e9c-246935829e41.png">

Edit: it's not actually infinite looping, but there is unnecessary looping for each additional zero score in the component. Also, the zero scores don't contribute anything to the clustering step, so it's just extra wasted memory space.

**Comment by fjsj** [comment]
After #809 was merged, I think we shouldn't see 0 scores at clustering stage.

**Comment by joshuacortez** [comment]
Hi @fjsj, thanks! After checking, it turned out it wasn't part yet of the 2.0.3 release that I had. Glad to know this issue was already addressed.
