### ISSUE TITLE
Dedupe Performance Issues

### ISSUE THREAD

**Issue by vinayakpandi** [dedupeio/dedupe#838]
I'm running a dataset which has 400k rows and 8 columns(single word column values). Its been 2 days I started running ,dedupe on it and its still running. Any idea how to tune/optimize this.

**Comment by fjsj** [comment]
Try this: https://dedupeio.github.io/dedupe-examples/docs/pgsql_big_dedupe_example.html
From: https://github.com/dedupeio/dedupe-examples
