### ISSUE TITLE
Limitation on Clustering?

### ISSUE THREAD

**Issue by Klaxmax70** [dedupeio/dedupe#842]
Hi there
i am using dedupe just for a few days and have prepared some training data with around 40 rows of data.  The training set contains 15 matches and the others doesn't match to any other record. When finished traing the model and finished clustering the result set contains only of 3 dupes and not the wanted 15 ones. It looks to me like clustering only processes around 10% of data which is fed to the dedupe. Do I something wrong not to get all data clustered in my training set? If there is a limitation where can I  get around it?
BR Markus

**Comment by fgregg** [comment]
sorry, this isn't enough information to answer your question. this type of usage question would also be better asked on stackoverflow.com

thanks!
