### ISSUE TITLE
ChildProcessError

### ISSUE THREAD

**Issue by thomasadams-velocityglobal** [dedupeio/dedupe#846]
![image](https://user-images.githubusercontent.com/60484140/91229624-684e0980-e6e7-11ea-8280-7ac02bf01422.png)

Any ideas?

**Comment by thomasadams-velocityglobal** [comment]
Not too sure why this error is happening.

**Comment by fgregg** [comment]
look like you are having a problem with pandas_dedupe. that's a different project. https://github.com/Lyonk71/pandas-dedupe/issues
