### ISSUE TITLE
Error when only a custom comparator is used

### ISSUE THREAD

**Issue by fritshermans** [dedupeio/dedupe#847]
When I create a dedupe instance using only a 'Custom' comparator, I get an error:
 `TypeError: descriptor 'union' of 'set' object needs an argument`

Please check the code below that reproduces the error:

```
import dedupe

DATA_SAMPLE = {0: {'name': 'Kyle'},
 1: {'name': 'Bob'},
 2: {'name': 'Kyle'},
 3: {'name': 'William'},
 4: {'name': 'Sue'},
 5: {'name': 'William'},
 6: {'name': 'Kyle'},
 7: {'name': 'Jimmy'},
 8: {'name': 'Charlie'},
 9: {'name': 'Jimbo'},
}

def custom_metric(string_1, string_2):
    return int(string_1[:3]==string_2[:3])

fields = [{'field':'name','type':'Custom','comparator':custom_metric}]

deduper = dedupe.Dedupe(fields)

deduper.prepare_training(DATA_SAMPLE)
```

Note that when I include this `custom_metric` together with the 'String' type, it works well:

```
fields = [{'field':'name','type':'Custom','comparator':custom_metric},
         {'field':'name','type':'String'}]

deduper = dedupe.Dedupe(fields)

deduper.prepare_training(DATA_SAMPLE)
```

Could you please check if I did something wrong or if it is a bug?
Thanks a lot in advance.

**Comment by fgregg** [comment]
There are no blocking rules associated with a 'Custom' type and since in your first example it is the only field you have, then blocking cannot happen and you get a mysterious error.

We should update the documentation and also throw an error if the only field that is defined is a Custom type.

**Comment by fritshermans** [comment]
Hi @fgregg, thanks a lot for your response. Would it be possible to set a blocking rule rule manually?

**Comment by fgregg** [comment]
see https://github.com/dedupeio/dedupe-variable-address as an example of creating a new variable types that has custom blocking rule.

not documented i'm afraid
