### ISSUE TITLE
UserWarning: Training data has records not known to the active learner. Read training in before initializing the active learner with the sample method, or use the prepare_training method.

### ISSUE THREAD

**Issue by pooja198** [dedupeio/dedupe#848]
I am using the csvlink tool to find matches between two csv
[OEM.xlsx](https://github.com/dedupeio/dedupe/files/5141696/OEM.xlsx)
[Partner.xlsx](https://github.com/dedupeio/dedupe/files/5141697/Partner.xlsx)

When providing my own training data, by specifying --skip_training True .Command used is (csvlink OEM.csv Partner.csv --field_names_1 ValueAddedReseller --field_names_2 AccountName  --skip_training True --training_file training.json --output_file output.csv ) .

Its throwing an error "UserWarning: Training data has records not known to the active learner. Read training in before initializing the active learner with the sample method, or use the prepare_training method."

Not sure how to solve it . And how to make both the samples generated and training file contain both the same records.
Kindly help

**Comment by fgregg** [comment]
Please open on the csvdedupe library. https://github.com/dedupeio/csvdedupe
