### ISSUE TITLE
AttributeError: 'StaticDedupe' object has no attribute 'match'

### ISSUE THREAD

**Issue by marianadpl** [dedupeio/dedupe#859]
I am getting this error now and it was working perfectly fine last month. Was there any updates?

I am using Python 3.7 from Anaconda

My dedupe is 2.0.6

The numpy version is 1.19.1 (I've read in Stackoverflow people having similar issues due to numpy version).

My pip version is 20.2.3. 

I saw in previous post the suggestion of using  import dedupe  dedupe.__file__ but also didn't work. 

Any sugestions of what else I could try?

**Comment by fjsj** [comment]
could you please post the full stacktrace and maybe your source code as well (or some similar code to reproduce the issue)?

**Comment by marianadpl** [comment]
Sorry about that. This is the bit of the code I am having issues. settings_file is a JSON file with the learned setting. 

CUSTOMER_SELECT="SELECT id, name_only, gender, dob, address, occupation, bank_acct_no FROM " + input_table

logger.info('Importing data from '+ input_table +' table ...')
c.execute(CUSTOMER_SELECT)
data = c.fetchall()
data_l = []
columns = tuple([d[0] for d in c.description] )
for row in data:
    data_l.append(dict(zip(columns, row)))
data_d = {}
for row in data_l:
            #clean_row = [(k, preProcess(v)) for (k, v) in row.items()]
            row_id = (row['id'])
            data_d[row_id] = dict(row)
			
logger.info(str(len(data_d)) + ' records imported')
data_l=[]
del data

if os.path.exists(settings_file):
    logger.info('Reading from ' + settings_file)
    with open(settings_file, 'rb') as sf :
        deduper = dedupe.StaticDedupe(sf)
else:
    fields = [
        {'field' : 'name_only','variable name': 'name', 'type': 'String'},
        {'field' : 'gender','variable name': 'gender', 'type': 'String', 'has missing':True},
        {'field' : 'dob','variable name': 'dob', 'type': 'String','has missing':True},
        {'field' : 'address','variable name': 'address', 'type': 'String', 'has missing':True},
        {'field' : 'occupation','variable name': 'occupation', 'type': 'String', 'has missing':True}, 
		{'field' : 'bank_acct_no','variable name': 'bank_acct_no', 'type': 'String', 'has missing':True}
        #{'type'  : 'Interaction', 'interaction variables' : ['name', 'address']},
        #{'type'  : 'Interaction', 'interaction variables' : ['name', 'dob']},
        #{'type'  : 'Interaction', 'interaction variables' : ['dob', 'address']},        
 
 ]
 
logger.info('Clustering.....')
**clustered_dupes = deduper.match(data_d, threshold=0.5)**
logger.info('Clustering completed')

**Comment by fjsj** [comment]
@marianadpl maybe you updated the library? Current version doesn't have the `match` method anymore. It's now called `partition`. See https://github.com/dedupeio/dedupe/blob/master/CHANGELOG.md#20

You can try to install the old version with `pip install "dedupe==1.10.0"` or update your code. Check the most recent [docs](https://docs.dedupe.io/en/latest/) and [examples](https://github.com/dedupeio/dedupe-examples).

**Comment by marianadpl** [comment]
@fjsj It worked! Thanks for that!
