### ISSUE TITLE
Dedupe 2.x not working on Windows Server 2016

### ISSUE THREAD

**Issue by CountRavoli** [dedupeio/dedupe#861]
When running the csv_example, it just stop doing anything after printing "clustering..."; No CPU usage, and never finishes.

It works fine when using any 1.x version (after changing the appropriate method names, etc)

Issue seen on:

- Windows Server 2016
- Python 3.8
- Dedupe 2.x

**Comment by fgregg** [comment]
We can add Windows Server 2016 to the appveyor build matrix. A PR to make this change would be welcome.

**Comment by fgregg** [comment]
actually, we are using github actions for our windows CI, and windows server 2016 is no longer supported.

https://github.blog/changelog/2019-10-31-github-actions-windows-server-2016-r2-virtual-environment-will-be-removed-on-november-7/

i'm sorry, but I don't think I'll be able to to sort out what's happening. if you do, a PR is certainly welcome.
