### ISSUE TITLE
add blog posts about dedupe to README

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#865]
- flavio's talk
- district data labs

**Comment by fgregg** [comment]
- https://www.youtube.com/watch?v=McsTWXeURhA&list=PLXiBVSVjkleVc7HyLAC6wDD31IrUO7eye
- https://medium.com/district-data-labs/basics-of-entity-resolution-with-python-and-dedupe-bc87440b64d4

**Comment by fritshermans** [comment]
I presented using Dedupe at scale in Spark at ING's data science meetup that you could consider adding as well; [youtube](https://youtu.be/q9HPUYmiwjE?t=2699)
