### ISSUE TITLE
sqlite based parallel processing

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#866]
right now, dedupe users can use parallel processing for comparing records.

however, much of the benefits of the parallel processing is lost because of the inter-process communication. 

1. The parent process creates a stream of record pairs to compare
2. The parent process chunks these streams and then puts these chunks into a queue
3. The worker picks up chunks from a queue and compares the records
4. The worker processors put the comparison scores into a queue
5. A collector process gets the scores from a queue and assembles them into a memmaped numpy array

Every time we hand off between processes, the data has to be serialized by the sender, transmitted, and deserialized by the receiver. 

This communication overhead can be quite high. Indeed, blocking which should be a very parallelizable task, is not worth parallelizing because the costs of communication overhead makes it not worth it #305, as @fjsj recently rediscovered.

However, as we have started to lean into sqlite, there are new opportunities for parallel processing with less communication.

Something like, 

1. parent process determines ranges of comparisons for different workers to take on (but not do the actually chunking). 
2. worker processes access the sqlite blocking table directly to get comparison pairs and compare them according the ranges passed to them
3. worker processes write directly to a memmaped numpy array

**Comment by fjsj** [comment]
I think the suggested approach looks great, I've implemented similar approaches, and they work well.
The key is avoiding the serialization / ipc overhead. It's best if the workers can get the records directly from DB. And writing in parallel to a single memmaped numpy array works well too.

On a related note, for ensuring best performance and memory/disk usage, it may be useful to require integer IDs. Looks like [str ids are still supported](https://github.com/dedupeio/dedupe/blob/add3e9cd587aa6a163cd7e7e34bead21958bff74/dedupe/core.py#L407).

**Comment by fgregg** [comment]
@fjsj have you implemented parallel writing to a numpy array that takes the place of [`mergeScores`](https://github.com/dedupeio/dedupe/blob/master/dedupe/core.py#L174-L212)?

**Comment by fjsj** [comment]
For another project, I've implemented a parallel process that saves results with `np.save` into multiple files. After all tasks are done, I concatenate all the files into a single memmaped numpy array. I think saving directly from the parallel tasks to the memmaped numpy array works fine. See: https://joblib.readthedocs.io/en/latest/auto_examples/parallel_memmap.html#writable-memmap-for-shared-memory-joblib-parallel
