### ISSUE TITLE
Ask for more information dynamically to increase confidence

### ISSUE THREAD

**Issue by guilhermecgs** [dedupeio/dedupe#871]
Hi folks, 

Lets assume a user is trying to perform a new registration and the backend answers that there is a 60% chance that this user already has an active registration based on its name, location, etc.

However, to avoid potentially creating a duplicated entry, I would like the backend to provide something like:  "If you ask the user it's age (or address or something else dynamically), I can with 100% confidence assert if it is the same user or not".

With this information, a new question on the UI appears asking the user to answer it.

Question:
1) What approach would you use?
2) Can I do something like this with this project?

**Comment by fgregg** [comment]
i would train a number of different models that did not did not include those models, and then compare there outputs
