### ISSUE TITLE
ImportError: DLL load failed while importing doublemetaphone: The specified module could not be found.

### ISSUE THREAD

**Issue by ollivar** [dedupeio/dedupe#873]
Hello,

I am using Python 3.8.3 on a Windows PC and I trying to run the examples from your git repo. After creating my virtual environment and attempting to run code from command line, I am getting the following error: ImportError: DLL load failed while importing doublemetaphone: The specified module could not be found. 

Any help or thoughts would be appreciated. Thank you!

**Comment by ollivar** [comment]
I was able to resolve the issue after creating a VM with Python 3.8.5.

**Comment by fgregg** [comment]
we have released a lot of binary wheels for metaphone, so hopefully this won't be an issue going forward
