### ISSUE TITLE
AttributeError: 'StaticDedupe' object has no attribute 'matchBlocks'

### ISSUE THREAD

**Issue by nrajasek1** [dedupeio/dedupe#875]
My code is failing with below error. i am trying to search in here to see any code i  need to install. can any one help me with the required libraries from where i can download 

  clustered_dupes = deduper.matchBlocks(candidates_gen(c_cluster),, threshold=0.5)

AttributeError: 'StaticDedupe' object has no attribute 'matchBlocks'

any help in this regard is much appriciated

**Comment by fgregg** [comment]
you are using an outdated version of the library. if you can't change your code, you'll need to use a version of dedupe earlier than 2.0
