### ISSUE TITLE
AttributeError: Attempting to block with an index predicate without indexing records

### ISSUE THREAD

**Issue by gbozzetti** [dedupeio/dedupe#879]
Hello,

I need a help with this error that I don't know how to fix, I'm following all the steps in the documentation but still the error shows up.

I'm using the RecordLink with the declared fields, my data_1 is a list movies' titles badly formatted and my data_2 is a list of movies' titles correctly formatted, the link between data_1 and data_2 is many-to-one, data_2 doesn't have duplicates.

What I'm doing is:

- dedupe.RecordLink(fields)
- prepare_training(data_1, data_2)
- mark_pairs(labeled_pairs) <-- here I'm passing a dict {"distinct": [ [{"title": "..."},{"title": "..."}] ], "match": [ [{"title": "..."},{"title": "..."}] ]}
- join(data_1, data_2, threshold=0.5, constraint='many-to-one')

the script runs outputting these logs:
`INFO:dedupe.canopy_index:Removing stop word e 
INFO:dedupe.canopy_index:Removing stop word  2
INFO:dedupe.canopy_index:Removing stop word 01
INFO:dedupe.canopy_index:Removing stop word 20
INFO:dedupe.training:Final predicate set:
INFO:dedupe.training:(SimplePredicate: (sameFiveCharStartPredicate, title), SimplePredicate: (tokenFieldPredicate, title))`

but after some seconds I get
`/lib/python3.8/site-packages/dedupe/predicates.py", line 239, in __call__
    raise AttributeError("Attempting to block with an index "
AttributeError: Attempting to block with an index predicate without indexing records`

What am I doing wrong?

Thank you for you help!

**Comment by fgregg** [comment]
i'm not sure. can you produce a reproducible example?
