### ISSUE TITLE
incorrect Cores value halts run without message

### ISSUE THREAD

**Issue by rderidder-lda** [dedupeio/dedupe#882]
Hello.. Sorry if this is vague - i'm a bit of a newbie.. but when trying to use dedupe on my python project on my computer, it was halting during the score call:
                clustered_dupes = deduper.cluster(deduper.score(record_pairs(cur2)), threshold=0.5)

i took this code basically directly from your mysql example.

there was no error / exception.. the run would just stop at that point, and my app would restart.

i narrowed it down to the earlier line where the number of cores are set:
            deduper = dedupe.Dedupe(fields, num_cores=4)

I changed the 4 to a 1, and it got past that issue.
So, just a suggestion to throw an exception if maybe the number of cores doesn't align well.

When i was stepping through the code, it got to popen_spawn_win32.py and halted at this line within Popen:
                hp, ht, pid, tid = _winapi.CreateProcess(
                    python_exe, cmd,
                    None, None, False, 0, env, None, None)
                _winapi.CloseHandle(ht)

**Comment by fgregg** [comment]
multiprocessing on windows can be pretty hard to debug, sorry. I have windows in the test matrix.
