### ISSUE TITLE
Why does Record Linkage in Dedupe.io give different cluster ID's for the matched records?

### ISSUE THREAD

**Issue by sindu0090** [dedupeio/dedupe#883]
Hi I have the following two files and I want to find the matches in between these two files. Every record in Test1.csv can match at most one record from Test2.csv, but more than one record from Test1.csv can match to the same record in Test2.csv. I am matching on the name and the domainWithExtension column.

Test1.csv

ID | accountid | name | domainWithExtension
-- | -- | -- | --
1 | 132 | Boxaround | boxaround.nl
2 | 343 | Calsoft Systems USA | calsoft.on
3 | 2342 | VillaMokka APS | mokka.con
4 | 45 | Balance.as | balance.as
5 | 45 | Cofemel - Sociedade De VestuÃrio S.A. | lkt.in
6 | 23 | lolson | lolson.in
7 | 3 | Boxaround | boxaround.nl

Test2.csv

ID | accountid | name | domainWithExtension
-- | -- | -- | --
1 | 3453 | Boxaround | boxaround.nl
2 | 6456 | Calsoft Systems USA | calsoft.on
3 | 77 | Octopus | octopus.on
4 | 444 | Balance.as | balance.as
5 | 36 | Cofemel - Sociedade De VestuÃrio S.A. | lkt.in
6 | 22 | GBH Communication | calsoft.on

`
import csv
import re
import logging
import optparse

import dedupe
from unidecode import unidecode

def preProcess(column):
  column = unidecode(column)
  column = re.sub('\n', ' ', column)
  column = re.sub('-', '', column)
  column = re.sub('/', ' ', column)
  column = re.sub("'", '', column)
  column = re.sub(",", '', column)
  column = re.sub(":", ' ', column)
  column = re.sub('  +', ' ', column)
  column = column.strip().strip('"').strip("'").lower().strip()
  if not column:
      column = None
  return column

def readData(filename):
  """
  Read in our data from a CSV file and create a dictionary of records,
  where the key is a unique record ID.
  """

  data_d = {}
  with open(filename,encoding='utf-8') as f:
      reader = csv.DictReader(f)
      for i, row in enumerate(reader):
          clean_row = dict([(k, preProcess(v)) for (k, v) in row.items()])
          data_d[filename + str(i)] = dict(clean_row)

  return data_d

if __name__ == '__main__':

  optp = optparse.OptionParser()
  optp.add_option('-v', '--verbose', dest='verbose', action='count',
                  help='Increase verbosity (specify multiple times for more)'
                  )
  (opts, args) = optp.parse_args()
  log_level = logging.WARNING
  if opts.verbose:
      if opts.verbose == 1:
          log_level = logging.INFO
      elif opts.verbose >= 2:
          log_level = logging.DEBUG
  logging.getLogger().setLevel(log_level)

  output_file = 'data_matching_output.csv'
  settings_file = 'data_matching_learned_settings'
  training_file = 'data_matching_training.json'

  left_file = 'Test1.csv'
  right_file = 'Test2.csv'

  print('importing data ...')
  data_1 = readData(left_file)
  data_2 = readData(right_file)

  if os.path.exists(settings_file):
      print('reading from', settings_file)
      with open(settings_file, 'rb') as sf:
          linker = dedupe.StaticRecordLink(sf)

  else:

      fields = [
                  {'field' : 'name', 'type': 'String', 'has missing': True},
                  {'field' : 'domainWithExtension', 'type': 'String', 'has missing': True},
              ]

      linker = dedupe.RecordLink(fields)

      if os.path.exists(training_file):
          print('reading labeled examples from ', training_file)
          with open(training_file) as tf:
              linker.prepare_training(data_1,
                                      data_2,
                                      training_file=tf,
                                      sample_size=15000)
      else:
          linker.prepare_training(data_1, data_2, sample_size=15000)

          print('starting active labeling...')

          dedupe.console_label(linker)

          linker.train()

          with open(training_file, 'w') as tf:
              linker.write_training(tf)

          with open(settings_file, 'wb') as sf:
              linker.write_settings(sf)

  print('clustering...')
  linked_records = linker.join(data_1, data_2, 0.5, constraint='many-to-one')
  print(linked_records)
  print('# duplicate sets', len(linked_records))

  cluster_membership = {}
  for cluster_id, (cluster, score) in enumerate(linked_records):
      for record_id in cluster:
          cluster_membership[record_id] = {'Cluster ID': cluster_id,
                                           'Link Score': score}
  print(cluster_membership)
  with open(output_file, 'w',encoding = "utf-8") as f:

      header_unwritten = True

      for fileno, filename in enumerate((left_file, right_file)):
          with open(filename,encoding = "utf-8") as f_input:
              reader = csv.DictReader(f_input)

              if header_unwritten:

                  fieldnames = (['Cluster ID', 'Link Score', 'source file'] +
                                reader.fieldnames)

                  writer = csv.DictWriter(f, fieldnames=fieldnames)
                  writer.writeheader()

                  header_unwritten = False

              for row_id, row in enumerate(reader):

                  record_id = filename + str(row_id)
                  cluster_details = cluster_membership.get(record_id, {})
                  row['source file'] = fileno
                  row.update(cluster_details)

                  writer.writerow(row)`

This works and gives the following result:

Cluster ID | Link Score | source file | ID | accountid | name | domainWithExtension
-- | -- | -- | -- | -- | -- | --
0 | 0.999996 | 0 | 1 | 132 | Boxaround | boxaround.nl
  |   |   |   |   |   |  
1 | 0.999996 | 0 | 2 | 343 | Calsoft Systems USA | calsoft.on
  |   | 0 | 3 | 2342 | VillaMokka APS | mokka.con
2 | 0.999996 | 0 | 4 | 45 | Balance.as | balance.as
3 | 0.999996 | 0 | 5 | 45 | Cofemel - Sociedade De VestuÃrio S.A. | lkt.in
  |   | 0 | 6 | 23 | lolson | lolson.in
4 | 0.999996 | 0 | 7 | 3 | Boxaround | boxaround.nl
4 | 0.999996 | 1 | 1 | 3453 | Boxaround | boxaround.nl
1 | 0.999996 | 1 | 2 | 6456 | Calsoft Systems USA | calsoft.on
  |   | 1 | 3 | 77 | Octopus | octopus.on
2 | 0.999996 | 1 | 4 | 444 | Balance.as | balance.as
3 | 0.999996 | 1 | 5 | 36 | Cofemel - Sociedade De VestuÃrio S.A. | lkt.in
  |   | 1 | 6 | 22 | GBH Communication | calsoft.on

The record for "Boxaround" appears in the Test1.csv twice. So I would expect both these records to be matched to the "Boxaround" record in Test2.csv and should have the same Cluster ID in the output however the cluster ID 4 in the output has two records and another one with Cluster ID 0 for "Boxaround". I want all three "Boxaround" records to have the same Cluster ID 4. How can I achieve this? Please help.

**Comment by fgregg** [comment]
use the Gazetteer class
