### ISSUE TITLE
Dependency on Levenshtein_search makes dedupe GPL 3-licensed

### ISSUE THREAD

**Issue by sarimak** [dedupeio/dedupe#885]
Dedupe is MIT-licensed but depends on GPL 3-licensed Levenshtein_search:
https://github.com/dedupeio/dedupe/blob/master/LICENSE
https://github.com/dedupeio/dedupe/blob/master/setup.py#L24
https://github.com/mattandahalfew/Levenshtein_search/blob/master/LICENSE

As a result all code that imports dedupe has to obey the limitations of distribution according to GPL 3 terms and unless the users do a recursive license check, they may be unintentionally violating GPL when re-distributing their code in good will.

Could you please find a way how to replace the dependency on a GPL library -perhaps https://github.com/toastdriven/pylev which uses 3-clause BSD could do the trick?

**Comment by sarimak** [comment]
Until now Levenshtein_search had broken PIP package metadata (no license) so the issue wasn't visible with reasonable effort. But with
https://github.com/mattandahalfew/Levenshtein_search/pull/22 which fixes the metadata, the license incompatibility is now visible.

**Comment by sarimak** [comment]
And in December 2019 the Levenshtein_search repo changed its license from MIT to GPL 3:
https://github.com/mattandahalfew/Levenshtein_search/commit/ed8c0f7f92381c337435a16438dc215a3cdb91ef#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

**Comment by fgregg** [comment]
The last version on pypi 1.4.5 is licensed as MIT. So, I can pin to that version

I've very much appreciated @mattandahalfew's library, and I'm sure he has his reasons for making this change.

**Comment by fgregg** [comment]
pinned now
