### ISSUE TITLE
Dedupe will not work on Python 3.10 due to deprecated sampling from a set

### ISSUE THREAD

**Issue by sarimak** [dedupeio/dedupe#890]
Our automated testsuite shows a deprecation warning when run with Python 3.9:
```
<my_venv>/lib/python3.9/site-packages/dedupe/sampling.py:207: DeprecationWarning: Sampling from a set deprecated since Python 3.9 and will be removed in a subsequent version.
    data_q = deque(random.sample(data.items(), len(data)))
```
The corresponding code can be found at https://github.com/dedupeio/dedupe/blob/19407578b4c123d004d09bf3c1b961e36f9e9a0c/dedupe/sampling.py#L207

I am not sure if the warning is indicating the silent conversion to a tuple as mentioned in https://bugs.python.org/issue42470 or if it is bogus and will go away with Python 3.10 thanks to the fix for this Python bug.

Our "data" argument is a Mapping[Union[int, str], Mapping[str, Any]] so it shouldn't be a Set[Any].

**Comment by fgregg** [comment]
this has not ended up being an issue
