### ISSUE TITLE
'StaticDedupe' object has no attribute 'prepare_training'

### ISSUE THREAD

**Issue by ML6634** [dedupeio/dedupe#892]
The code worked a few days. Now it produced a bug. Any comments? Thank you!

The code:

if os.path.exists(training_file):
    print('reading labeled examples from ', training_file)
    with open(training_file, 'rb') as f:
        deduper.prepare_training(dc, f)
else:
    deduper.prepare_training(dc)

The bug:

AttributeError                            Traceback (most recent call last)
<ipython-input-33-b0b3b889d95b> in <module>
     10         deduper.prepare_training(dc, f)
     11 else:
---> 12     deduper.prepare_training(dc)

AttributeError: 'StaticDedupe' object has no attribute 'prepare_training'

**Comment by fgregg** [comment]
StaticDedupe should not have a method to prepare training since you shouldn't use it for training.
