### ISSUE TITLE
Linking 2 dataset using RecordLink one to many relationship only one to one record

### ISSUE THREAD

**Issue by abttran** [dedupeio/dedupe#895]
I have 2 dataset , query input and query output.  On query term can have multiple query output, but when I try to link record using RecordLInk, it only yield one record from query input to query output.  I have tried one-to-one , many-to-one and many-to-many but it doesn't yield the data correctly.  Is it something I did wrong?

Thanks

**Comment by fgregg** [comment]
use the gazeteer class
