### ISSUE TITLE
High memory consumption of coveredPairs in DedupeBlockLearner class

### ISSUE THREAD

**Issue by ArVar** [dedupeio/dedupe#899]
The current implementation of `coveredPairs` uses `itertools.combinations` together with a custom enumerator. Apparently, all pairs in a block AND all blocks are kept in memory which leads to a (potentially unnecessary) huge memory consumption especially when large blocks are present. During the `prepare_training` process it is taking down my application due to memory errors on my machine with (considerably small) memory of 16 GB RAM. You can see a step function in my memory consumption.
I have tested with the mysql example (50k subset of the example data), the MemoryError appears at `pairs = frozenset(...)`

Shouldn't there be a way or workaround, to reduce this memory load e.g. by writing the pairs of a block sequentially to a database, eventually at the cost of speed? Is there something going wrong or is it working es expected and I need more memory?
Generally, I thought such an iterator construction is handling that for me. Did I have missed something?

**Comment by ArVar** [comment]
After some further investigation I found out, that `pair_enumerator` is aggregating a lot of data. Not sure, if this is intended. Deleting and refilling it might be a part of the solution.

**Comment by fgregg** [comment]
pair_enum could be replaced by a hash function.

this would lead to some imprecision, but would probably be fine with a large enough keyspace

**Comment by fgregg** [comment]
i would also add that if you pair_enumerator is truly the place that is taking up too much memory, you will certainly run into memory problems later

i would recommend passing in a random sample to prepare_training

**Comment by fgregg** [comment]
i will implement a pairing function for pair_enumerator

https://en.wikipedia.org/wiki/Pairing_function
