### ISSUE TITLE
Read about how random forests avoid overfit

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#901]
I think it's likely that there is something applicable here for blocking.

**Comment by stevetracvc** [comment]
I monkey patched the Matching.classifier to allow pretty much any sklearn classifier (I use RF) instead of the RegularizedLogisticRegression. I'm not a Python developer and my code probably looks like garbage, but let me know if you're interested.

**Comment by fgregg** [comment]
thanks @stevetracvc. i'm interested in learning about random forests because there are similarities between RF and how we learn blocking rules. that's separate from the classifier

**Comment by fgregg** [comment]
some ideas

1. constrain the number of total predicate rules we will allow in the final predicate set
2. only consider predicates that have some threshold over overall coverage (remove too precise predicate)
