### ISSUE TITLE
Why use different type's comparator in the same string have different compare order ?

### ISSUE THREAD

**Issue by svjack** [dedupeio/dedupe#903]
<img width="813" alt="截屏2021-07-15 上午6 00 43" src="https://user-images.githubusercontent.com/27874014/125698997-4e847201-63f6-4417-90bc-8314a7162856.png">
init same string text_a and text_b use "Text" comparator "CosineTextSimilarity" and "String" comparator "normalizedAffineGapDistance" respectively.
have:

cos(text_b, text_b) > cos(text_b, text_a)
AffGap(text_b, text_b) < AffGap(text_b, text_a)

this should have effect on combine different field's distance with weight if the weight can not choose negative value.
Can you explain this design for me ?

This make me confused when I use a fields which is a mixture of "String" type and "Text" type, they seems have opposite
effect on the final combine score.

**Comment by svjack** [comment]
I now know that Text and String comparators are in different level,  
You design think it is not suitable to use normalizedAffineGapDistance to compare sentence,
Are there any reason.
distance such as fuzzywuzzy seems works both ok on String (single token) and sentence (multi tokens joined)
Why not use a compatible measurement ?

**Comment by fgregg** [comment]
the weight *can* be negative
