### ISSUE TITLE
Can you add keyword predicate to Text Type or this kind interface to the framework?

### ISSUE THREAD

**Issue by svjack** [dedupeio/dedupe#905]
I find the character about this project is to use predicate to sample on data.
Can you make the sample interface more open to user that user can use this toolkit to 
sample data from the massive population.
The application scene is when i have massive text data, i want to customize some predicates.(as same sub categories)
And use them to sampling to construct a subset as your dedupeSamplePredicate do ?

Open the interface on new Variables will make this function convenient.

**Comment by fgregg** [comment]
not in project scope
