### ISSUE TITLE
Can you brief explain some logic that you use predicate in this project ?

### ISSUE THREAD

**Issue by svjack** [dedupeio/dedupe#906]
As i review the code, there are two kinds of predicates in your project.
One is some rule based predicates that have attribute “func” that can used 
to sample in dedupeBlockedSample (StringPredicate)

Others are predicates that have attribute “index” that can used for fingerprint
object to generate feature (tfidf related inherit from SearchPredicate that can call by target arguments
they may set to a collection named “index_predicates” that can used by learner
(and you also have a argument to switch is or not use these index_predicates by hasattr 
justification)

So i think the key point of downstream is the logic of BlockLearner use set (that’s why you need
features can hash)
record2 in cover function are indexed doc, so coverage between record1 and record2 as a pair sample
index filter that have intersection predicates values. i.e. coverage is a index collection have labeled
 related features.
and predicates to make predicate_cover that construct “encoded” coverable_dupes 

simple_candidates should be logic to make some sense of predicates related filtrate among 
match_cover (which always labeled in fit_transform and have predicated related in pair) 
and comparison_cover
they only have intersection part of predicates (because del key)
So you think these predicates as important predicates not only cover labeling set but among
pair 

In DedupeBlockLearner’s predict you use current_predicates justify pair predicates intersection (by intersection)
and this only related with blocker (which is only a rule based part of dedupe) these scores are 0-1 labels,
You merge these scores with rlr prob scores (trained by data model’s distance defined by Types) (concatenation)  use std to measure disagreements among rules and 
machine learning model 

Use mark to trigger the fit (transform) logic (with the match and random sample ratio as 4:1 in rule based 
active learning cls ) in prepare_training 

And call train to retrieve classifier and predicates for fingerprinter 
final use score product on distance from data model to clustering sample from duplicate or not.

Are their any omit key points ?

**Comment by fgregg** [comment]
this is covered in the documentation if there is a point that is unclear open an issue for that
