### ISSUE TITLE
Add match distinct difference validation interface to Dedupe after training

### ISSUE THREAD

**Issue by svjack** [dedupeio/dedupe#907]
I think it is important to add a validation interface between "match" and "distinct" after call "console_label"
and "train" method, because it will provide user a overview about the quality of fields setting (distance setting) and 
whether the amount of labeled data is sufficient to distinguish "match" and "distinct".

```py
def add_index_to_list(l2_list):
    index_d_dict = dict(enumerate(sorted(set(
        map(lambda d_: tuple(sorted(
            map(lambda t2: (t2[0],"" if t2[1] is None else t2[1])
                                        ,d_.items())
        )) ,reduce(lambda a, b: a + b, l2_list))
    ))))
    d_index_dict = dict(map(lambda t2: t2[::-1], index_d_dict.items()))
    req = []
    for left, right in l2_list:
        left_t, right_t = tuple(sorted(
        map(lambda t2: (t2[0],"" if t2[1] is None else t2[1])
                                        ,left.items())
        )), tuple(sorted(
        map(lambda t2: (t2[0],"" if t2[1] is None else t2[1])
                                        ,right.items())
        ))
        left_index, right_index = d_index_dict[left_t], d_index_dict[right_t]
        req.append(((left_index, left), (right_index, right)))
    return req

##### .score use trained classifier (use after train) 
def valid_deduper_match_distinct_difference(deduper):
    assert hasattr(deduper, "training_pairs")
    match_pair_with_index = add_index_to_list(deduper.training_pairs["match"])
    distinct_pair_with_index = add_index_to_list(deduper.training_pairs["distinct"])
    p_match_score = deduper.score(match_pair_with_index)
    p_distinct_score = deduper.score(distinct_pair_with_index)
    return pd.DataFrame(list(p_match_score)).iloc[:,0].map(lambda x: x[1]), pd.DataFrame(list(p_distinct_score)).iloc[:,0].map(lambda x: x[1])
```

call valid_deduper_match_distinct_difference above will retrieve score of labeled part (use None to compatible with has_missing in field)
if these two score distributions is difference, then the fields(distance) quality and the amount of labeled data are sufficient

for example, below figure of these two scores, indicate all sufficient
<img width="588" alt="截屏2021-07-17 下午7 39 18" src="https://user-images.githubusercontent.com/27874014/126035706-69061a60-3d80-49d6-afd8-eb7fd7c7481c.png">

And, below figure of these scores, say that the settings may be bad:
<img width="548" alt="截屏2021-07-17 下午7 40 08" src="https://user-images.githubusercontent.com/27874014/126035735-23017714-8a62-419b-a374-0eed1f0b251b.png">

Can you add these validation functions to the project ?

**Comment by fgregg** [comment]
not in scope
