### ISSUE TITLE
Squared Distances Recalculated Unnecessarily 

### ISSUE THREAD

**Issue by jhendr** [dedupeio/dedupe#911]
In [clustering.confidences](https://github.com/dedupeio/dedupe/blob/master/dedupe/clustering.py#L250) squared_distances is computed each time by squaring condensed_distances. However, confidences is called in a [loop](https://github.com/dedupeio/dedupe/blob/master/dedupe/clustering.py#L250) in which condensed_distances is unchanging. In the case where condensed_distances is large and there are a large number of small clusters (meaning many loop iterations) this can result in repeating that computation many times. In my use case squaring condensed_distances takes around 500ms, but is repeated around 50k times wasting hours of time.

This may be some or all of the problem described in https://github.com/dedupeio/dedupe/pull/880.

Will post a PR shortly...

**Comment by fgregg** [comment]
closed by #912
