### ISSUE TITLE
Getting PermissionError: [WinError 32] when trying to delete temporary mmap_file

### ISSUE THREAD

**Issue by robmcd** [dedupeio/dedupe#915]
```
Traceback (most recent call last):
  File "C:\Users\user\project\venv\lib\site-packages\dedupe\api.py", line 180, in partition
    os.remove(mmap_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmppdwxtjxk'
```
Seems similar to #604 

* Windows 10
* Python 3.7
* Dedupe 2.0.8

Sometimes if I re-run my code the error is avoided. But that's not a great workaround..

Sorry, i'm not very proficient in python so may not be much help diagnosing the issue. Just wondering if there are many others encountering the same.

**Comment by XavierRo** [comment]
Hello,
I have the same problem (Windows 10, python 3.9, dedupe 2.0.8).
First i try to change TMPDIR 
```
import os
os.environ["TMPDIR"] = "D:/Data/temp/dedupe"
```
No change, same problem.

I am not an expert in python nor in multiprocessing but by modifying the launch:
```
if __name__ == '__main__':
     freeze_support ()
    use_dedupe_function ()
```

it works

**Comment by fgregg** [comment]
because of the way multiprocessing works, you really always want to call the dedupe functions from within a "if __name__ == '__main__':"
