### ISSUE TITLE
Is there a way to specify which predicate(s) you want to use for blocking (instead of letting the model learn it/them)?

### ISSUE THREAD

**Issue by arnaudsj** [dedupeio/dedupe#916]
Hi,

I  would like to be able to specify a particular predicate for the model to use, is there a way to overwrite this easily? I looked in the code, and I could not find it after a quick glance. 

The issue I am trying to avoid is learning tons of predicates (I have many fields), which I know won't help for the data I am attempting to deduplicate. the other issue I have seen is overfitting the predicate learner, and ending up with no records in any blocks in the larger dataset.

Thank you in advance, and thank you for the great work with this library!

**Comment by fgregg** [comment]
There are no real interfaces for this, no. 

I'm working on some approaches to address overfitting, but that will take some time to land.

It might also be a good idea to add an argument to the data models to tell Dedupe to not use a field for blocking.

**Comment by arnaudsj** [comment]
Thank you @fgregg for the input. I just wanted to double-check before starting to put something together to get around this current limitation.
