### ISSUE TITLE
Tweak parameters for dealing with couples

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#918]
Hi! First of all, thank you for this excellent library. I just have a question on how to tweak the variable types. I understand that you sell this consulting as part of dedupe.io, so feel free to tell me to pay you for the help :)

I'm using it to duplicate campaign donation data, which contains name and address information. Many of the donations are from couples, so that all fields are very similar except for the first name. I'd like to split these couples up as two different entries. Any tips for what variables or interactions or custom metrics I should use to accomplish this? Thank you!

**Comment by fgregg** [comment]
Are you saying both first name appear in the name field?
