### ISSUE TITLE
Out of memory when training Dedupe object

### ISSUE THREAD

**Issue by XH42** [dedupeio/dedupe#920]
Hi,

I'm trying to train a Dedupe object on a dataset composed of 1.5M records representing worldwide businesses.

I set up 12 fields, all with possible missing values, among which : 
* 2 are of type String
  * `name` and `street`
* 10 are of type ShortString

I followed the [pgsql_big_dedupe_example](https://github.com/dedupeio/dedupe-examples/blob/master/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py) to setup the process. I understand that for bigger dataset, we are supposed to use PostgreSQL as a backend.

However, for the training part, I did not see any use of the database. In the example, the whole dataset is fed directly to the `prepare_training` method, so that's what I did.

However, the program runs for some time, approximately 10 minutes, and then gets killed running out of memory. Hardware has 16GB of free memory. 

The bottleneck is the `coveredPairs` static method of the `DedupeBlockLearner` class.
I ran some memory consumption, and basically, what happens is that some predicates cover a considerable amount of pairs, which leads to a bump in memory consumption. Here is a table of the top 10 of the most memory intensive predicate :
| memory\_usage (MB) | memory\_increase (MB) | len(pairs) | predicate                                      |
| ------------------ | --------------------- | ---------- | ---------------------------------------------- |
| 13036.908          | 1267.988              | 12104952   | LevenshteinCanopyPredicate: (2, country\_code) |
| 9398.288           | 1259.052              | 11568838   | ExistsPredicate: (Exists, phone)               |
| 7256.24            | 1250.78               | 12451282   | LevenshteinCanopyPredicate: (3, country\_code) |
| 5091.304           | 1236.792              | 11759700   | ExistsPredicate: (Exists, city)                |
| 11518.504          | 1205.652              | 12451282   | LevenshteinCanopyPredicate: (4, country\_code) |
| 5985.912           | 731.432000000001      | 10033813   | ExistsPredicate: (Exists, post\_code)          |
| 8134.224           | 726.796               | 9411570    | ExistsPredicate: (Exists, name)                |
| 10312.852          | 639.276000000002      | 6537642    | ExistsPredicate: (Exists, fax)                 |

So, is this a bug or a limitation ?

* It may be a misunderstanding of the API, in this case am I supposed to pass the whole 1.5M rows or a random sample ? I did not see any information regarding that particular point in the documentation.
* I could increase the amount of memory available, but that does not seem like a good solution if the length of the dataset to process increase by 10 for instance.
* The `country_code` field is defined as a `ShortString`,[ so it should not try to learn canopy predicate for this field](https://docs.dedupe.io/en/latest/Variable-definition.html#shortstring-types)

Thanks

**Comment by fgregg** [comment]
Use a sample of your records, and feed that to prepare_training
