### ISSUE TITLE
[Question] Can I emphasize prefix match?

### ISSUE THREAD

**Issue by qkhanhpro** [dedupeio/dedupe#921]
Hi. I am using dedupe's partitioning function and I my dataset is heavily skewed toward those with same prefix belong to the same group.

Can I ask if there is a method to emphasize the importance of prefix or the starting porpotion of the strings?

**Comment by qkhanhpro** [comment]
Hi @fgregg  I mean that we have different prefix like

company A
company B
company C

storage A
storage B
storage C

country A
country B
country C

Can I skew more toward those with common prefixes being into the same partition? I try to search something like that in the document but I cant find

Thank you a lot!

**Comment by NickCrews** [comment]
@qkhanhpro For your example, @fgregg is saying split that field into two fields:

One field would be
```
company
company
company
storage
storage
storage
country
country
country
```
and the other would be
```
A
B
C
A
B
C
A
B
C
```
And you create a variable for each of these fields (perhaps `ShortString` and `ShortString`), and then perhaps, depending on the context, create an `InteractionVariable` between them.

Does that make sense?
