### ISSUE TITLE
record linkage in a "runtime" process

### ISSUE THREAD

**Issue by cragia** [dedupeio/dedupe#923]
Hello to everyone.
I'm looking to using the dedupe library to do some deduplication + record linkage.
In particular, my scenario is this: I have multiple sources for profiles, and so I collect all the different profiles from all the sources, and I deduplicate them inside that source, and then I need to link across the different sources to generate some "cleaned and unique" profiles.
Now, for each source I have the first BULK upload, in which I want to use dedupe to be able to test the similarity of the profiles. And I guess that's ok. BUT, after the bulk upload, the sources continue to create profiles, so I continuously getting one profile at a time, and I need to link it to a similar profile (if there is one) in my database. But you can understand that if I have already hundred of thousands profiles in my database already, I cannot every time load the entire database to be able to do record linkage... is there a way to interface directly with a database? without getting all the profiles every time?

thank you,
Giacomo.

**Comment by fgregg** [comment]
checkout out https://github.com/dedupeio/dedupe-examples#postgresql-big-dedupe-example---postgresql-example-on-large-dataset
