### ISSUE TITLE
deduper._sample memory issues for large dataset

### ISSUE THREAD

**Issue by shoaibazeemsiddique** [dedupeio/dedupe#924]
Hi

We have a huge dataset, roughly 2.1M rows. We are using api._sample methods to generate the samples. As api._sample requires a dictionary object which should contain the whole dataset. Considering the size of the data we are not able to load the full dataset in the dictionary object (getting memory failures). 

-What could be the possible solution for it? 
-Can we use some other sampling library and pass its results to the deduper library of labelling and deduplication?

Thanks
SS

**Comment by fgregg** [comment]
yes, you can generate a sample in another way and pass it on.
