### ISSUE TITLE
Unable to use custom separators in partitioning data

### ISSUE THREAD

**Issue by nangokosu** [dedupeio/dedupe#927]
I followed the instructions in the Dedupe documentation for implementing Custom Separators in my training. Everything went smoothly, and I was able to finish the active training portion, write the training and settings files. However, when I went to partition the data based on the training using deduper.partition(), I get " Can't get attribute 'fuzzy_token_sort_ratio' on <module '__main__' (built-in)>", where fuzzy_token_sort_ratio is the name of one of my custom separators used for training. There is no documentation on how I can pass the custom separators into the partitioning phase.

**Comment by fgregg** [comment]
i suspect it's a pickling issue. please provide a reproducible script.

**Comment by fgregg** [comment]
closing for now. please reopen if you can provide reproducible example
