### ISSUE TITLE
Conflict resolution for one-to-one matching

### ISSUE THREAD

**Issue by lucasmalherbe** [dedupeio/dedupe#928]
In a record linkage use case, how does dedupe resolve conflicts when the "one-to-one" option si chosen?

Suppose you have two files with to records each and the following probabilities predicted by dedupe.

| File A | File B | Probability |
|--------|--------|-------------|
| a1     | b1     | 0.95        |
| a2     | b1     | 0.90        |
| a1     | b2     | 0.70        |

With a threshold of 0.5, which pairs are going to be ones and which pairs are going to be zeroes? You can't put 1 for the three pairs, otherwise it's not a one-to-one match anymore. So what's the process for deciding such cases?

**Comment by fgregg** [comment]
the highest scoring matc, so a1-b1 will match
