### ISSUE TITLE
Train deduper from labeled dataset

### ISSUE THREAD

**Issue by cbhower** [dedupeio/dedupe#933]
Thanks for your hard work on this package! I apologize if this has been asked before. I've seen similar questions but not this exact question.

I want to train a classifier from an existing labeled dataset. I have shaped the data as needed for mark_pairs() but when I try to run the train method I get the error:

  File "/.../src/handlers/run_deduplication.py", line 32, in train
    deduper.train()
  File "/.../venv/lib/python3.8/site-packages/dedupe/api.py", line 1052, in train
    assert self.active_learner is not None, \
AssertionError: Please initialize with the sample method

The code works as follows:

deduper = dedupe.Dedupe(fields) # this code works fine
deduper.mark_pairs(training_data) # this code works fine
deduper.train() # error is here

What are the correct steps after deduper.mark_pairs() and before deduper.train()? What method will set the self.active_learning attribute to not none? I've gone through the docs and source code but still haven't managed to find the right approach. Eventually, I would like to use active learning to enhance my training but getting my existing labeled training set to work would be a great start.

Thanks again!

**Comment by fgregg** [comment]
you need to also call the [`prepare_training`](https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.Dedupe.prepare_training) method

**Comment by fgregg** [comment]
this may a useful reference https://github.com/dedupeio/dedupe/blob/master/tests/canonical.py#L91-L94

**Comment by cbhower** [comment]
Hi @fgregg Thank you for the response! I did try this but I still couldn't get it to work. As a workaround, I have been saving my pre labeled set as a json file and loading it as a training_file in prepare_prepare_training(). Here I am bypassing the active learning and just training with existing labeled set I already have. 

The problem now is that increasing the size of the labeled dataset does not scale well. Load time and training time are extremely long with 5k pre-labeled pairs of data. How can I improve performance? would loading the data with mark_pairs be more efficient? I have a dataset with ~ 40k labeled pairs and would like to use this package with a database with ~700k observations. If this is off topic I can create a new issue.

**Comment by fgregg** [comment]
that's a great way to do it. 

as far as performance with large data, you can open a new issue.
