### ISSUE TITLE
Memory is maxing out when building an index in deduper.fingerprinter.index()

### ISSUE THREAD

**Issue by ronbeltran** [dedupeio/dedupe#941]
First of all, thank you for this wonderful library. I have followed this big data example however my script is maxing out/crashing our server environment. The culprit i believe is in the indexing of learned "Index Predicate" and building the indices. Specifically in this line:

https://github.com/dedupeio/dedupe-examples/blob/master/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py#L231

Question: Can we limit (ie. SELECT DISTINCT {field} FROM {tablename} LIMIT {limit}) the distinct field values in this line before feeding it to deduper.fingerprinter.index() 

https://github.com/dedupeio/dedupe-examples/blob/master/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py#L229

If so, will this have any effect of the results of the dedupe? For context, we have 16M records to dedupe. Any tips will be much appreciated. Thanks!

**Comment by fgregg** [comment]
the indexes are all memory, so if you want to avoid this problem, turn off index predicates.

**Comment by ronbeltran** [comment]
https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.Dedupe.train
    
    deduper.train(index_predicates=False)

This is confirmed. Deduper runs fine without the index predicates.
