### ISSUE TITLE
Dedupe errors out with sqlite3.OperationalError: database or disk is full when running join on 1.4 mil rows data

### ISSUE THREAD

**Issue by sunil-varicent** [dedupeio/dedupe#942]
When linker join method is called like this: 

`self.__linker.join(data.data_left, data.data_right, 0.0, constraint='many-to-one')`

with 1.4 mil rows of data, after approx an hour it errors out with such error:

`con.executemany(\"INSERT INTO blocking_map_a values (?, ?)\",\n\nsqlite3.OperationalError: database or disk is full\n`

The disk volume size is 30GB, /tmp folder is mapped to same volume. Instead of increasing disk size, we are trying to find a way to incrementally join the data, so that we can scale the solution to bigger size of input data. We tried to split the large data set into batches and join the batch individually. Even linker object is created for each batch from saved settings. Sample code of batching:

```
                           for item in split_dict(data.data_left, batchSize):
				new_linker = self.__getLinker()
				linked_records_chunks = new_linker.join(item, data.data_right, 0.0, constraint='many-to-one')
				linked_records.extend(linked_records_chunks)
				new_linker = None

def __getLinker(self):
		current_state = self.__dict__.copy()
		with io.BytesIO(current_state['settings']) as setting_bytes:
			return dedupe.StaticRecordLink(setting_bytes)
```

But even with batchin (10K rows of batch size), it fails with same out of disk error.

It would be greatly appreciated if we could get some pointer to make the dedupe work with large number of input data without getting out of disk error. Is there a way we can make dedupe cleanup disk after each join in batches?

**Comment by fgregg** [comment]
if you are using the many-to-one matching you could use the Gazetteer class
