### ISSUE TITLE
prepare_training method breaks when the training file contains list data

### ISSUE THREAD

**Issue by tonca** [dedupeio/dedupe#943]
**Environment**:
Python 3.8.10
dedupe 2.0.8

**What happens**:
When I try to load a previously saved training file with the method `prepare_training` on a linker object `dedupe.Dedupe`, which contain items with array fields (JSON lists), a type error is thrown:
```
TypeError: unhashable type: 'list'
```
This also happens if I try to add pairs (containing list fields) to the linker and then run the method `prepare_training`

**How to reproduce**:
1. Clone the repository `dedupeio/dedupe-examples`
2. Run the script `patent_example/patent_example.py` in the repo for a first time and complete some of the active training labeling questions
3. Delete the file `patsat_settings.json`, in order to avoid the static linker loading
4. Run the script once more

The above error will be thrown at line 137, where the `prepare_training` method is used to load the `patsat_training.json` file into the linker.

**Possible causes and solutions:**
The source of the error is line 276 in file `dedupe/labeler.py`:
```
unique_fields = {record[field] for record in records}
```
From what I can understand we are trying to access each single field in the records, however, somehow the field key passed is a list. This is strange, because the object it comes from (`blocker.index_fields` from line 275 ) should be a dictionary, therefore its keys should be hashable.

**Comment by fgregg** [comment]
the problem was that the tuples were not getting serialized to json correctly. unfortunately, you'll need to delete your training json file and start over once. after that it should be fine.

**Comment by tonca** [comment]
It is not a problem to delete the training file.
How can I serialize it differently, other than using the `write_training` method? That's not clear to me.

**Comment by tonca** [comment]
Ok sorry, I just saw the new release! 
Wow so quick! Thank you!
