### ISSUE TITLE
Run dedupe on million of rows

### ISSUE THREAD

**Issue by ronbeltran** [dedupeio/dedupe#947]
Hi,

I had implemented dedupe script based on the postgres example https://github.com/dedupeio/dedupe-examples/blob/master/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py. I had turned off index predicates and it seems to work fine for 100k rows/records. What are the steps to make it work with 20M rows/records?

**Comment by fgregg** [comment]
give it 20M rows
