### ISSUE TITLE
sample_size 

### ISSUE THREAD

**Issue by az0** [dedupeio/dedupe#955]
https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.RecordLink.prepare_training
function signature shows default is 15000 while text states 150,000
![image](https://user-images.githubusercontent.com/933680/152438845-4af71055-3f97-4819-be8a-822dd4d9e2ea.png)

Same here
https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.Gazetteer.prepare_training

This one doesn't indicate the default value in the text.
https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.Dedupe.prepare_training

It is redundant to have it in the text, so I wouldn't mention it.

By the way, is there any general advice on sample size? This would be helpful to have in the documentation. While updating from dedupe 1.9 to 2.0, my learning settings file blew up from 16,641B to 613,513 KB while changing sample_size from 10000 to 15000. Training is slow, even with small sample sizes.

**Comment by fgregg** [comment]
thanks! i think something else is going with the size of the settings file and slow training.

How many records are in your training data? The slow training might be related to #940

**Comment by az0** [comment]
>thanks! i think something else is going with the size of the settings file and slow training.

Should I open a separate issue?

>How many records are in your training data? The slow training might be related to https://github.com/dedupeio/dedupe/issues/940

Full training is 9,369 match vs. 7,064 distinct, but since updating to dedupe 2, I started sampling the training to speed things up. 

My last run was 

Training: 2,000 match vs. 2,000 distinct
prepare_training(sample_size=15000) took 10 minutes
train() took 5 minutes
settings file was 193,312,682B

**Comment by fgregg** [comment]
i think i've already addressed the big settings file. can you pull from master?

as for the slow training, it sounds like #940. could you add to that issue? Particularly if you have training data you can share.
