### ISSUE TITLE
Very long clustering / very large block 

### ISSUE THREAD

**Issue by ronbeltran** [dedupeio/dedupe#958]
Good day, This is regarding https://github.com/dedupeio/dedupe/issues/671.

What could be the solution when you ran into a very large block big enough to maxed out the machine resources (ie. disk space or RAM) on clustering deduper.cluster() step. Is there any settings in dedupe api that set limits to how big large blocks can be generated. Thank you in advance.

**Comment by fgregg** [comment]
by default, dedupe doesn't filter out any of the record pairs by score before passing to cluster. it will likely be profitable to filter out low score pairs.

**Comment by ronbeltran** [comment]
Thank you @fgregg. I will be exploring this possible solution.
