### ISSUE TITLE
Too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by rahullak** [dedupeio/dedupe#960]
When trying to mark_pairs using labeled examples (which contain LatLong field), I am getting the following error:

`
labeled_examples={'match': [],
 'distinct': [({'AddressExtraCleanID': 'ID1',
    'CountryName': 'SW',
    'New_City': 'K',
    'New_PostCode': '999 40',
    'POBox': None,
    'New_Street': 'KLLL',
    'LatLong': (89.403866, 99.945303)},
   {'AddressExtraCleanID': 'ID2',
    'CountryName': 'SW',
    'New_City': 'K',
    'New_PostCode': None,
    'POBox': None,
    'New_Street': 'LMMM',
    'LatLong': (89.403971, 99.948227)})]}

deduper.mark_pairs(labeled_examples)`

ValueError: too many values to unpack (expected 2)

/python/lib/python3.8/site-packages/haversine/haversine.py in haversine(point1, point2, unit)
     86 
     87     # unpack latitude/longitude
---> 88     lat1, lng1 = point1
     89     lat2, lng2 = point2
     90 

Please help. @fgregg

**Comment by NickCrews** [comment]
If you can provide minimum, fully reproducible script (that I can just copy paste), then I can help investigate @rahullak

**Comment by rahullak** [comment]
@NickCrews 
Hello, I created and ran the reproducible script today and it worked! Then I ran my original script again and that also worked without any modifications! Not sure what went wrong the previous times.

Sorry, and thanks for offering to help!

**Comment by NickCrews** [comment]
Yay! Thanks and nice job @rahullak !
