### ISSUE TITLE
Explore `shelve` for connected components dict

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#966]
If the connected components dict in `clustering.union_find()` is running us out of memory, maybe we can use https://docs.python.org/3/library/shelve.html as a disk-based dictionary?

**Comment by fgregg** [comment]
i think it's worth a look, but when we looked at shelve before for other purposes in the library it was surprisingly slow.

**Comment by NickCrews** [comment]
Good to know. I'd say reopen if we add profiling as in https://github.com/dedupeio/dedupe/issues/967 and see that this actually is a bottleneck.
