### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by NickCrews** [dedupeio/dedupe#967]
Branched off of https://github.com/dedupeio/dedupe/issues/965#issuecomment-1046319666.

EDIT: See next comment for using ASV instead of @profile

Place @profile decorators on bottleneck functions using `memory_profiler`

List this dependency as extra, so that most users don't need to install it.

Also, to prevent overhead from @profile getting run always (even when we don't want profiling), wrap it in our own custom decorator that is usually a noop:

```python
def dd_profile(func, *args, **kwargs):
    # Maybe a better way to configure this? Would have to be at import time
    if os.environ["DEDUPE_PROFILE"]:
        # Actually add the profiler wrapper
        return profile(func, *args, **kwargs)
    else:
        # noop
        return func
```

Next steps are to probably actually make a new branch and apply it to some of the examples?

**Comment by NickCrews** [comment]
OK, I think a better option is [Air Speed Velocity](https://asv.readthedocs.io/en/stable/index.html).

- Don't have to modify the codebase at all, benchmarks are separate, like tests
- measure time, memory, and custom attributes (eg we could measure accuracy)
- used by big names like numpy, pandas, scipy
- See examples at that link of static websites, it has built in support for github pages
- Could run on every PR, or could trigger only when we care from a comment like `@benchmark main..HEAD --bench benchmarks.TimeSuite.time_range` [as pandas does](https://github.com/pandas-dev/pandas/blob/1951dd70dee5df23cc85e09d44f745bc3e724dcd/.github/workflows/asv-bot.yml)

Initially, I would think that we would get a lot of value out of measuring
- time
- peak memory
- accuracy
on just one or two end-to-end runs (training and evaluating separate). Either could use [the test datasets](https://github.com/dedupeio/dedupe/tree/master/tests/datasets), or could use the examples from [dedupe examples](https://github.com/dedupeio/dedupe-examples)

One tricky thing would be to decide how to store [the results](https://asv.readthedocs.io/en/stable/using.html#benchmarking) (eg the metrics collected from past runs). Would want a way to ensure a consistent machine (using github actions? and/or with docker?). Keep the results in this repo, or keep them in a separate repo, possibly using submodules as they mention?

@fgregg @fjsj any thoughts here?

**Comment by fgregg** [comment]
I love this ides @NickCrews . if you want to try to get something rough and ready set up, i think that would a really good step forward. if it's looking very valuable, then we will figure out the tricky bits.

**Comment by NickCrews** [comment]
Cool, it might be a bit, but I will try to get to this.

I'll start with the benchmarks in this repo, as those other packages do. Will try to start out without the stored state of past metrics. Will make the decision at game time of which example data to use, haven't explored enough yet to see which I like better.

**Comment by NickCrews** [comment]
@fgregg @fjsj  I'm not well versed in entity resolution, any suggestions on what metrics I should use for "accuracy"? Based on the abstract of https://arxiv.org/abs/1509.04238 (didn't read it yet as I thought maybe you'd have pointers) it sounds like the standard measures like F score and precision might need to get tweaked a little bit

**Comment by fgregg** [comment]
i think precision and recall are really still the best ones.

**Comment by fgregg** [comment]
look at canonical.py in tests to see how precision and recall is calculated there.
