### ISSUE TITLE
AttributeError: 'Dedupe' object has no attribute 'prepare_training'

### ISSUE THREAD

**Issue by XueXue0916** [dedupeio/dedupe#972]
Dear dedupe team: 

When I use Depupe packages, it occurs AttributeError, and I don't know how to fix that：AttributeError: 'Dedupe' object has no attribute 'prepare_training'. I guess it's the version problem! Can you help me to fix this problem? Thank you very much. 

Here is the version of the packages: 

dedupe                    1.9.7                  
dedupe-hcluster           0.3.9                   
dedupe-variable-datetime  0.1.5 
Unidecode                 0.04.16
future                    0.18.2

I am looking forward to your reply.

Best 
Xue

**Comment by fgregg** [comment]
you are running a version of python that does not have the prepare_training method . either upgrade dedupe or adapt your script
