### ISSUE TITLE
Target in Predicate Search Not clear

### ISSUE THREAD

**Issue by NeverInAsh** [dedupeio/dedupe#979]
In the `Fingerprinter ` class object we have the option to pass `target`. But the documentation mentions that there is no loss of accuracy if this is set to default. Can somebody please explain then why target = True is not the default option , if the calculations can be fast as well as accurate at the same time.

**Comment by fgregg** [comment]
because it is only usable when you are linking two datasets. one can be the target, the other will not be. if you are deduping a single dataset, this option does not make sense.
