### ISSUE TITLE
treat "unsure" as yes

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#984]

**Comment by NickCrews** [comment]
Can you elaborate a little more? Just to make the code for console labeling simpler? Or does this actually improve matching performance (better to err on the side of it being a match)? At this point, in my use, when I'm labeling, should I just always say "yes" when I'm tempted to say "unsure"?

**Comment by fgregg** [comment]
I saw a presentation on record linkage that compared human reviewers and a ground-truth mechanism, and the main difference in the the ground-truth performance was that humans are much to conservative in accepting matches.

**Comment by NickCrews** [comment]
Awesome, thanks! Think the end goal should be to remove "unsure" from the UI, or should keep it in the UI and just treat it as "yes" under the hood. The second is a bit disingenuous, but per what you just said, it might actually lead to better performance in actual use. Could mention a note that says "If you're unsure, just say yes", but that might not be seen.

**Comment by fgregg** [comment]
I'm thinking of the second option (lying to people), with a flag that people can set if they really don't want that behavior. The more sophsticated thing would be to give it a "half label" or, equivalently add the record as both a positive and as a negative.

**Comment by fgregg** [comment]
Actually, i like the idea of adding it as both a positive and negative.

**Comment by NickCrews** [comment]
Adding as both seems reasonable, what are the implications of that?
- Still will learn a blocking rule for it (good)
- Won't affect weights of the learner as they will cancel each other out (good)
- ???

**Comment by fgregg** [comment]
if ever introduce sample weights, it could be good to give each of the duplicated records a half weight. i think this is a solid idea to try out!

**Comment by NickCrews** [comment]
> if ever introduce sample weights, it could be good to give each of the duplicated records a half weight.

hmmm I see what you mean. Does bring up the question of what is "half weight". I would assume that it would be an option to assign arbitrary weights to samples (ie range [0, inf]), so if you said unsure, does that mean just divide the initial weight in half?

Did I miss any other implications that are important?

> in the meantime, i think this is a solid idea to try out!

Cool, this seems like it would be really easy to implement, just change the behavior in [console_label()](https://github.com/dedupeio/dedupe/blob/c2ac55932930591ccfdbce650f66715a52425c36/dedupe/convenience.py#L179), right? Nowhere else to worry about?

**Comment by fgregg** [comment]
> does that mean just divide the initial weight in half?

i think so, yes.



> Did I miss any other implications that are important?

i think it's not quite right that it leaves classifier weights unaffected. it will tend to drive the classifier towards prediction 0.5. (which is good!!)

**Comment by NickCrews** [comment]
Check out #994 when you get the chance! :)

**Comment by NickCrews** [comment]
> i think it's not quite right that it leaves classifier weights unaffected. it will tend to drive the classifier towards predicting 0.5. (which is good!!)

Yes, that makes sense, thanks
