### ISSUE TITLE
KeyError caused by core.randomPairs for datasets >= ~66k records

### ISSUE THREAD

**Issue by JM-Pittman** [dedupeio/dedupe#986]
Environment:
Windows 10
Anaconda 2020.02
Numpy 1.22.2
Python 3.8.12
dedupe 2.0.13

The KeyError identified in #945 and marked resolved by #954, persists for larger datasets. Based on some sensitivity testing, ~66k records seems to be the magic number for recreating the issue. I have found this to be the case with my own datasets, and produced the below stack trace using the csv example dataset from dedupe-examples that I concatenated with itself multiple times to get to the requisite number of rows.

Traceback (most recent call last):
  File "C:\\...\deduping_model\alpha_0\alpha_0_model_training.py", line 85, in <module>
    deduper.prepare_training(data_clean)
  File "C:\Anaconda\envs\care\lib\site-packages\dedupe\api.py", line 1298, in prepare_training        
    self._sample(data, sample_size, blocked_proportion)
  File "C:\Anaconda\envs\care\lib\site-packages\dedupe\api.py", line 1324, in _sample
    self.active_learner = self.ActiveLearner(self.data_model,
  File "C:\Anaconda\envs\care\lib\site-packages\dedupe\labeler.py", line 421, in __init__
    self.candidates = self._sample(data, blocked_proportion, sample_size)
  File "C:\Anaconda\envs\care\lib\site-packages\dedupe\labeler.py", line 59, in _sample
    return [(data[k1], data[k2])
  File "C:\Anaconda\envs\care\lib\site-packages\dedupe\labeler.py", line 59, in <listcomp>
    return [(data[k1], data[k2])
KeyError: 2147556154

**Comment by JM-Pittman** [comment]
I've been able to isolate the issue to the typecasting to `numpy.uint` in the `core.randomPairs()` . The following code snippet will demonstrate the error in randomPairs:
```
import random
import numpy

def test_randomPairs(n_records_list: list, sample_size=15000):
    
    test_results = []
    for n_records in n_records_list:
        n = n_records * (n_records -1) // 2
        random_pairs = numpy.array(random.sample(range(n), sample_size), dtype=numpy.uint)
        b = 1 - 2 * n_records
        i = (-b - 2 * numpy.sqrt(2*(n-random_pairs) + .25)) // 2
        i = i.astype(numpy.uint)
        j = random_pairs + i * (b + i + 2) // 2+1
        j = j.astype(numpy.uint)
        tmp = {'n_records': n_records, 'n': n, 'max_i': max(i), 'max_j': max(j)}
        test_results.append(tmp)
    
    return test_results

test_list = [1000, 30000, 60000, 66000, 80000]
results = test_randomPairs(test_list)
```
The problematic indices are isolated to the `j` array and starting with `n_records = 66000` grow larger than `n_records`.

At least in my environment, I was able to resolve the issue by removing `j = j.astype(numpy.uint)`. Would be interested to hear if others are able to replicate my issue or if it's an artifact of my particular env.

**Comment by JM-Pittman** [comment]
Seems like somewhere between 60k and 70k records, we overflow `numpy.uint`'s default size - changing the typecasts to `numpy.int64` fixed my issues.

**Comment by fgregg** [comment]
thanks for the helpful bug report!

**Comment by fgregg** [comment]
https://github.com/dedupeio/dedupe/commit/ccd983a9098d0967074de26e140d4a489c03a9fa obviates this bugs in that code.
