### ISSUE TITLE
Is dedupe good for deduplicating product names?

### ISSUE THREAD

**Issue by eminos** [dedupeio/dedupe#987]
I tried dedupe on a collection of product names, and the results are not great. I'm not sure if I'm doing anything wrong, or maybe dedupe is just not a good tool for this particular collection.

The fields I'm using are:
- Product name
- Category
- Price (integer, cents)

Product names can be as widely different as:

- Samsung S21
- Mobile phone Galaxy S21 128GB 8GB RAM black

These above are (probably) the same product, even though these strings are very different.

- Samsung Galaxy A12
- Samsung Galaxy A12s

These are different products, even though it's only one character difference.

The category field is also very different. Sometimes missing and sometimes something generic like "Featured".

**Am I right in assuming this kind of deduplication would be really difficult to do with ML at all?**

I'm not looking for perfect matches in all cases, that's probably impossible.

Is there anything I should think about before trying dedupe some more?
Settings? Cleanup the data?

**Comment by fgregg** [comment]
not really a question appropriate for the issue tracker

**Comment by eminos** [comment]
that's what I thought, but where should I ask this then? didn't find a chat server or forum or similar...
