### ISSUE TITLE
Cyclical package dependency: dedupe and dedupe-variable-datetime

### ISSUE THREAD

**Issue by markusmaresch** [dedupeio/dedupe#988]
Both dedupe and the very old dedupe-variable-datetime package depend on EACH other mutually.
Maybe dedupe-variable-datetime is not needed at all ?

In order to check/reproduce:

pip install dedupe

Successfully installed dedupe-2.0.13 dedupe-variable-datetime-0.1.5 ...

pip list | grep dedupe | awk '{print $1}' | xargs pip show | grep -e "Name:" -e "Requires:" | grep dedupe

Could be improved.
Main point: dedupe requres dedupe-variable-datetime and vice versa

**Comment by fgregg** [comment]
this is fine and normal for namespace packages
