### ISSUE TITLE
Is dedupe the right tool for an incremental canonical dataset?

### ISSUE THREAD

**Issue by gbozzetti** [dedupeio/dedupe#989]
Hello dedupers,

I'm wondering if I can successfully use dedupe with the following scenario:

Phase 1:
- I have a messy list A to match against a clean canonical dataset B
- I prepare the training and I mark uncertain pairs, I save the training file and the setting file and I run the search to get my results

Phase 2:
- I receive a messy list C to match against the same canonical dataset B
- I want to use this new list C to increment my training file, so I prepare the training by loading the previous training file, I mark uncertain pairs, I save the new training file and setting file and I run the search to get my results

Phase 3:
- I add new clean rows to my canonical dataset B
- I receive a messy list D to match against the canonical dataset B with new rows
- I want to use this new list D to increment my training file? Can I do that by loading the previous training file obtained from Phase 2 or, since I have a canonical dataset B with new rows, I need to restart the training from scratch?

Thank you very much for your help!

**Comment by fgregg** [comment]
yup. you can use the Dedupe mode for phase 1 and the Gazetter mode for phase 2 and 3.

**Comment by gbozzetti** [comment]
cool! @fgregg thank you for replying.

Is dedupe mode the only method I should use in Phase 1, or I can use Gazetter as well?

Please notice that the canonical dataset B contains only unique entries

**Comment by fgregg** [comment]
sorry yes. just use gazetteer throughout

**Comment by gbozzetti** [comment]
thank you for the clarification @fgregg 

Out of curiosity, how would dedupe perform with strings' matching in different languages? For instance, I have my canonical dataset B that contains names of things in English, and I want to train dedupe with a list A that contains some names of the things in dataset B, both in English and Spanish. So, theoretically I can send a pairs dict like
```python
{'match'    : [
    ({'name':'the name in English'},{'name':'the name in English'}),
    ({'name':'the name in Spanish'},{'name':'the name in English'})
],
'distinct' : []
}
```
but I'm not sure if this will confuse dedupe, resulting in an output with less accuracy
