### ISSUE TITLE
shoud we integrate with scikit learn

### ISSUE THREAD

**Issue by fgregg** [dedupeio/dedupe#991]
Thinking about #990, i'm wondering if we should make scikit learn a dependency.

When we started dedupe 10 years ago, it was really hard to get scipy and scikit learn set up on users machines, but it's not anymore.

It would be nice to get out of the game of implementing some algos ourselves.

Thoughts, @fjsj @NickCrews

**Comment by fjsj** [comment]
I agree, IMO scikit-learn is fairly default and sometimes I see it being used just for model evaluation / visualization, so it ends up being a very common dependency in ML projects.

**Comment by NickCrews** [comment]
I think this move would be well worth it.

Presumably after doing this it would be easy to swap out different classifiers, so a to-do is figuring out how to configure which classifier you want to use.

**Comment by fgregg** [comment]
this is actually very easy, because i've already made so the classifier has the sklearn api.

**Comment by fjsj** [comment]
Here I adapted the code via inheritance to support sklearn classifiers: https://github.com/vintasoftware/deduplication-slides/blob/pycon-2020/rf_dedupe.py

But it's worth checking the conditionals on `def fit` against the current Dedupe version.

**Comment by fgregg** [comment]
closed by #992

**Comment by NickCrews** [comment]
Nice job @fgregg, this looks awesome!
